export default {
  openMode: 'DRAWER_BOTTOM',
  deviewCodeName: 'mob_about10',
  deviewId: '8aab61810a5bacf02cac6d6c997dbb44',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ABOUT',
  },
  caption: '关于（模态下方抽屉弹出）',
  codeName: 'about_mob_about10',
  appDataEntityId: 'web.about',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '左侧工具栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              valignSelf: 'MIDDLE',
                              widthMode: 'FULL',
                            },
                            showCaption: true,
                            id: 'lefttoolbar',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentWidth: 60,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          basis: 100,
                          shrink: 0,
                          layout: 'FLEX',
                          width: 60,
                          widthMode: 'PX',
                        },
                        width: 60,
                        id: 'view_left_toolbar',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '标题栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'captionbar',
                          },
                        ],
                        layout: {
                          align: 'center',
                          dir: 'row',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'view_captionbar',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '工具栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              valignSelf: 'MIDDLE',
                              widthMode: 'FULL',
                            },
                            showCaption: true,
                            id: 'righttoolbar',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentWidth: 100,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          basis: 100,
                          shrink: 0,
                          layout: 'FLEX',
                          width: 100,
                          widthMode: 'PX',
                        },
                        width: 100,
                        id: 'view_right_toolbar',
                      },
                    ],
                    predefinedType: 'Toolbar',
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysCss: {
                      cssName: 'mob-custom-header-style',
                    },
                    id: 'view_toolbar',
                  },
                ],
                predefinedType: 'Header',
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_header',
              },
            ],
            predefinedType: 'PANELPART',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '引用布局面板',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'panelpart',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              sysImage: {
                                rawContent:
                                  '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                              },
                              contentType: 'IMAGE',
                              predefinedType: 'STATIC_IMAGE',
                              id: 'static_image',
                            },
                            caption: '图片',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              layout: 'FLEX',
                            },
                            sysImage: {
                              rawContent:
                                '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                            },
                            showCaption: true,
                            id: 'static_image',
                          },
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                editor: {
                                  halign: 'LEFT',
                                  renderMode: 'TEXT_DYNAMIC',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'name',
                                },
                                viewFieldName: 'name',
                                allowEmpty: true,
                                caption: '文本(动态)',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  shrink: 1,
                                  halignSelf: 'CENTER',
                                  layout: 'FLEX',
                                },
                                id: 'name',
                              },
                            ],
                            predefinedType: 'CONTAINER_SINGLEDATA',
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'SINGLEDATA',
                            dataSourceType: 'DEACTION',
                            appDEMethodId: 'get_about_info',
                            appDataEntityId: 'web.about',
                            caption: '单项数据容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'container_singledata',
                          },
                        ],
                        layout: {
                          dir: 'column',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container_top',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  sysImage: {
                                    cssClass: 'fa fa-desktop',
                                    glyph: 'xf108@FontAwesome',
                                  },
                                  contentType: 'IMAGE',
                                  predefinedType: 'STATIC_IMAGE',
                                  id: 'static_image1',
                                },
                                caption: '图片',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 0,
                                  layout: 'FLEX',
                                },
                                sysImage: {
                                  cssClass: 'fa fa-desktop',
                                  glyph: 'xf108@FontAwesome',
                                },
                                showCaption: true,
                                id: 'static_image1',
                              },
                              {
                                actionGroupExtractMode: 'ITEM',
                                panelItems: [
                                  {
                                    editor: {
                                      halign: 'LEFT',
                                      renderMode: 'TEXT_DYNAMIC',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      editorType: 'SPAN',
                                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'frontendinfo',
                                    },
                                    allowEmpty: true,
                                    caption: '文本(动态)',
                                    itemStyle: 'DEFAULT',
                                    itemType: 'FIELD',
                                    layoutPos: {
                                      shrink: 1,
                                      layout: 'FLEX',
                                    },
                                    id: 'frontendinfo',
                                  },
                                  {
                                    editor: {
                                      halign: 'LEFT',
                                      renderMode: 'TEXT_DYNAMIC',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      editorType: 'SPAN',
                                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'frontendversion',
                                    },
                                    viewFieldName: 'frontendversion',
                                    allowEmpty: true,
                                    caption: '文本(动态)',
                                    itemStyle: 'DEFAULT',
                                    itemType: 'FIELD',
                                    layoutPos: {
                                      shrink: 1,
                                      layout: 'FLEX',
                                    },
                                    id: 'frontendversion',
                                  },
                                ],
                                layout: {
                                  layout: 'FLEX',
                                },
                                dataRegionType: 'INHERIT',
                                caption: '容器',
                                itemStyle: 'DEFAULT',
                                itemType: 'CONTAINER',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                id: 'container_frontend_content',
                              },
                            ],
                            layout: {
                              dir: 'row',
                              layout: 'FLEX',
                              valign: 'center',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'container_frontend',
                          },
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  sysImage: {
                                    cssClass: 'fa fa-server',
                                    glyph: 'xf233@FontAwesome',
                                  },
                                  contentType: 'IMAGE',
                                  predefinedType: 'STATIC_IMAGE',
                                  id: 'static_image2',
                                },
                                caption: '图片',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 0,
                                  layout: 'FLEX',
                                },
                                sysImage: {
                                  cssClass: 'fa fa-server',
                                  glyph: 'xf233@FontAwesome',
                                },
                                showCaption: true,
                                id: 'static_image2',
                              },
                              {
                                actionGroupExtractMode: 'ITEM',
                                panelItems: [
                                  {
                                    editor: {
                                      halign: 'LEFT',
                                      renderMode: 'TEXT_DYNAMIC',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      editorType: 'SPAN',
                                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'backendinfo',
                                    },
                                    viewFieldName: 'backendinfo',
                                    allowEmpty: true,
                                    caption: '文本(动态)',
                                    itemStyle: 'DEFAULT',
                                    itemType: 'FIELD',
                                    layoutPos: {
                                      shrink: 1,
                                      layout: 'FLEX',
                                    },
                                    id: 'backendinfo',
                                  },
                                  {
                                    editor: {
                                      halign: 'LEFT',
                                      renderMode: 'TEXT_DYNAMIC',
                                      valign: 'MIDDLE',
                                      wrapMode: 'NOWRAP',
                                      editorType: 'SPAN',
                                      predefinedType: 'FIELD_TEXT_DYNAMIC',
                                      valueType: 'SIMPLE',
                                      editable: true,
                                      id: 'backendversion',
                                    },
                                    viewFieldName: 'backendversion',
                                    allowEmpty: true,
                                    caption: '文本(动态)',
                                    itemStyle: 'DEFAULT',
                                    itemType: 'FIELD',
                                    layoutPos: {
                                      shrink: 1,
                                      layout: 'FLEX',
                                    },
                                    id: 'backendversion',
                                  },
                                ],
                                layout: {
                                  layout: 'FLEX',
                                },
                                dataRegionType: 'INHERIT',
                                caption: '容器',
                                itemStyle: 'DEFAULT',
                                itemType: 'CONTAINER',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                id: 'container_backend_content',
                              },
                            ],
                            layout: {
                              dir: 'row',
                              layout: 'FLEX',
                              valign: 'center',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'container_backend',
                          },
                        ],
                        predefinedType: 'CONTAINER_SINGLEDATA',
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'SINGLEDATA',
                        dataSourceType: 'CUSTOM',
                        scriptCode:
                          '{frontendinfo:"前端应用由iBiz全动态网页架构：",frontendversion:"["+ibiz.env.appVersion+"] 提供支持",backendinfo:"后台服务由iBiz全动态微服务架构：",backendversion:"["+ibiz.appData.version+"] 提供支持"}',
                        caption: '单项数据容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container_bottom',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container_content',
                  },
                ],
                predefinedType: 'PANELPART',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '引用布局面板',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'panelpart1',
              },
            ],
            layout: {
              align: 'center',
              dir: 'column',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'container',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        sysCss: {
          cssName: 'mob-about-view-layout-style',
        },
        id: 'page_container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.ABOUT',
        },
        caption: '关于（模态下方抽屉弹出）',
        codeName: 'mob_about10_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.about',
        controlParam: {},
        name: 'captionbar',
        id: 'mob_about10_captionbar',
      },
    ],
    codeName: 'usr0822763300',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '关于布局面板',
    appDataEntityId: 'web.about',
    controlParam: {},
    modelId: 'd93505b3b62bdd9e2e06b2421fa32ccf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0822763300',
  },
  title: '关于（模态下方抽屉弹出）',
  viewStyle: 'DEFAULT',
  viewType: 'DEMOBCUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '8a8877ce9cfff42da9e64684accacf63',
  modelType: 'PSAPPDEVIEW',
  name: 'aboutmob_about10',
  id: 'web.about_mob_about10',
};
