export default {
  caption: '面包屑首页视图',
  codeName: 'breadcrumb',
  appViewMsgGroupId: 'breadcrumb',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      halign: 'LEFT',
                      renderMode: 'PARAGRAPH',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      rawItemParams: [
                        {
                          key: 'position',
                          value: 'TOP',
                        },
                      ],
                      predefinedType: 'VIEWMSG_POS',
                      id: 'viewmsg_pos',
                    },
                    caption: '视图消息',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'viewmsg_pos',
                  },
                  {
                    rawItem: {
                      rawItemParams: [
                        {
                          key: 'navmode',
                          value: 'menu',
                          id: 'panelitem',
                        },
                      ],
                      predefinedType: 'NAV_BREADCRUMB',
                      id: 'nav_breadcrumb',
                    },
                    caption: '面包屑导航',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_breadcrumb',
                  },
                  {
                    rawItem: {
                      predefinedType: 'NAV_BREADCRUMB',
                      id: 'nav_breadcrumb1',
                    },
                    caption: '面包屑导航',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_breadcrumb1',
                  },
                  {
                    rawItem: {
                      rawItemParams: [
                        {
                          key: 'navmode',
                          value: 'store',
                          id: 'panelitem1',
                        },
                      ],
                      predefinedType: 'NAV_BREADCRUMB',
                      id: 'nav_breadcrumb2',
                    },
                    caption: '面包屑导航',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_breadcrumb2',
                  },
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS_INDEX',
                      id: 'nav_pos_index',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos_index',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                contentHeight: 100,
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  height: 100,
                  heightMode: 'PERCENTAGE',
                  layout: 'BORDER',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 100,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'APP_APPTITLE',
                      rawItemHeight: 90,
                      id: 'app_apptitle',
                    },
                    caption: '应用标题',
                    contentHeight: 90,
                    height: 90,
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 0,
                      height: 90,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    showCaption: true,
                    id: 'app_apptitle',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              contentType: 'IMAGE',
                              predefinedType: 'USERMESSAGE',
                              id: 'usermessage',
                            },
                            caption: '消息通知',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              widthMode: 'FULL',
                            },
                            showCaption: true,
                            id: 'usermessage',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 48,
                        contentWidth: 48,
                        height: 48,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          height: 48,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 48,
                          widthMode: 'PX',
                        },
                        width: 48,
                        id: 'container1',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionType: 'NONE',
                            buttonHeight: 48,
                            buttonStyle: 'DEFAULT',
                            buttonType: 'PANELBUTTON',
                            buttonWidth: 48,
                            renderMode: 'BUTTON',
                            tooltip: '按钮',
                            uiactionTarget: 'NONE',
                            caption: '按钮',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'FULL',
                            },
                            width: 48,
                            id: 'button_calluilogic1',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 48,
                        contentWidth: 48,
                        height: 48,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          height: 48,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 48,
                          widthMode: 'PX',
                        },
                        width: 48,
                        id: 'container2',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionType: 'NONE',
                            buttonHeight: 48,
                            buttonStyle: 'DEFAULT',
                            buttonType: 'PANELBUTTON',
                            buttonWidth: 48,
                            renderMode: 'BUTTON',
                            tooltip: '按钮',
                            uiactionTarget: 'NONE',
                            caption: '按钮',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'FULL',
                            },
                            width: 48,
                            id: 'button_calluilogic2',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 48,
                        contentWidth: 48,
                        height: 48,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          height: 48,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 48,
                          widthMode: 'PX',
                        },
                        width: 48,
                        id: 'container3',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionType: 'NONE',
                            buttonHeight: 48,
                            buttonStyle: 'DEFAULT',
                            buttonType: 'PANELBUTTON',
                            buttonWidth: 48,
                            renderMode: 'BUTTON',
                            tooltip: '按钮',
                            uiactionTarget: 'NONE',
                            caption: '按钮',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'BUTTON',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'FULL',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'FULL',
                            },
                            width: 48,
                            id: 'button_calluilogic3',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 48,
                        contentWidth: 48,
                        height: 48,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          height: 48,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 48,
                          widthMode: 'PX',
                        },
                        width: 48,
                        id: 'container5',
                      },
                    ],
                    predefinedType: 'INDEX_ACTIONS',
                    layout: {
                      align: 'space-around',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'indexactions',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '文本内容',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'INDEX_VIEW_SEARCH',
                          id: 'index_view_search',
                        },
                        caption: '搜索栏',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'index_view_search',
                      },
                    ],
                    layout: {
                      align: 'center',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 52,
                    height: 52,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 0,
                      height: 52,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container',
                  },
                  {
                    caption: '首页菜单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    showCaption: true,
                    id: 'appmenu',
                  },
                ],
                predefinedType: 'AppHeader',
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'app_header',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_LEFT',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 256,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'WEST',
              layout: 'BORDER',
              width: 256,
              widthMode: 'PX',
            },
            width: 256,
            showCaption: true,
            id: 'container_scroll_left',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        layoutMode: 'TABLE_24COL',
        appMenuItems: [
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 3,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0513634013',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '日历视图',
                tooltip: '日历视图',
                id: 'menuitem3',
              },
              {
                accUserMode: 3,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0513647532',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '看板视图',
                tooltip: '看板视图',
                id: 'menuitem6',
              },
              {
                itemType: 'MENUITEM',
                appMenuItems: [
                  {
                    accUserMode: 3,
                    itemType: 'MENUITEM',
                    appFuncId: 'usrappfunc0513267307',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '表格视图',
                    tooltip: '表格视图',
                    id: 'menuitem4',
                  },
                  {
                    accUserMode: 3,
                    itemType: 'MENUITEM',
                    appFuncId: 'usrappfunc0513353562',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    valid: true,
                    caption: '编辑视图',
                    tooltip: '编辑视图',
                    id: 'menuitem5',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '二级导航',
                tooltip: '二级导航',
                id: 'menuitem2',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '一级导航',
            tooltip: '一级导航',
            id: 'menuitem1',
          },
          {
            accUserMode: 3,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0513647141',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '地图视图',
            tooltip: '地图视图',
            id: 'menuitem7',
          },
          {
            accUserMode: 3,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0513574103',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '图表视图',
            tooltip: '图表视图',
            id: 'menuitem8',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'breadcrumb',
        controlType: 'APPMENU',
        logicName: '面包屑首页视图',
        controlParam: {},
        modelId: 'e383120479889177322bd07ffcfee071',
        modelType: 'PSAPPMENU',
        name: 'appmenu',
        id: 'breadcrumb',
      },
      {
        caption: '面包屑首页视图',
        codeName: 'captionbar',
        controlType: 'CAPTIONBAR',
        controlParam: {},
        id: 'captionbar',
      },
    ],
    codeName: 'a085c49a3bcf5085655',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '应用首页视图布局',
    controlParam: {},
    modelId: 'e86627f71ee5ed6b75e900a3e653adc4',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a085c49a3bcf5085655',
  },
  title: '面包屑首页视图',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b909a4e6be74f6569b4bd3e955149ebf',
  modelType: 'PSAPPINDEXVIEW',
  name: 'breadcrumb',
  id: 'web.breadcrumb',
};
