export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'workflow_design_grid',
  deviewId: '328a10d3e234b28fed992f977536fec0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.CATEGORY',
  },
  caption: '工作流表格',
  codeName: 'category_workflow_design_grid',
  appDataEntityId: 'web.category',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'INDEXVIEWTAB_POPUPMODAL',
          refAppViewId: 'web.category_form_design_edit',
        },
        appUILogicRefViews: [
          {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'web.category_form_design_edit',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'INDEXVIEWTAB_POPUPMODAL',
          refAppViewId: 'web.category_form_design_edit',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'web.category_form_design_edit',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      rawValue: true,
      key: 'sort',
      value: 'sort,asc',
      id: 'sort',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '表单设计',
      refAppViewId: 'web.category_form_design_edit',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '表单设计',
      refAppViewId: 'web.category_form_design_edit',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建类型',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建类型',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'workflow_new@category',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '新建审批单',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建审批单',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'workflow_design_grid_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工作流表格_工具栏',
      appDataEntityId: 'web.category',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'b32be972c7d5bee9eaaf38ee4d572844',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'workflow_design_grid_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CATEGORY.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '流程设计',
                detailType: 'DEUIACTION',
                uiactionId: 'workflow_design@category',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                id: 'u031a8fe',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '新建审批单',
                detailType: 'DEUIACTION',
                uiactionId: 'workflow_new@category',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-file-text-o',
                  glyph: 'xf0f6@FontAwesome',
                },
                id: 'uaf71011',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '查看审批单',
                detailType: 'DEUIACTION',
                uiactionId: 'workflow_approve@category',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-eye',
                  glyph: 'xf06e@FontAwesome',
                },
                id: 'uee5abc5',
              },
            ],
            appDataEntityId: 'web.category',
            uniqueTag: 'category__Usr0630418309',
            name: '工作流',
            id: 'usr0630418309',
          },
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 400,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.category',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.category',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'workflow_design_grid_grid',
      controlType: 'GRID',
      logicName: '工作流表格_表格',
      appDataEntityId: 'web.category',
      controlParam: {
        id: 'grid',
      },
      modelId: 'a44e1ee8cbf0693e1f8803d946533245',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.category.workflow_design_grid_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr06302757_search_form',
      controlType: 'SEARCHFORM',
      logicName: '工作流表格_搜索表单',
      appDataEntityId: 'web.category',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'c582e929b7c4cff28e6f006e4a3b9cd2',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.category.usr06302757_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.category',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.CATEGORY',
      },
      caption: '工作流表格',
      codeName: 'workflow_design_grid_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.category',
      controlParam: {},
      name: 'captionbar',
      id: 'workflow_design_grid_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.category',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作流表格',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f04b4d400938765a2db01f0984fd3200',
  modelType: 'PSAPPDEVIEW',
  name: 'CATEGORYworkflow_design_grid',
  id: 'web.category_workflow_design_grid',
};
