export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'meditpanel_embed',
  deviewId: '780abf2d470f884fb6440a05f4515f75',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DETAIL',
  },
  caption: '多编辑面板_嵌入编辑视图',
  codeName: 'detail_meditpanel_embed',
  appDataEntityId: 'web.detail',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      autoSaveMode: 1,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.detail',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.detail',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.detail',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.detail',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.detail',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.detail',
        id: 'update',
      },
      enableAutoSave: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.DETAIL.NAME',
                  },
                  caption: '项名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 16,
                    colMD: 16,
                    colSM: 16,
                    colXS: 16,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'status',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__cl_status',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'status',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '状态',
                  codeName: 'status',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 8,
                    colSM: 8,
                    colXS: 8,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'status',
                },
              ],
              caption: '明细数据基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.DETAIL.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main3',
      controlType: 'FORM',
      logicName: '多编辑面板_嵌入编辑视图_表单',
      appDataEntityId: 'web.detail',
      controlParam: {
        id: 'form',
      },
      modelId: '36ad7e5318f0ce90b6693e40031d5360',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.detail.main3',
    },
    {
      codeName: 'meditpanel_embed_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.detail',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'meditpanel_embed_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DETAIL',
      },
      caption: '多编辑面板_嵌入编辑视图',
      codeName: 'meditpanel_embed_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.detail',
      controlParam: {},
      name: 'captionbar',
      id: 'meditpanel_embed_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.detail',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '多编辑面板_嵌入编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1b9ab26c063c4541813b8d318ee811dc',
  modelType: 'PSAPPDEVIEW',
  name: 'DETAILmeditpanel_embed',
  id: 'web.detail_meditpanel_embed',
};
