export default {
  gridRowActiveMode: 2,
  enableRowEdit: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'druipart_grid_view',
  deviewId: '6990350fc93219a97f7c34bce6a4952d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DETAIL',
  },
  caption: '明细数据',
  codeName: 'detail_druipart_grid_view',
  appDataEntityId: 'web.detail',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onMounted',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'grid',
      scriptCode: "const grid = view.getCtrl('GRID','grid');\r\ngrid.load();",
      builtinLogic: true,
      id: 'logic_load',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'web.detail_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'web.detail_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'web.detail_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'web.detail_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '明细数据编辑视图',
      refAppViewId: 'web.detail_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '明细数据编辑视图',
      refAppViewId: 'web.detail_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '项名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DETAIL.NAME',
          },
          caption: '项名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'num',
          excelCaption: '数量',
          appDEFieldId: 'num',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '数量',
          codeName: 'num',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'num',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'num',
          valueType: 'SIMPLE',
          dataType: 29,
          id: 'num',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'master_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'master_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '数量',
          codeName: 'num',
          enableCond: 3,
          appDEFieldId: 'num',
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'num',
          },
          allowEmpty: true,
          id: 'num',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEdit: true,
      enableRowNew: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.detail',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.detail',
        id: 'fetch',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.detail',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.detail',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.detail',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.detail',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main3',
      controlType: 'GRID',
      logicName: '表单数据关系界面表格视图_表格',
      appDataEntityId: 'web.detail',
      controlParam: {
        ctrlParams: {
          EDITSHOWMODE: 'cell',
        },
        id: 'grid',
      },
      modelId: '1fb7466d20982f3f65f82fb36c9bde9f',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.detail.main3',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main2',
      controlType: 'SEARCHFORM',
      logicName: '表单数据关系界面表格视图_搜索表单',
      appDataEntityId: 'web.detail',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'c4299e9069860a67774d5381cde1c5cd',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.detail.main2',
    },
    {
      xdataControlName: 'grid',
      codeName: 'druipart_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '表单数据关系界面表格视图_工具栏',
      appDataEntityId: 'web.detail',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'c4243706d96d8298dab0499474d94286',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'druipart_grid_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.detail',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DETAIL',
      },
      caption: '明细数据',
      codeName: 'druipart_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.detail',
      controlParam: {},
      name: 'captionbar',
      id: 'druipart_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.detail',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表单数据关系界面表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'bb019dcf441b8cb37de792cbc0fa562e',
  modelType: 'PSAPPDEVIEW',
  name: 'DETAILdruipart_grid_view',
  id: 'web.detail_druipart_grid_view',
};
