export default {
  accUserMode: 3,
  caption: '应用功能示例',
  codeName: 'func_demo',
  controls: [
    {
      layoutMode: 'TABLE_24COL',
      appMenuItems: [
        {
          accUserMode: 3,
          itemType: 'MENUITEM',
          appFuncId: 'appfunc95',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          caption: '打开应用视图',
          tooltip: '打开应用视图',
          id: 'menuitem1',
        },
        {
          itemType: 'MENUITEM',
          appFuncId: 'appfunc96',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          caption: '打开HTML页面',
          tooltip: '打开HTML页面',
          id: 'menuitem2',
        },
        {
          itemType: 'MENUITEM',
          appFuncId: 'appfunc97',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          caption: '界面行为',
          tooltip: '界面行为',
          id: 'menuitem3',
        },
        {
          itemType: 'MENUITEM',
          appFuncId: 'appfunc98',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          caption: '执行JavaScript',
          tooltip: '执行JavaScript',
          id: 'menuitem4',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      enableCustomized: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'func_demo',
      controlType: 'APPMENU',
      logicName: '应用首页视图',
      controlParam: {},
      modelId: '0fafe3ae15603a9e12f23b7c547b5cd3',
      modelType: 'PSAPPMENU',
      name: 'appmenu',
      id: 'func_demo',
    },
    {
      caption: '应用功能示例',
      codeName: 'captionbar',
      controlType: 'CAPTIONBAR',
      controlParam: {},
      id: 'captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPINDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '应用首页视图',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '298fd4593eda152372643284546a90bd',
  modelType: 'PSAPPINDEXVIEW',
  name: 'func_demo',
  id: 'web.func_demo',
};
