export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_rightnav_month',
  deviewId: 'c5b455069b1aa6bb448e58d590b5ec04',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置导航栏_右侧导航_月',
  codeName: 'master_calendar_rightnav_month',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      calendarStyle: 'MONTH',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          endTimeAppDEFieldId: 'end_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.master',
          navAppViewId: 'web.master_info_view',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'RIGHT',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_rightnav_month',
      controlType: 'CALENDAR',
      logicName: '日历_内置导航栏_右侧导航_月',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'calendar',
      },
      modelId: '16cf9a2264db1e6d6002ebb88e3acd68',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.master.calendar_rightnav_month',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_内置导航栏_右侧导航_月',
      codeName: 'calendar_rightnav_month_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_rightnav_month_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_内置导航栏_右侧导航_月',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1ba6f7152caa832f26332ffbbf7bd8c3',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_rightnav_month',
  id: 'web.master_calendar_rightnav_month',
};
