export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_week',
  deviewId: '75668ad94ae5c9ee673bc7903b7f49cc',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_常规_周',
  codeName: 'master_calendar_week',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      calendarStyle: 'WEEK',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          endTimeAppDEFieldId: 'end_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.master',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_base_week',
      controlType: 'CALENDAR',
      height: 650,
      logicName: '日历_周',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'calendar',
      },
      modelId: '0cfda61193bba6e9ff986c2f0b19d7d6',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.master.calendar_base_week',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_常规_周',
      codeName: 'calendar_week_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_week_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_常规_周',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3ee14490d8a110fde2fab14b7ff551a5',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_week',
  id: 'web.master_calendar_week',
};
