export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'drtab_logic_hidden',
  deviewId: '8481c15dd0cb3eb439560fe8bc664a83',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '数据关系分页_隐藏表单项逻辑',
  codeName: 'master_drtab_logic_hidden',
  height: 700,
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup38',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '显示',
          appViewId: 'web.master_drtab_show_edit',
          id: 'show',
        },
        {
          caption: '隐藏',
          appViewId: 'web.master_drtab_hidden_edit',
          id: 'hidden',
        },
      ],
      dataRelationTag: 'drtab_logic_hidden',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_drtab_logic_hidden__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'drtab_logic_hidden',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '6700af587d044613a8496a9c9fd71e83',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'drtab_logic_hidden',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '数据关系分页_隐藏表单项逻辑',
      codeName: 'drtab_logic_hidden_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'drtab_logic_hidden_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据关系分页_隐藏表单项逻辑',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '210b6857526454a351e624ac5c41de3d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdrtab_logic_hidden',
  id: 'web.master_drtab_logic_hidden',
};
