export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_default_sort',
  deviewId: '79DC35D8-1B39-4236-BEDD-DAAE753C0DA6',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_默认排序',
  codeName: 'master_card_default_sort',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      cardHeight: 60,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'ASC',
      minorSortAppDEFieldId: 'px',
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          frontCodeListId: 'web.mock__cl_categories',
          appDEFieldId: 'type',
          dataType: 25,
          id: 'type',
        },
        {
          frontCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          dataType: 9,
          id: 'status',
        },
        {
          appDEFieldId: 'px',
          dataType: 9,
          id: 'px',
        },
        {
          appDEFieldId: 'quantity',
          dataType: 6,
          id: 'quantity',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      dedataViewItems: [
        {
          clconvertMode: 'FRONT',
          caption: '类型',
          dataItemName: 'type',
          itemType: 'DATAITEM',
          appDEFieldId: 'type',
          codeListId: 'web.mock__cl_categories',
          enableSort: true,
          name: 'TYPE',
          id: 'type',
        },
        {
          clconvertMode: 'FRONT',
          caption: '状态',
          dataItemName: 'status',
          itemType: 'DATAITEM',
          appDEFieldId: 'status',
          codeListId: 'web.mock__cl_status',
          enableSort: true,
          name: 'STATUS',
          id: 'status',
        },
        {
          caption: '排序',
          dataItemName: 'px',
          itemType: 'DATAITEM',
          appDEFieldId: 'px',
          enableSort: true,
          name: 'PX',
          id: 'px',
        },
        {
          caption: '数量',
          dataItemName: 'quantity',
          itemType: 'DATAITEM',
          appDEFieldId: 'quantity',
          enableSort: true,
          name: 'QUANTITY',
          id: 'quantity',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_default_sort',
      controlType: 'DATAVIEW',
      logicName: '卡片_默认排序',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: 'bd54da722d120f23ab4bcdc0b40bd614',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_default_sort',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_默认排序',
      codeName: 'card_default_sort_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_default_sort_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_默认排序',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5e0d92cb4d4fc0510816e851db2f7a16',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_default_sort',
  id: 'web.master_card_default_sort',
};
