export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'grid_group',
  deviewId: '6365c75b375f412d31216ba570e76aa8',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_分组',
  codeName: 'master_grid_group',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '自动分组',
          appViewId: 'web.master_grid_group_auto',
          id: 'auto',
        },
        {
          caption: '分组代码表',
          appViewId: 'web.master_grid_group_codelist',
          id: 'codelist',
        },
      ],
      dataRelationTag: 'DataRelation28',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_grid_group__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation28',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '6a29a24b7a155e227115747a271e59db',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation28',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格_分组',
      codeName: 'grid_group_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_group_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格_分组',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ee70955699cba9477fc066836cb711fd',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_group',
  id: 'web.master_grid_group',
};
