export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'app_portal_demo_grid_view',
  deviewId: '30c6b7ec716ac9c4ac61aa3cbc994495',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '门户部件演示表格视图',
  codeName: 'master_app_portal_demo_grid_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MASTER.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'date',
          excelCaption: '日期',
          appDEFieldId: 'date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '日期',
          codeName: 'date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'quantity',
          excelCaption: '数量',
          appDEFieldId: 'quantity',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '数量',
          codeName: 'quantity',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'quantity',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'date',
        },
        {
          appDEFieldId: 'quantity',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'quantity',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'region_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'category_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdatatype',
        },
        {
          appDEFieldId: 'category_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_type',
        },
        {
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'wf_status',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'wf_status',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 10,
      sortMode: 'REMOTE',
      hasWFDataItems: true,
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_grid',
      controlType: 'GRID',
      logicName: '表格视图_表格',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'grid',
      },
      modelId: 'f45f40d7336ddf7c9907cf21eccffb3f',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.master.grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '请输入名称',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.MASTER.N_NAME_LIKE',
              },
              caption: '名称(%)',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_name_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'region_name',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_region_name_like',
              },
              allowEmpty: true,
              caption: '区划名称(%)',
              codeName: 'n_region_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_region_name_like',
            },
            {
              dataType: 6,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'quantity',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_quantity_ltandeq',
              },
              allowEmpty: true,
              caption: '数量(<=)',
              codeName: 'n_quantity_ltandeq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_quantity_ltandeq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'type',
              editor: {
                singleSelect: true,
                appCodeListId: 'web.mock__cl_categories',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_type_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '类型(=)',
              codeName: 'n_type_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 6,
                colMD: 6,
                colSM: 6,
                colXS: 6,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_type_eq',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main239',
      controlType: 'SEARCHFORM',
      logicName: '搜索表单_转换参数模式',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          CONVERTPARAMMODE: 'searchconds',
        },
        id: 'searchform',
      },
      modelId: '6090ec229415d7278b681e070dbcd9b1',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.main239',
    },
    {
      groupMode: 'SINGLE',
      groupMoreText: '更多',
      searchBarFilters: [
        {
          dataType: 9,
          labelPos: 'NONE',
          editor: {
            singleSelect: true,
            appCodeListId: 'web.mock__cl_status',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'n_status_eq',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          itemType: 'FILTER',
          appDEFieldId: 'status',
          id: 'n_status_eq',
        },
        {
          dataType: 25,
          labelPos: 'NONE',
          defsearchMode: {
            codeName: 'N_TYPE_EQ',
            stdDataType: 25,
            valueOP: 'EQ',
            name: 'N_TYPE_EQ',
            id: 'n_type_eq',
          },
          editor: {
            singleSelect: true,
            appCodeListId: 'web.mock__cl_categories',
            editorType: 'DROPDOWNLIST',
            valueType: 'SIMPLE',
            editable: true,
            id: 'n_type_eq',
          },
          allowEmpty: true,
          needCodeListConfig: true,
          caption: '类型',
          itemType: 'FILTER',
          appDEFieldId: 'type',
          id: 'n_type_eq',
        },
        {
          dataType: 6,
          labelPos: 'NONE',
          defsearchMode: {
            codeName: 'N_QUANTITY_LT',
            stdDataType: 6,
            valueOP: 'LT',
            name: 'N_QUANTITY_LT',
            id: 'n_quantity_lt',
          },
          editor: {
            editorType: 'TEXTBOX',
            placeHolder: '请输入数量',
            valueType: 'SIMPLE',
            editable: true,
            id: 'n_quantity_lt',
          },
          allowEmpty: true,
          caption: '数量',
          itemType: 'FILTER',
          appDEFieldId: 'quantity',
          id: 'n_quantity_lt',
        },
        {
          dataType: 6,
          labelPos: 'NONE',
          defsearchMode: {
            codeName: 'N_QUANTITY_GT',
            stdDataType: 6,
            valueOP: 'GT',
            name: 'N_QUANTITY_GT',
            id: 'n_quantity_gt',
          },
          editor: {
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'n_quantity_gt',
          },
          allowEmpty: true,
          caption: '数量',
          itemType: 'FILTER',
          appDEFieldId: 'quantity',
          id: 'n_quantity_gt',
        },
      ],
      searchBarGroups: [
        {
          defaultGroup: true,
          caption: '全部',
          itemType: 'GROUP',
          id: 'all',
        },
        {
          caption: '正常',
          data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"1"}]}]}}',
          itemType: 'GROUP',
          appDEFieldId: 'status',
          id: 'status_1',
        },
        {
          caption: '停用',
          data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"0"}]}]}}',
          itemType: 'GROUP',
          appDEFieldId: 'status',
          id: 'status_0',
        },
      ],
      quickGroupCount: 3,
      quickSearchMode: 2,
      quickSearchWidth: 300,
      searchBarStyle: 'SEARCHBAR2',
      enableFilter: true,
      enableGroup: true,
      enableQuickSearch: true,
      codeName: 'usr0516231784',
      controlType: 'SEARCHBAR',
      logicName: '搜索栏_高级',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      modelId: '25b03ee8f0b49425146e6610d381d52d',
      modelType: 'PSSYSSEARCHBAR',
      name: 'searchbar',
      id: 'web.master.usr0516231784',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '门户部件演示表格视图',
      codeName: 'app_portal_demo_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'app_portal_demo_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '门户部件演示表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '48deec144e8fb91920442f2e9ec42635',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERapp_portal_demo_grid_view',
  id: 'web.master_app_portal_demo_grid_view',
};
