export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'editor_stepper',
  deviewId: '1649749c9104bb2b75236e2d440fcf10',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_步进器',
  codeName: 'master_editor_stepper',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'editor_stepper',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'editor_stepper_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_步进器_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '858e4ba4961e408006591b21cb709332',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editor_stepper_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '这是步进器内容',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    stepValue: 1,
                    editorType: 'STEPPER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  updateDV: '这是步进器内容',
                  allowEmpty: true,
                  caption: '步进器',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: '步进器',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    stepValue: 2,
                    editorParams: {
                      stepvalue: '2',
                    },
                    editorType: 'STEPPER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用stepvalue参数指定递增递减的步进值。当前的步进值为2，每次增加会加2，每次减少会减2',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: '步进控制',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    stepValue: 1,
                    precision: 2,
                    scale: 2,
                    editorParams: {
                      precision: '2',
                    },
                    editorType: 'STEPPER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem2',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用precision参数控制步进器的精度。当前步进器的精度为2位小数',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
              ],
              caption: '数值精度',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    stepValue: 1,
                    maxValue: 10,
                    editorParams: {
                      minvalue: '0',
                      maxvalue: '10',
                    },
                    editorType: 'STEPPER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用maxvalue和minvalue参数指定步进器允许的最大最小值。当前步进器最大值为10，最小值为0',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
              ],
              caption: '最大最小值',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '12',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    stepValue: 1,
                    editorParams: {
                      readonly: 'true',
                    },
                    editorType: 'STEPPER',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem4',
                  },
                  updateDV: '12',
                  allowEmpty: true,
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用readonly参数控制编辑器是否为只读态。当前编辑器为只读态',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem4',
                  },
                  codeName: 'rawitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem4',
                },
              ],
              caption: '只读态',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '步进器',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'editor_stepper_form',
      controlType: 'FORM',
      logicName: '编辑器_步进器_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'aa50a8c5efa862ffb16464ba30d3745b',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.editor_stepper_form',
    },
    {
      codeName: 'editor_stepper_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editor_stepper_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_步进器',
      codeName: 'editor_stepper_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editor_stepper_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_步进器',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c172964d3b56c5b9e6ca767957802974',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditor_stepper',
  id: 'web.master_editor_stepper',
};
