export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'ChartGridTabExpView',
  deviewId: 'befa14f7f117090ae93e9256c6367886',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表数据表格',
  codeName: 'master_chart_grid_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'chartgrid',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '单序列图表表格',
          appViewId: 'web.master_chart_grid_view_base',
          id: 'base',
        },
        {
          caption: '多序列图表表格',
          appViewId: 'web.master_chart_grid_mul_series',
          id: 'mulseries',
        },
        {
          caption: '复合序列图表表格',
          appViewId: 'web.master_usr8928_chart_view',
          id: 'repeat_series',
        },
      ],
      dataRelationTag: 'DataRelation123',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_chart_grid_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation123',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'af23598fa0baf56781d703f66bcc57aa',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation123',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表数据表格',
      codeName: 'chart_grid_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_grid_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表数据表格',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '15d4789e8c6d4910be4ed1b9201cc03b',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERChartGridTabExpView',
  id: 'web.master_chart_grid_tab_exp_view',
};
