export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'card_sort_exp',
  deviewId: '0ECBBCE3-5687-4F75-9D31-F2D659650269',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_排序导航视图',
  codeName: 'master_card_sort_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '默认排序',
          appViewId: 'web.master_card_default_sort',
          id: 'card_default_sort',
        },
        {
          caption: '禁用排序',
          appViewId: 'web.master_card_disable_sort',
          id: 'card_disable_sort',
        },
      ],
      dataRelationTag: 'DataRelation47',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_card_sort_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation47',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '0dc9fc30b1bd055bff579281e13cf85d',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation47',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_排序导航视图',
      codeName: 'card_sort_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_sort_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_排序导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '04f496be8ef4b738614e986c725bcda7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_sort_exp',
  id: 'web.master_card_sort_exp',
};
