export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendar_nav_month',
  deviewId: 'bc5f5cc42fb39af3671394ed5b93a21b',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置导航栏_月',
  codeName: 'master_calendar_nav_month',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '右侧导航',
          appViewId: 'web.master_calendar_rightnav_month',
          id: 'right',
        },
        {
          caption: '下方导航',
          appViewId: 'web.master_calendar_bottomnav_month',
          id: 'bottom',
        },
      ],
      dataRelationTag: 'calendar_nav_month_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar_nav_month__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_nav_month_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          ENABLENAVBAR: 'false',
        },
        id: 'tabexppanel',
      },
      modelId: 'c9019bbdfe651ea171e6272c68131e0e',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'calendar_nav_month_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_内置导航栏_月',
      codeName: 'calendar_nav_month_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_nav_month_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_内置导航栏_月',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd6513aafda3f47d8d415b933bd60a22f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_nav_month',
  id: 'web.master_calendar_nav_month',
};
