export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'cancel_change',
  deviewId: '0b24dbc39e081a19d667eb29543eb1cf',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '取消变更',
  codeName: 'master_cancel_change',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onFormDataChange',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'form',
      scriptCode:
        'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
      builtinLogic: true,
      id: 'logic1',
    },
    {
      eventNames: 'onMounted',
      logicTrigger: 'VIEWEVENT',
      logicType: 'SCRIPT',
      scriptCode:
        'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});\r\n',
      builtinLogic: true,
      id: 'logic',
    },
  ],
  appViewMsgGroupId: 'form_cancel_change',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  appViewParams: [
    {
      key: 'SRFRENEWSESSION',
      value: 'true',
      name: 'SRFRENEWSESSION',
      id: 'srfrenewsession',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'data_cancelchanges',
          valid: true,
          caption: '取消变更',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'deuiaction1',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode:
                'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
              triggerType: 'ITEMVISIBLE',
              id: 'logic',
            },
          ],
          tooltip: '取消变更',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      xdataControlName: 'form',
      codeName: 'cancel_change_toolbar',
      controlType: 'TOOLBAR',
      logicName: '取消变更_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '8493e189ff4846dcdb19c9703550bdbc',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'cancel_change_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.MASTER.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
              ],
              caption: '基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  buildInActions: 7,
                  contentControl: {
                    aggMode: 'NONE',
                    columnEnableFilter: 2,
                    columnEnableLink: 2,
                    groupMode: 'NONE',
                    groupStyle: 'DEFAULT',
                    degridColumns: [
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'name',
                        excelCaption: '项名称',
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        enableRowEdit: true,
                        aggMode: 'NONE',
                        align: 'LEFT',
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DETAIL.NAME',
                        },
                        caption: '项名称',
                        codeName: 'name',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 150,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'name',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'num',
                        excelCaption: '数量',
                        appDEFieldId: 'num',
                        valueType: 'SIMPLE',
                        enableRowEdit: true,
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '数量',
                        codeName: 'num',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'num',
                      },
                    ],
                    degridDataItems: [
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'name',
                      },
                      {
                        appDEFieldId: 'num',
                        valueType: 'SIMPLE',
                        dataType: 29,
                        id: 'num',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfkey',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfdataaccaction',
                      },
                      {
                        appDEFieldId: 'master_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'master_id',
                      },
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfmajortext',
                      },
                    ],
                    degridEditItems: [
                      {
                        caption: '项名称',
                        codeName: 'name',
                        enableCond: 3,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        id: 'name',
                      },
                      {
                        caption: '数量',
                        codeName: 'num',
                        enableCond: 3,
                        appDEFieldId: 'num',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'num',
                        },
                        allowEmpty: true,
                        id: 'num',
                      },
                      {
                        caption: '标识',
                        codeName: 'srfkey',
                        enableCond: 3,
                        appDEFieldId: 'id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfkey',
                        },
                        allowEmpty: true,
                        id: 'srfkey',
                      },
                    ],
                    pagingMode: 1,
                    pagingSize: 20,
                    sortMode: 'REMOTE',
                    hasWFDataItems: true,
                    enableCustomized: true,
                    enablePagingBar: true,
                    enableRowEdit: true,
                    enableRowNew: true,
                    navViewPos: 'NONE',
                    createControlAction: {
                      appDEMethodId: 'create',
                      appDataEntityId: 'web.detail',
                      id: 'create',
                    },
                    fetchControlAction: {
                      appDEMethodId: 'fetch_default',
                      appDataEntityId: 'web.detail',
                      id: 'fetch',
                    },
                    getDraftControlAction: {
                      appDEMethodId: 'get_draft',
                      appDataEntityId: 'web.detail',
                      id: 'loaddraft',
                    },
                    getControlAction: {
                      appDEMethodId: 'get',
                      appDataEntityId: 'web.detail',
                      id: 'load',
                    },
                    removeControlAction: {
                      appDEMethodId: 'remove',
                      appDataEntityId: 'web.detail',
                      id: 'remove',
                    },
                    updateControlAction: {
                      appDEMethodId: 'update',
                      appDataEntityId: 'web.detail',
                      id: 'update',
                    },
                    autoLoad: true,
                    showBusyIndicator: true,
                    codeName: 'main2',
                    controlType: 'GRID',
                    logicName: '表单多数据表格',
                    appDataEntityId: 'web.detail',
                    controlParam: {},
                    modelId: 'fec07763d9aca01df76bb83ae82ad802',
                    modelType: 'PSDEGRID',
                    name: 'mdctrl1_grid',
                    id: 'web.detail.main2',
                  },
                  contentType: 'GRID',
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  codeName: 'mdctrl1',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'mdctrl1',
                },
              ],
              caption: '明细数据',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'web.detail_master_drpart',
                  parentDataJO: {
                    SRFPARENTTYPE: 'DER1N',
                    srfparentdename: 'MASTER',
                    srfparentmode: 'DER1N_DETAIL_MASTER_MASTER_ID',
                    srfparentdefname: 'MASTER_ID',
                    SRFDER1NID: 'DER1N_DETAIL_MASTER_MASTER_ID',
                  },
                  codeName: 'druipart1',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart1',
                },
              ],
              caption: '关系界面',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main214',
      controlType: 'FORM',
      logicName: '取消变更_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '943e4894b488bd154535893b1d1b536e',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main214',
    },
    {
      codeName: 'cancel_change_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'cancel_change_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '取消变更',
      codeName: 'cancel_change_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'cancel_change_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '取消变更',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'e28dd63737f4a98f00ea7bc0d451f496',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcancel_change',
  id: 'web.master_cancel_change',
};
