export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'editform_mdctrl_group_action',
  deviewId: '9e13ad65bd29f14c1afe519a5a5b60db',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑表单_多数据部件行为组',
  codeName: 'master_editform_mdctrl_group_action',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              actionGroupExtractMode: 'ITEM',
              buildInActions: 7,
              contentControl: {
                aggMode: 'NONE',
                columnEnableFilter: 2,
                columnEnableLink: 2,
                groupMode: 'NONE',
                groupStyle: 'DEFAULT',
                degridColumns: [
                  {
                    clconvertMode: 'NONE',
                    dataItemName: 'name',
                    excelCaption: '项名称',
                    appDEFieldId: 'name',
                    valueType: 'SIMPLE',
                    enableRowEdit: true,
                    aggMode: 'NONE',
                    align: 'LEFT',
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.DETAIL.NAME',
                    },
                    caption: '项名称',
                    codeName: 'name',
                    columnType: 'DEFGRIDCOLUMN',
                    noPrivDisplayMode: 1,
                    width: 150,
                    widthUnit: 'PX',
                    enableSort: true,
                    id: 'name',
                  },
                  {
                    clconvertMode: 'NONE',
                    dataItemName: 'num',
                    excelCaption: '数量',
                    appDEFieldId: 'num',
                    valueType: 'SIMPLE',
                    enableRowEdit: true,
                    aggMode: 'NONE',
                    align: 'LEFT',
                    caption: '数量',
                    codeName: 'num',
                    columnType: 'DEFGRIDCOLUMN',
                    noPrivDisplayMode: 1,
                    width: 100,
                    widthUnit: 'PX',
                    enableSort: true,
                    id: 'num',
                  },
                ],
                degridDataItems: [
                  {
                    appDEFieldId: 'name',
                    valueType: 'SIMPLE',
                    dataType: 25,
                    id: 'name',
                  },
                  {
                    appDEFieldId: 'num',
                    valueType: 'SIMPLE',
                    dataType: 29,
                    id: 'num',
                  },
                  {
                    appDEFieldId: 'id',
                    valueType: 'SIMPLE',
                    dataType: 25,
                    id: 'srfkey',
                  },
                  {
                    appDEFieldId: 'id',
                    valueType: 'SIMPLE',
                    dataType: 25,
                    id: 'srfdataaccaction',
                  },
                  {
                    appDEFieldId: 'master_id',
                    valueType: 'SIMPLE',
                    dataType: 25,
                    id: 'master_id',
                  },
                  {
                    appDEFieldId: 'name',
                    valueType: 'SIMPLE',
                    dataType: 25,
                    id: 'srfmajortext',
                  },
                ],
                degridEditItems: [
                  {
                    caption: '项名称',
                    codeName: 'name',
                    enableCond: 3,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    id: 'name',
                  },
                  {
                    caption: '数量',
                    codeName: 'num',
                    enableCond: 3,
                    appDEFieldId: 'num',
                    editor: {
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'num',
                    },
                    allowEmpty: true,
                    id: 'num',
                  },
                  {
                    caption: '标识',
                    codeName: 'srfkey',
                    enableCond: 3,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'srfkey',
                    },
                    allowEmpty: true,
                    id: 'srfkey',
                  },
                ],
                pagingMode: 1,
                pagingSize: 20,
                sortMode: 'REMOTE',
                hasWFDataItems: true,
                enableCustomized: true,
                enablePagingBar: true,
                enableRowEdit: true,
                enableRowNew: true,
                navViewPos: 'NONE',
                createControlAction: {
                  appDEMethodId: 'create',
                  appDataEntityId: 'web.detail',
                  id: 'create',
                },
                fetchControlAction: {
                  appDEMethodId: 'fetch_default',
                  appDataEntityId: 'web.detail',
                  id: 'fetch',
                },
                getDraftControlAction: {
                  appDEMethodId: 'get_draft',
                  appDataEntityId: 'web.detail',
                  id: 'loaddraft',
                },
                getControlAction: {
                  appDEMethodId: 'get',
                  appDataEntityId: 'web.detail',
                  id: 'load',
                },
                removeControlAction: {
                  appDEMethodId: 'remove',
                  appDataEntityId: 'web.detail',
                  id: 'remove',
                },
                updateControlAction: {
                  appDEMethodId: 'update',
                  appDataEntityId: 'web.detail',
                  id: 'update',
                },
                autoLoad: true,
                showBusyIndicator: true,
                codeName: 'main2',
                controlType: 'GRID',
                logicName: '表单多数据表格',
                appDataEntityId: 'web.detail',
                controlParam: {},
                modelId: 'fec07763d9aca01df76bb83ae82ad802',
                modelType: 'PSDEGRID',
                name: 'mdctrl1_grid',
                id: 'web.detail.main2',
              },
              contentType: 'GRID',
              appDEFieldId: 'details',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    capLanguageRes: {
                      lanResTag: 'TBB.TEXT.*.SAVE',
                    },
                    caption: '保存',
                    detailType: 'DEUIACTION',
                    uiactionId: 'editview_saveaction',
                    tooltipLanguageRes: {
                      lanResTag: 'TBB.TOOLTIP.*.SAVE',
                    },
                    showCaption: true,
                    showIcon: true,
                    sysImage: {
                      cssClass: 'fa fa-save',
                      glyph: 'xf0c7@FontAwesome',
                    },
                    id: 'u0364614',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      uiactionGroupDetails: [
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '打开关于',
                          detailType: 'DEUIACTION',
                          uiactionId: 'open_about@master',
                          showCaption: true,
                          showIcon: true,
                          sysImage: {
                            cssClass: 'fa fa-info-circle',
                            glyph: 'xf05a@FontAwesome',
                          },
                          id: 'u1b2c7f7',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '打开文档',
                          detailType: 'DEUIACTION',
                          uiactionId: 'open_document@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'u77f70f9',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '打开弹窗',
                          detailType: 'DEUIACTION',
                          uiactionId: 'open_dialog@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'ufa9f69d',
                        },
                      ],
                      name: 'More',
                      id: 'more',
                    },
                    addSeparator: true,
                    showCaption: true,
                    showIcon: true,
                    id: 'u4a20692',
                  },
                ],
                appDataEntityId: 'web.master',
                id: '表单多数据部件界面行为组',
              },
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              caption: '多数据部件行为组',
              codeName: 'mdctrl1',
              detailStyle: 'DEFAULT',
              detailType: 'MDCTRL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'mdctrl1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'editform_mdctrl_group_action',
      controlType: 'FORM',
      logicName: '编辑表单_多数据部件_界面行为组',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '725c4dc1c77d46b5450218b4f1250598',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.editform_mdctrl_group_action',
    },
    {
      codeName: 'editform_mdctrl_group_action_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editform_mdctrl_group_action_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑表单_多数据部件行为组',
      codeName: 'editform_mdctrl_group_action_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editform_mdctrl_group_action_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑表单_多数据部件行为组',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '68c2ed22ba2a2b4d0a1ca95d7051a7bf',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditform_mdctrl_group_action',
  id: 'web.master_editform_mdctrl_group_action',
};
