export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'map_event_and_call',
  deviewId: '068a77ccd8470289aff8ed4f7fd78110',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '地图_事件及调用',
  codeName: 'master_map_event_and_call',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '事件',
          appViewId: 'web.master_map_event',
          id: 'event',
        },
        {
          caption: '能力',
          appViewId: 'web.master_map_ability',
          id: 'ability',
        },
      ],
      dataRelationTag: 'DataRelation94',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_map_event_and_call__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation94',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '514add61fe9da3fd4d7f1821e70d89c3',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation94',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '地图_事件及调用',
      codeName: 'map_event_and_call_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'map_event_and_call_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '地图_事件及调用',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '6d5ee88db07a0621be9987cbc88a3b4f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERmap_event_and_call',
  id: 'web.master_map_event_and_call',
};
