export default {
  deviewCodeName: 'toolbar_counter',
  deviewId: '693105f2c0b77f0618353289e53739ad',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '工具栏计数器',
  codeName: 'master_toolbar_counter',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'vmgroup5',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            rawItem: {
              predefinedType: 'VIEWMSG_POS',
              id: 'viewmsg_pos',
            },
            caption: '视图消息占位',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'viewmsg_pos',
          },
          {
            caption: '工具栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingLeft: 'OUTERMEDIUM',
              spacingRight: 'OUTERMEDIUM',
            },
            showCaption: true,
            id: 'toolbar',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    appCounterRefs: [
      {
        appCounter: {
          codeName: 'Counter',
          counterType: 'DEDR',
          getAppDEActionId: 'get_counter_data',
          appDataEntityId: 'web.master',
          timer: 60000,
          uniqueTag: 'Counter',
          name: '计数器',
          id: 'web.counter',
        },
        tag: 'c08c472f59332aa507b4952a6d4e5c5f',
        uniqueTag: 'Counter',
        id: 'c08c472f59332aa507b4952a6d4e5c5f',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_refreshaction',
            valid: true,
            caption: '刷新',
            counterId: 'form',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-refresh',
              glyph: 'xf021@FontAwesome',
            },
            tooltip: '刷新',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建',
            counterId: 'menu',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
        ],
        codeName: 'toolbar_counter_toolbar',
        controlType: 'TOOLBAR',
        logicName: '计数器',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '3e111386fb122ccc5033767938db77e0',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'toolbar_counter_toolbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '工具栏计数器',
        codeName: 'toolbar_counter_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'toolbar_counter_captionbar',
      },
    ],
    codeName: 'auto79361922',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'toolbar_counter',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'e8c978b46f0fcb97967e8f96f0edf147',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto79361922',
  },
  title: '工具栏计数器',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'bd99052201655c0ef81ac60c5792a664',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtoolbar_counter',
  id: 'web.master_toolbar_counter',
};
