export default {
  tabLayout: 'TOP',
  loadDefault: true,
  deviewCodeName: 'ctrl_event_trigger',
  deviewId: 'dafeee8365cf0735935d31285c3aebed',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '部件事件触发',
  codeName: 'master_ctrl_event_trigger',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '表格部件',
          appViewId: 'web.master_ctrl_event_grid_trigger',
          id: 'grid',
        },
        {
          caption: '表单部件',
          appViewId: 'web.master_ctrl_event_form_trigger',
          id: 'form',
        },
      ],
      dataRelationTag: 'DataRelation11',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_ctrl_event_trigger__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation11',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '555be228f3d03a4e3f6b3f0ab744bb2d',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation11',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '部件事件触发',
      codeName: 'ctrl_event_trigger_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'ctrl_event_trigger_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '部件事件触发',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '023367f4f3a46bdbb1624ecc19f14a32',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERctrl_event_trigger',
  id: 'web.master_ctrl_event_trigger',
};
