export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'Pickup_treempickupview2',
  deviewId: 'f47b5dabf27521868b1796ec9f32618c',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树多项数据选择视图（左右关系）',
  codeName: 'master_pickup_treempickupview2',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      eventNames: 'onSelectionChange',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'pickupviewpanel',
      scriptCode:
        "const tips = '选择视图面板的选中数据变更事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips, `选中数据:`, data);",
      builtinLogic: true,
      id: 'logic',
    },
  ],
  appViewMsgGroupId: 'pickup_eventandcall',
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'all',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-根节点（node）',
              id: '默认根节点（root）-根节点（node）',
            },
            {
              childDETreeNodeId: 'enable',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-正常（enable）',
              id: '默认根节点（root）-正常（enable）',
            },
            {
              childDETreeNodeId: 'disable',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-停用（disable）',
              id: '默认根节点（root）-停用（disable）',
            },
          ],
          detreeNodes: [
            {
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '全部',
              nodeType: 'all',
              treeNodeType: 'STATIC',
              name: '全部',
              id: 'all',
            },
            {
              text: '停用',
              nodeType: 'disable',
              navigateParams: [
                {
                  key: 'n_status_eq',
                  value: '0',
                  rawValue: true,
                  id: 'n_status_eq',
                },
              ],
              treeNodeType: 'STATIC',
              name: '停用',
              id: 'disable',
            },
            {
              text: '正常',
              nodeType: 'enable',
              navigateParams: [
                {
                  key: 'n_status_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_status_eq',
                },
              ],
              treeNodeType: 'STATIC',
              name: '正常',
              id: 'enable',
            },
          ],
          outputIconDefault: true,
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.master',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'web.master',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.master',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'pickup_pickupview2_tree_view',
          controlType: 'TREEVIEW',
          logicName: '选择视图面板_数据选择视图（左右关系）_树视图',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          modelId: '1548d405c97707a8548330b7b7c76ad9',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'web.master.pickup_pickupview2_tree_view',
        },
      ],
      codeName: 'pickup_treempickupview2_treeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '4ed2ba80715b19240a8f05fdb752d5d6_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'pickup_treempickupview2_treeexpbar',
    },
    {
      embeddedAppDEViewId: 'web.master_pickup_treepickupcontrolview',
      codeName: 'pickup_treempickupview2_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_treempickupview2_pickupviewpanel',
    },
    {
      codeName: 'pickup_treempickupview2_toolbar',
      controlType: 'TOOLBAR',
      logicName: '选择视图面板工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fa9213d29a94558349d0f4fd85a15a32',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'pickup_treempickupview2_toolbar',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'region_id',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'category_type',
          dataType: 25,
          id: 'srfdatatype',
        },
        {
          appDEFieldId: 'category_type',
          dataType: 25,
          id: 'category_type',
        },
        {
          appDEFieldId: 'category_id',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'wf_status',
          frontCodeListId: 'web.wfstates',
          dataType: 25,
          id: 'wf_status',
        },
      ],
      pagingSize: 1000,
      hasWFDataItems: true,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_pickup',
      controlType: 'LIST',
      logicName: 'list_pickup',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'simplelist',
      },
      modelId: 'cb444557d0d3712d008bb5cbd4cb7e58',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'web.master.list_pickup',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树多项数据选择视图（左右关系）',
      codeName: 'pickup_treempickupview2_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_treempickupview2_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW2',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_树多项数据选择视图（左右关系）',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW2',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4ed2ba80715b19240a8f05fdb752d5d6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_treempickupview2',
  id: 'web.master_pickup_treempickupview2',
};
