export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_dy_uiaction_group_embed',
  deviewId: '743d6c83c3c9637c51c09e08b34f55f6',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_成员为动态界面行为组',
  codeName: 'master_card_dy_uiaction_group_embed',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'vmgroup311',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      cardHeight: 120,
      cardWidth: 300,
      groupLayout: 'ROW',
      groupMode: 'CODELIST',
      groupAppDEFieldId: 'status',
      groupCodeListId: 'web.mock__cl_status',
      groupUIActionGroup: {
        uiactionGroupDetails: [
          {
            actionLevel: 100,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            caption: '打开弹窗',
            detailType: 'DEUIACTION',
            uiactionId: 'open_dialog@master',
            showCaption: true,
            showIcon: true,
            id: 'u6d34e27',
          },
          {
            actionLevel: 100,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            detailType: 'DEUIACTIONGROUP',
            refUIActionGroup: {
              dynamicMode: 1,
              actionLevelAppDEFieldId: 'level',
              buttonStyleAppDEFieldId: 'button_style',
              clsAppDEFieldId: 'style',
              detailAppDEDataSetId: 'fetch_web_data_set',
              detailAppDataEntityId: 'web.ua_group_detail',
              enableScriptAppDEFieldId: 'enable_logic',
              iconClsAppDEFieldId: 'icon_cls',
              appDataEntityId: 'web.master',
              textAppDEFieldId: 'caption',
              tipsAppDEFieldId: 'tooltip',
              uiactionTagAppDEFieldId: 'action_tag',
              uniqueTag: 'master__web_dynamic_ex_ua',
              visibleScriptAppDEFieldId: 'visible_logic',
              name: 'web扩展界面行为组（动态）',
              id: 'web_dynamic_ex_ua',
            },
            showCaption: true,
            showIcon: true,
            id: 'u640401e',
          },
          {
            actionLevel: 100,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            caption: '打开主表格视图',
            detailType: 'DEUIACTION',
            uiactionId: 'open_main_gridview@master',
            showCaption: true,
            showIcon: true,
            id: 'ud2b4df4',
          },
        ],
        appDataEntityId: 'web.master',
        id: 'web成员为扩展界面行为组（动态）',
      },
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      dedataViewItems: [
        {
          dataItemName: 'dataitem',
          itemType: 'ACTIONITEM',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '打开弹窗',
                detailType: 'DEUIACTION',
                uiactionId: 'open_dialog@master',
                showCaption: true,
                showIcon: true,
                id: 'u6d34e27',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                detailType: 'DEUIACTIONGROUP',
                refUIActionGroup: {
                  dynamicMode: 1,
                  actionLevelAppDEFieldId: 'level',
                  buttonStyleAppDEFieldId: 'button_style',
                  clsAppDEFieldId: 'style',
                  detailAppDEDataSetId: 'fetch_web_data_set',
                  detailAppDataEntityId: 'web.ua_group_detail',
                  enableScriptAppDEFieldId: 'enable_logic',
                  iconClsAppDEFieldId: 'icon_cls',
                  appDataEntityId: 'web.master',
                  textAppDEFieldId: 'caption',
                  tipsAppDEFieldId: 'tooltip',
                  uiactionTagAppDEFieldId: 'action_tag',
                  uniqueTag: 'master__web_dynamic_ex_ua',
                  visibleScriptAppDEFieldId: 'visible_logic',
                  name: 'web扩展界面行为组（动态）',
                  id: 'web_dynamic_ex_ua',
                },
                showCaption: true,
                showIcon: true,
                id: 'u640401e',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '打开主表格视图',
                detailType: 'DEUIACTION',
                uiactionId: 'open_main_gridview@master',
                showCaption: true,
                showIcon: true,
                id: 'ud2b4df4',
              },
            ],
            appDataEntityId: 'web.master',
            id: 'web成员为扩展界面行为组（动态）',
          },
          id: 'dataitem',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      enableGroup: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_uiactiongroup_embed_data_view',
      controlType: 'DATAVIEW',
      logicName: '卡片_成员为动态界面行为组_卡片视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: 'a47b95c52ff84751e04f0d073552a2cb',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_uiactiongroup_embed_data_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_成员为动态界面行为组',
      codeName: 'card_dy_uiaction_group_embed_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_dy_uiaction_group_embed_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_成员为动态界面行为组',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '897e490b537030e5fe9648e1f6086510',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_dy_uiaction_group_embed',
  id: 'web.master_card_dy_uiaction_group_embed',
};
