export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'card_load_mode_exp',
  deviewId: 'E9D75D54-33D0-4554-B3F1-2CF654585437',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_加载模式导航视图',
  codeName: 'master_card_load_mode_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '分页加载',
          appViewId: 'web.master_card_paging_load',
          id: 'card_paging_load',
        },
        {
          caption: '加载更多',
          appViewId: 'web.master_card_load_more',
          id: 'card_load_more',
        },
        {
          caption: '滚动加载',
          appViewId: 'web.master_card_roll_load',
          id: 'card_roll_load',
        },
      ],
      dataRelationTag: 'DataRelation45',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_card_load_mode_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation45',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '360DE604-BF0D-489F-AECC-FDD1C6CD3EB0',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation45',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_加载模式导航视图',
      codeName: 'card_load_mode_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_load_mode_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_加载模式导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0d5132798d3c21cf0f5d2e6f3dee58b6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_load_mode_exp',
  id: 'web.master_card_load_mode_exp',
};
