export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'map',
  loadDefault: true,
  deviewCodeName: 'map_event',
  deviewId: '6d5b03a0997f75cf12cb593c74710d73',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '地图_事件',
  codeName: 'master_map_event',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      eventNames: 'onPointClick',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'map',
      scriptCode:
        "const tips = '地图散点点击事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips);",
      builtinLogic: true,
      name: 'onPointClick',
      id: 'onpointclick',
    },
    {
      eventNames: 'onAreaClick',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'map',
      scriptCode:
        "const tips = '地图区域点击事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips);",
      builtinLogic: true,
      name: 'onAreaClick',
      id: 'onareaclick',
    },
    {
      eventNames: 'onBackClick',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'map',
      scriptCode:
        "const tips = '地图返回事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips);",
      builtinLogic: true,
      name: 'onBackClick',
      id: 'onbackclick',
    },
    {
      eventNames: 'onDrillDown',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'map',
      scriptCode:
        "const tips = '地图下钻事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips);",
      builtinLogic: true,
      name: 'onDrillDown',
      id: 'ondrilldown',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'map_event',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      legendPos: 'RIGHT',
      mapStyle: 'USER',
      sysMapItems: [
        {
          customCond:
            "{'SRFNAVPARAM.n_parent_id_eq': context.srfareacode===100000?'86':`${context.srfareacode}`}",
          dataAppDEFieldId: 'level',
          idAppDEFieldId: 'id',
          itemStyle: 'REGION',
          itemType: 'area',
          latitudeAppDEFieldId: 'code',
          longitudeAppDEFieldId: 'code',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '区域',
          id: 'area',
        },
        {
          customCond:
            "{'SRFNAVPARAM.n_parent_id_eq': context.srfareacode===100000?'86':`${context.srfareacode}`}",
          idAppDEFieldId: 'id',
          itemStyle: 'POINT',
          itemType: 'point',
          latitudeAppDEFieldId: 'latitude',
          longitudeAppDEFieldId: 'longitude',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '点',
          id: 'point',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'map_event_map_view',
      controlType: 'MAP',
      height: 600,
      logicName: '地图_事件_地图部件',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'map',
      },
      modelId: '2ce0d83b1e6894ff966af29ff8348b17',
      modelType: 'PSSYSMAPVIEW',
      name: 'map',
      id: 'web.master.map_event_map_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '地图_事件',
      codeName: 'map_event_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'map_event_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMAPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '地图_事件',
  viewStyle: 'DEFAULT',
  viewType: 'DEMAPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '6e10436550302980fe818afce9252261',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERmap_event',
  id: 'web.master_map_event',
};
