export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'Tree_refreshmode_nocache',
  deviewId: 'aff0057dfd3368ccbfe8f0ae9f830342',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '无缓存模式示例',
  codeName: 'master_tree_refreshmode_nocache',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '主数据（node）-名称（node_1）',
        },
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-主数据（node）',
          id: '默认根节点（root）-主数据（node）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '主数据',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          expanded: true,
          name: '主数据',
          id: 'node',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node_1',
          appDataEntityId: 'web.master',
          treeNodeType: 'DE',
          name: '名称',
          id: 'node_1',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_refreshmode_nocache_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树视图_不缓存刷新模式_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          MDCTRLREFRESHMODE: 'nocache',
        },
        id: 'tree',
      },
      modelId: '1af3e079b9871a55a88a35b57d30a74a',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_refreshmode_nocache_tree_view',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'tree_refresh@master',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '刷新',
          itemType: 'DEUIACTION',
          tooltip: '刷新',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      xdataControlName: 'tree',
      codeName: 'tree_refreshmode_nocache_toolbar',
      controlType: 'TOOLBAR',
      logicName: '树视图_刷新模式',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'f94d28dd523c3ff021dbc9863590f55b',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'tree_refreshmode_nocache_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '无缓存模式示例',
      codeName: 'tree_refreshmode_nocache_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_refreshmode_nocache_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '无缓存模式示例',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '7e4270cfa85329d5b5128d207d3eae04',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_refreshmode_nocache',
  id: 'web.master_tree_refreshmode_nocache',
};
