export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'baseCalendarExpView',
  deviewId: 'FE636365-74C8-4F53-8E0D-5BAFD607784F',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历导航视图_基础',
  codeName: 'master_base_calendar_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'CalendarExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      sysImage: {
        cssClass: 'fa fa-cube',
        glyph: 'xf1b2@FontAwesome',
      },
      title: '日历导航',
      xdataControlName: 'calendarexpbar_calendar',
      enableCounter: true,
      enableSearch: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '导航栏导航编辑视图',
          refAppViewId: 'web.master_usr4409_edit_view',
          name: 'EXPITEM:master',
          id: 'expitem:master',
        },
      ],
      controls: [
        {
          calendarStyle: 'MONTH',
          groupMode: 'NONE',
          legendPos: 'NONE',
          sysCalendarItems: [
            {
              beginTimeAppDEFieldId: 'start_time',
              endTimeAppDEFieldId: 'end_time',
              idAppDEFieldId: 'id',
              itemStyle: 'DEFAULT',
              itemType: 'master',
              appDEDataSetId: 'fetch_default',
              textAppDEFieldId: 'name',
              appDataEntityId: 'web.master',
              navAppViewId: 'web.master_usr4409_edit_view',
              navigateParams: [
                {
                  key: 'name',
                  value: 'name',
                  id: 'name',
                },
              ],
              name: '主数据',
              id: 'master',
            },
          ],
          navViewPos: 'NONE',
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'base_calendar_exp_view_calendar',
          controlType: 'CALENDAR',
          logicName: '日历导航视图_基础_日历部件',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'calendarexpbar_calendar',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'calendarexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'calendarexpbar_calendar',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'calendarexpbar_load',
            },
          ],
          controlParam: {
            ctrlParams: {
              DEFAULTDATETIME: '2025-05-05',
            },
            id: 'calendarexpbar_calendar',
          },
          modelId: 'DA7981EA-2B40-4DDE-8571-C679EC1450C9',
          modelType: 'PSSYSCALENDAR',
          name: 'calendarexpbar_calendar',
          id: 'web.master.base_calendar_exp_view_calendar',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_refreshaction',
              valid: true,
              caption: '刷新',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-refresh',
                glyph: 'xf021@FontAwesome',
              },
              tooltip: '刷新',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
          ],
          codeName: 'base_calendar_exp_view_calendarexpbar_toolbar',
          controlType: 'TOOLBAR',
          logicName: '日历导航栏_基础_工具栏',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'calendarexpbar_toolbar',
          },
          modelId: 'C303FF21-7583-4CF6-B82B-2347DE31EC65',
          modelType: 'PSDETOOLBAR',
          name: 'calendarexpbar_toolbar',
          id: 'base_calendar_exp_view_calendarexpbar_toolbar',
        },
      ],
      codeName: 'base_calendar_exp_view_calendarexpbar',
      controlType: 'CALENDAREXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          DEFAULTDATETIME: '2025-05-05',
        },
        id: 'calendarexpbar',
      },
      width: 750,
      modelId: 'f7ef2fe1e8180f838a19ddde9f2115ff_calendarexpbar',
      modelType: 'PSEXPBAR',
      name: 'calendarexpbar',
      id: 'base_calendar_exp_view_calendarexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历导航视图_基础',
      codeName: 'base_calendar_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'base_calendar_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDAREXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历导航视图_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDAREXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f7ef2fe1e8180f838a19ddde9f2115ff',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERbaseCalendarExpView',
  id: 'web.master_base_calendar_exp_view',
};
