export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_event',
  deviewId: '83520ae6a0f86ba36c85c9b39e23a6ae',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '部件事件',
  codeName: 'master_list_event',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'card_event',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'region_id',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'category_type',
          dataType: 25,
          id: 'srfdatatype',
        },
        {
          appDEFieldId: 'category_type',
          dataType: 25,
          id: 'category_type',
        },
        {
          appDEFieldId: 'category_id',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'wf_status',
          frontCodeListId: 'web.wfstates',
          dataType: 25,
          id: 'wf_status',
        },
      ],
      pagingSize: 1000,
      hasWFDataItems: true,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_event',
      controlType: 'LIST',
      logicName: 'list_event',
      appDataEntityId: 'web.master',
      controlLogics: [
        {
          eventNames: 'onLoadSuccess',
          logicTag: 'list',
          logicType: 'SCRIPT',
          scriptCode:
            "console.log('列表数据加载成功事件触发，当前列表数据：', ctrl.state.items)",
          triggerType: 'CTRLEVENT',
          name: 'onLoadSuccess',
          id: 'onloadsuccess',
        },
        {
          eventNames: 'onSelectionChange',
          logicTag: 'list',
          logicType: 'SCRIPT',
          scriptCode:
            "console.log('选中数据变更事件触发，当前选中数据：', data)\r\nibiz.message.info(`选中数据变更事件触发`);",
          triggerType: 'CTRLEVENT',
          name: 'onSelectionChange',
          id: 'onselectionchange',
        },
      ],
      controlParam: {
        id: 'list',
      },
      modelId: '01ee2366a13eedbb2cb5e968f0ca1a02',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'web.master.list_event',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '部件事件',
      codeName: 'list_event_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'list_event_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表_部件事件',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6c1deca6f6434e8d8e563fa5d79ff50a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_event',
  id: 'web.master_list_event',
};
