export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendar_layout',
  deviewId: '871713d1ede5fd7c59914e00fc8a4f41',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_项布局',
  codeName: 'master_calendar_layout',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '天',
          appViewId: 'web.master_calendar_layout_day',
          id: 'day',
        },
        {
          caption: '周',
          appViewId: 'web.master_calendar_layout_week',
          id: 'week',
        },
        {
          caption: '月',
          appViewId: 'web.master_calendar_layout_month',
          id: 'month',
        },
        {
          caption: '时间轴',
          appViewId: 'web.master_calendar_layout_timeline',
          id: 'timeline',
        },
        {
          caption: '用户自定义',
          appViewId: 'web.master_calendar_layout_user',
          id: 'user',
        },
      ],
      dataRelationTag: 'calendar_layout_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar_layout__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_layout_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '1257a9c0958d8753cb38f92dc8020ef5',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'calendar_layout_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_项布局',
      codeName: 'calendar_layout_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_layout_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_项布局',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '91a5ace1e059866ba6f13d0970a20fd6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_layout',
  id: 'web.master_calendar_layout',
};
