export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'Pickup_editview2',
  deviewId: '736c4631d7dbd96bd4e6094a2b111f80',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '选择视图面板_编辑视图（左右关系）',
  codeName: 'master_pickup_editview2',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'pickup_editview2_toolbar',
      controlType: 'TOOLBAR',
      logicName: '选择视图面板_编辑视图（左右关系）_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'd576a7e38b8da88aabc71bd21a6cb452',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'pickup_editview2_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'web.master_pickup_gridpickupview2',
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'formitem3',
                editorParams: {
                  AC: 'FALSE',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKEREX_NOAC',
                editorItems: [
                  {
                    id: 'formitem3',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem',
              },
              allowEmpty: true,
              caption: '表格',
              codeName: 'formitem',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'formitem',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem3',
              },
              allowEmpty: true,
              hidden: true,
              codeName: 'formitem3',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'formitem3',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'web.master_pickup_cardpickupview2',
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'formitem4',
                editorParams: {
                  AC: 'FALSE',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKEREX_NOAC',
                editorItems: [
                  {
                    id: 'formitem4',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem1',
              },
              allowEmpty: true,
              caption: '卡片',
              codeName: 'formitem1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'formitem1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem4',
              },
              allowEmpty: true,
              hidden: true,
              codeName: 'formitem4',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'formitem4',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'web.master_pickup_treepickupview2',
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'formitem5',
                editorParams: {
                  AC: 'FALSE',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKEREX_NOAC',
                editorItems: [
                  {
                    id: 'formitem5',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem2',
              },
              allowEmpty: true,
              caption: '树',
              codeName: 'formitem2',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'formitem2',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem5',
              },
              allowEmpty: true,
              hidden: true,
              codeName: 'formitem5',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'formitem5',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main158',
      controlType: 'FORM',
      logicName: '选择视图面板_编辑视图（左右关系）_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'd9716eed1c44e27ce39e1058bea6f0a1',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main158',
    },
    {
      codeName: 'pickup_editview2_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'pickup_editview2_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '选择视图面板_编辑视图（左右关系）',
      codeName: 'pickup_editview2_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_editview2_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_编辑视图（左右关系）',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f8288ff37050438cf261e6426323ed35',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_editview2',
  id: 'web.master_pickup_editview2',
};
