export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'AnchorTabExpView',
  deviewId: '0b5a6ed03d5f3a542d6064c988441c4a',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '锚点分页导航',
  codeName: 'master_anchor_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup7',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '左侧锚点栏',
          appViewId: 'web.master_editform_anchor',
          id: 'left',
        },
        {
          caption: '右侧锚点栏',
          appViewId: 'web.master_right_anchor_edit_view',
          id: 'right',
        },
        {
          caption: '左上角锚点栏',
          appViewId: 'web.master_left_top_anchor_edit_view',
          id: 'left_top',
        },
        {
          caption: '右上角导航栏',
          appViewId: 'web.master_right_top_anchor_edit_view',
          id: 'right_top',
        },
      ],
      dataRelationTag: 'DataRelation23',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_anchor_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation23',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'e11f8b09c32aab93331619bae941911c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation23',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '锚点分页导航',
      codeName: 'anchor_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'anchor_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '锚点分页导航',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'dcf07f652890347d4f89d71f5e7045b0',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERAnchorTabExpView',
  id: 'web.master_anchor_tab_exp_view',
};
