export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'tree_counter_disabled',
  deviewId: '07d65c67068fcee21c45ad8c4c70a82c',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_计数器动态禁用',
  codeName: 'master_tree_counter_disabled',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onCreated',
      logicTrigger: 'VIEWEVENT',
      logicType: 'SCRIPT',
      scriptCode:
        "view.ctx.evt.on('onRegister', (name, ctrl) => {\r\n   if (name === 'tree') {\r\n      ctrl.disableCounter?.();\r\n      console.log('部件注册成功事件触发后，调用禁用部件计数器能力');\r\n   }\r\n})",
      builtinLogic: true,
      id: 'disable_counter',
    },
  ],
  appViewMsgGroupId: 'disable_counter',
  controls: [
    {
      appCounterRefId: 'c08c472f59332aa507b4952a6d4e5c5f',
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
        {
          childDETreeNodeId: 'node_3',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
        {
          childDETreeNodeId: 'node_2',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '节点1',
          counterId: 'tree',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          name: '节点1',
          id: 'node',
        },
        {
          text: '节点1-1',
          counterId: 'menu',
          nodeType: 'node_1',
          treeNodeType: 'STATIC',
          name: '节点1-1',
          id: 'node_1',
        },
        {
          text: '节点1-2',
          counterId: 'grid',
          nodeType: 'node_2',
          treeNodeType: 'STATIC',
          name: '节点1-2',
          id: 'node_2',
        },
        {
          text: '节点2',
          counterId: 'ui_action',
          nodeType: 'node_3',
          treeNodeType: 'STATIC',
          name: '节点2',
          id: 'node_3',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      appCounterRefs: [
        {
          appCounter: {
            codeName: 'Counter',
            counterType: 'DEDR',
            getAppDEActionId: 'get_counter_data',
            appDataEntityId: 'web.master',
            timer: 60000,
            uniqueTag: 'Counter',
            name: '计数器',
            id: 'web.counter',
          },
          tag: 'c08c472f59332aa507b4952a6d4e5c5f',
          uniqueTag: 'Counter',
          id: 'c08c472f59332aa507b4952a6d4e5c5f',
        },
      ],
      codeName: 'tree_count',
      controlType: 'TREEVIEW',
      logicName: '树视图_计数器',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: 'f39c056591b4dfdc1c41aa3eb40eaf45',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_count',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_计数器动态禁用',
      codeName: 'tree_counter_disabled_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_counter_disabled_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_计数器动态禁用',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2a33655e9fff2f711648693aa4fc7109',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtree_counter_disabled',
  id: 'web.master_tree_counter_disabled',
};
