export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'treegridex',
  loadDefault: true,
  deviewCodeName: 'TreeGridEx_rowedit',
  deviewId: '46f78b80d60c53785da8ff8b2e4f4b21',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树表格增强_单行编辑',
  codeName: 'master_tree_grid_ex_rowedit',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeGridExView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'treegridex_rowedit',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detreeColumns: [
        {
          align: 'CENTER',
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 250,
          widthUnit: 'px',
          id: 'name',
        },
        {
          align: 'CENTER',
          caption: '编号',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'code',
        },
        {
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'STAR',
          id: 'status',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          nodeValue: '86',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          updateAppDEActionId: 'update_mock_data',
          nodeType: 'node',
          appDataEntityId: 'web.region',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'code',
              appDEFieldId: 'code',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'code',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'code',
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'FRONT',
              dataItemName: 'status',
              appCodeListId: 'web.mock__cl_status',
              appDEFieldId: 'status',
              valueType: 'SIMPLE',
              enableRowEdit: true,
              codeName: 'status',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'status',
              id: 'status',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'code',
              detreeColumnId: 'code',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'FRONT',
              frontCodeListId: 'web.mock__cl_status',
              appDEFieldId: 'status',
              detreeColumnId: 'status',
              valueType: 'SIMPLE',
              dataType: 9,
              id: 'status',
            },
          ],
          detreeNodeEditItems: [
            {
              enableCond: 3,
              appDEFieldId: 'code',
              editor: {
                editorType: 'NUMBER',
                valueType: 'SIMPLE',
                editable: true,
                id: 'code',
              },
              allowEmpty: true,
              id: 'code',
            },
            {
              enableCond: 3,
              appDEFieldId: 'name',
              editor: {
                maxLength: 200,
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'name',
              },
              allowEmpty: true,
              id: 'name',
            },
            {
              enableCond: 3,
              appDEFieldId: 'status',
              editor: {
                singleSelect: true,
                appCodeListId: 'web.mock__cl_status',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'status',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              id: 'status',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '区划数据',
          id: 'node',
        },
      ],
      treeGridMode: 1,
      enableEdit: true,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_grid_ex_rowedit_tree_grid',
      controlType: 'TREEGRIDEX',
      logicName: '树表格增强_行编辑_树表格',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          EDITSHOWMODE: 'row',
        },
        id: 'treegridex',
      },
      modelId: '621fece0f4c2662d387399415933f23d',
      modelType: 'PSDETREEGRIDEX',
      name: 'treegridex',
      id: 'web.master.tree_grid_ex_rowedit_tree_grid',
    },
    {
      xdataControlName: 'treegridex',
      codeName: 'tree_grid_ex_rowedit_toolbar',
      controlType: 'TOOLBAR',
      logicName: '树表格增强_行编辑_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '8c16f54c4b8fd0701a97ebe46efdd78b',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'tree_grid_ex_rowedit_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树表格增强_单行编辑',
      codeName: 'tree_grid_ex_rowedit_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_grid_ex_rowedit_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEGRIDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格增强_单行编辑',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDEXVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '01897e14f0890691072cd4b616758b3a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTreeGridEx_rowedit',
  id: 'web.master_tree_grid_ex_rowedit',
};
