export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'grid_attachment_column',
  deviewId: '9f4a8881d5ed6b679b55665119633d02',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_附件列',
  codeName: 'master_grid_attachment_column',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '文件预览',
          appViewId: 'web.master_grid_attachment_column_file_preview',
          id: 'default',
        },
        {
          caption: 'OSS参数',
          appViewId: 'web.master_grid_attachment_column_osscat',
          id: 'osscat',
        },
        {
          caption: '下载启用鉴权',
          appViewId: 'web.master_grid_attachment_column_enabledownloadticket',
          id: 'enabledownloadticket',
        },
        {
          caption: '启用无权限',
          appViewId: 'web.master_grid_attachment_column_enablenoaccess',
          id: 'enablenoaccess',
        },
      ],
      dataRelationTag: 'grid_attachment_column_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_grid_attachment_column__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_attachment_column_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'ae40ff1d3dfde69cee6ec6884a540292',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'grid_attachment_column_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格_附件列',
      codeName: 'grid_attachment_column_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_attachment_column_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格_附件列',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '57e0cddbac5a155678e0c3ffbb0a62de',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_attachment_column',
  id: 'web.master_grid_attachment_column',
};
