export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'list_group_exp',
  deviewId: '19aaa9dbf0dd807f62cb06e321ee7945',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_分组导航视图',
  codeName: 'master_list_group_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '自动分组',
          appViewId: 'web.master_list_auto_group',
          id: 'auto_group',
        },
        {
          caption: '代码表分组',
          appViewId: 'web.master_list_codelist_group',
          id: 'codelist_group',
        },
        {
          caption: '分组界面行为',
          appViewId: 'web.master_list_group_action',
          id: 'group_action',
        },
        {
          caption: '分组样式2',
          appViewId: 'web.master_list_group_style2',
          id: 'group_style2',
        },
      ],
      dataRelationTag: 'DataRelation56',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_list_group_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation56',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '3c9aec6147ce90b1d9f0f7771ab614cc',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation56',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '列表_分组导航视图',
      codeName: 'list_group_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'list_group_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表_分组导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c7cc3be935c66339d74fe43b3cbbd62e',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_group_exp',
  id: 'web.master_list_group_exp',
};
