export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'view_logic',
  deviewId: 'f4421d5660bbe795f3bbfc4f4c413acd',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '视图逻辑',
  codeName: 'master_view_logic',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '视图事件触发',
          appViewId: 'web.master_view_event_trigger',
          id: 'view_event',
        },
        {
          caption: '部件事件触发',
          appViewId: 'web.master_ctrl_event_trigger',
          id: 'ctrl_event',
        },
        {
          caption: '定时器触发',
          appViewId: 'web.master_timer_trigger',
          id: 'timer',
        },
        {
          caption: '调用视图能力',
          appViewId: 'web.master_call_view_ability',
          id: 'view_ability',
        },
      ],
      dataRelationTag: 'view_logic_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_view_logic__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'view_logic_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'bb1fc1943b92facb528c8e2db76b2070',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'view_logic_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '视图逻辑',
      codeName: 'view_logic_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'view_logic_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '视图逻辑',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e0bd388804ec01e9e5fb2fc9cc74ca6e',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERview_logic',
  id: 'web.master_view_logic',
};
