export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'Tree_refreshmode',
  deviewId: 'd2975a540a92be961af88a9dd09cbbd6',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_刷新模式',
  codeName: 'master_tree_refreshmode',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tree_refreshmode',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '缓存模式',
          appViewId: 'web.master_tree_refreshmode_cache',
          name: 'Tree_cache',
          id: 'tree_cache',
        },
        {
          caption: '无缓存模式',
          appViewId: 'web.master_tree_refreshmode_nocache',
          name: 'Tree_nocache',
          id: 'tree_nocache',
        },
      ],
      dataRelationTag: 'DataRelation76',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tree_refreshmode__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation76',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'ee1d10831b82c8a42522bb1c1922c218',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation76',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_刷新模式',
      codeName: 'tree_refreshmode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_refreshmode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_刷新模式',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '01a6e0a78bdb738a0f2f37d131a5ba83',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_refreshmode',
  id: 'web.master_tree_refreshmode',
};
