export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'card_showmode_exp',
  deviewId: '80d8334b74b4af7e26ed9e9963f8350d',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_显示模式导航视图',
  codeName: 'master_card_showmode_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup10',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '默认显示模式',
          appViewId: 'web.master_card_default_showmode',
          id: 'default',
        },
        {
          caption: '仅显示数据模式',
          appViewId: 'web.master_card_onlydata_showmode',
          id: 'onlydata',
        },
        {
          caption: '无数据显示模式',
          appViewId: 'web.master_card_mixin_showmode',
          id: 'mixin',
        },
      ],
      dataRelationTag: 'DataRelation49',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_card_showmode_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation49',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '87087d85b432385bc0f02074627cb9ba',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation49',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_显示模式导航视图',
      codeName: 'card_showmode_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_showmode_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_显示模式导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '393a5707b8479b24631acbdd8f643cfa',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_showmode_exp',
  id: 'web.master_card_showmode_exp',
};
