export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'MonthNavParamCalendarExpView',
  deviewId: '5903F5F1-8CC2-4542-AB13-22718DAF01E2',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历导航栏_导航参数_月',
  codeName: 'master_month_nav_param_calendar_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'CalendarExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      xdataControlName: 'calendarexpbar_calendar',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '导航栏导航编辑视图',
          refAppViewId: 'web.master_usr4409_edit_view',
          name: 'EXPITEM:master',
          id: 'expitem:master',
        },
      ],
      controls: [
        {
          calendarStyle: 'MONTH',
          groupMode: 'NONE',
          legendPos: 'NONE',
          sysCalendarItems: [
            {
              beginTimeAppDEFieldId: 'start_time',
              endTimeAppDEFieldId: 'end_time',
              idAppDEFieldId: 'id',
              itemStyle: 'DEFAULT',
              itemType: 'master',
              appDEDataSetId: 'fetch_default',
              textAppDEFieldId: 'name',
              appDataEntityId: 'web.master',
              navAppViewId: 'web.master_usr4409_edit_view',
              navigateParams: [
                {
                  key: 'name',
                  value: 'name',
                  id: 'name',
                },
              ],
              name: '主数据',
              id: 'master',
            },
          ],
          navViewPos: 'NONE',
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'month_nav_param_calendar_exp_view_calendar',
          controlType: 'CALENDAR',
          logicName: '日历导航栏_导航参数_月_日历部件',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'calendarexpbar_calendar',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'calendarexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'calendarexpbar_calendar',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'calendarexpbar_load',
            },
          ],
          controlParam: {
            ctrlParams: {
              DEFAULTDATETIME: '2025-05-05',
            },
            id: 'calendarexpbar_calendar',
          },
          modelId: 'E93D1237-D56D-4A23-A2DA-B73E56F1D5F4',
          modelType: 'PSSYSCALENDAR',
          name: 'calendarexpbar_calendar',
          id: 'web.master.month_nav_param_calendar_exp_view_calendar',
        },
      ],
      codeName: 'month_nav_param_calendar_exp_view_calendarexpbar',
      controlType: 'CALENDAREXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          DEFAULTDATETIME: '2025-05-05',
        },
        id: 'calendarexpbar',
      },
      width: 750,
      modelId: 'e28eef62f4a9dcb974c6416a3c57b771_calendarexpbar',
      modelType: 'PSEXPBAR',
      name: 'calendarexpbar',
      id: 'month_nav_param_calendar_exp_view_calendarexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历导航栏_导航参数_月',
      codeName: 'month_nav_param_calendar_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'month_nav_param_calendar_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDAREXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历导航栏_导航参数_月',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDAREXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e28eef62f4a9dcb974c6416a3c57b771',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERMonthNavParamCalendarExpView',
  id: 'web.master_month_nav_param_calendar_exp_view',
};
