export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'treegridex',
  loadDefault: true,
  deviewCodeName: 'treegridex_column_expand_icon',
  deviewId: '4603e1d5e977103f74e8629985ecf7f7',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树表格增强_指定展开图标列',
  codeName: 'master_treegridex_column_expand_icon',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeGridExView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup65',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detreeColumns: [
        {
          align: 'CENTER',
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 300,
          widthUnit: 'px',
          id: 'name',
        },
        {
          align: 'CENTER',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          width: 300,
          widthUnit: 'px',
          id: 'code',
        },
        {
          align: 'CENTER',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'STAR',
          id: 'status',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '区域数据（node）-区域数据（node）',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-区域数据（node）',
          id: '默认根节点（root）-区域数据（node）',
        },
      ],
      detreeNodes: [
        {
          nodeValue: '86',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.region',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'code',
              appDEFieldId: 'code',
              valueType: 'SIMPLE',
              codeName: 'code',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'code',
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'FRONT',
              dataItemName: 'status',
              appCodeListId: 'web.mock__cl_status',
              appDEFieldId: 'status',
              valueType: 'SIMPLE',
              codeName: 'status',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'status',
              id: 'status',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'code',
              detreeColumnId: 'code',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'status',
              detreeColumnId: 'status',
              valueType: 'SIMPLE',
              dataType: 9,
              id: 'status',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '区域数据',
          id: 'node',
        },
      ],
      treeGridMode: 1,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'treegridex_column_expand_icon',
      controlType: 'TREEGRIDEX',
      logicName: '树表格增强_指定展开图标列',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          EXPANDICONCOLUMN: 'code',
        },
        id: 'treegridex',
      },
      modelId: '7b223714a50cf24aab273363795e333e',
      modelType: 'PSDETREEGRIDEX',
      name: 'treegridex',
      id: 'web.master.treegridex_column_expand_icon',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树表格增强_指定展开图标列',
      codeName: 'treegridex_column_expand_icon_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'treegridex_column_expand_icon_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEGRIDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格增强_指定展开图标列',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDEXVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '48b1a8bd12f96d722199886cb9f8c12c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreegridex_column_expand_icon',
  id: 'web.master_treegridex_column_expand_icon',
};
