export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'Tree_hasvaluesearch',
  deviewId: 'b19acafa787572e4534cbb290d1b36b0',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_有搜索时启用搜索模式',
  codeName: 'master_tree_hasvaluesearch',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'tree_hasvaluesearch',
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node1_1',
          parentDETreeNodeId: 'node1',
          parentValueLevel: 1,
          searchMode: 1,
          id: '父节点（node）-子节点1（node_1）',
        },
        {
          childDETreeNodeId: 'node1',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-父节点（node）',
          id: '默认根节点（root）-父节点（node）',
        },
        {
          childDETreeNodeId: 'node1_2',
          parentDETreeNodeId: 'node1',
          parentValueLevel: 1,
          searchMode: 3,
          id: '父节点（node）-子节点2（node_2）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          enableQuickSearch: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '静态节点1',
          nodeType: 'node1',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          enableQuickSearch: true,
          expanded: true,
          name: '静态节点1',
          id: 'node1',
        },
        {
          text: '有搜索时启用静态节点1-1',
          nodeType: 'node1_1',
          treeNodeType: 'STATIC',
          enableQuickSearch: true,
          name: '有搜索时启用静态节点1-1',
          id: 'node1_1',
        },
        {
          text: '静态节点1-2',
          nodeType: 'node1_2',
          treeNodeType: 'STATIC',
          enableQuickSearch: true,
          name: '静态节点1-2',
          id: 'node1_2',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_hasvaluesearch_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树_搜索时启用搜索模式_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: 'ce32ff8cd70b84540405e72373db7fba',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_hasvaluesearch_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_有搜索时启用搜索模式',
      codeName: 'tree_hasvaluesearch_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_hasvaluesearch_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_有搜索时启用搜索模式',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '679d201665233d5867f7070d092c4af0',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_hasvaluesearch',
  id: 'web.master_tree_hasvaluesearch',
};
