export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'Pickup_muleditview',
  deviewId: 'b0a60ba66ec3981010462732eeb79c8c',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '选择视图面板_多选编辑视图',
  codeName: 'master_pickup_muleditview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'pickup_muleditview_toolbar',
      controlType: 'TOOLBAR',
      logicName: '选择视图面板_多选编辑视图_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '7d487df809c777775927ef8d4be79d14',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'pickup_muleditview_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                enablePickupView: true,
                pickupAppViewId: 'web.master_pickup_gridmpickupview',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'web.master',
                forceSelection: true,
                showTrigger: true,
                editorParams: {
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'ADDRESSPICKUP',
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem',
              },
              allowEmpty: true,
              caption: '表格',
              codeName: 'formitem',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'formitem',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                enablePickupView: true,
                pickupAppViewId: 'web.master_pickup_cardmpickupview',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'web.master',
                forceSelection: true,
                showTrigger: true,
                editorParams: {
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'ADDRESSPICKUP',
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem1',
              },
              allowEmpty: true,
              caption: '卡片',
              codeName: 'formitem1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'formitem1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                enablePickupView: true,
                pickupAppViewId: 'web.master_pickup_treempickupview',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'web.master',
                forceSelection: true,
                showTrigger: true,
                editorParams: {
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'ADDRESSPICKUP',
                valueType: 'SIMPLE',
                editable: true,
                id: 'formitem2',
              },
              allowEmpty: true,
              caption: '树',
              codeName: 'formitem2',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'formitem2',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main159',
      controlType: 'FORM',
      logicName: '选择视图面板_多选编辑视图_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '0902c334cc5634281c6c6f5746c433e7',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main159',
    },
    {
      codeName: 'pickup_muleditview_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'pickup_muleditview_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '选择视图面板_多选编辑视图',
      codeName: 'pickup_muleditview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_muleditview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_多选编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ccf1145b7f4ba812363b2ed80c96ed51',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_muleditview',
  id: 'web.master_pickup_muleditview',
};
