export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'map',
  loadDefault: true,
  deviewCodeName: 'map_custom_cond',
  deviewId: 'bd5e58327b6f2bf2d461b5d9f2cb60b1',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '地图_自定义条件',
  codeName: 'master_map_custom_cond',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'map_cond',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      legendPos: 'RIGHT',
      mapStyle: 'USER',
      sysMapItems: [
        {
          customCond:
            "{'SRFNAVPARAM.n_parent_id_eq': context.srfareacode===100000?'86':`${context.srfareacode}`,'SRFNAVPARAM.srfareacode': '%srfareacode%'}",
          dataAppDEFieldId: 'level',
          idAppDEFieldId: 'id',
          itemStyle: 'REGION',
          itemType: 'area',
          latitudeAppDEFieldId: 'code',
          longitudeAppDEFieldId: 'code',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '区域',
          id: 'area',
        },
        {
          customCond:
            "{'SRFNAVPARAM.n_parent_id_eq': context.srfareacode===100000?'86':`${context.srfareacode}`,'SRFNAVPARAM.srfareacode': '%srfareacode%'}",
          idAppDEFieldId: 'id',
          itemStyle: 'POINT',
          itemType: 'point',
          latitudeAppDEFieldId: 'latitude',
          longitudeAppDEFieldId: 'longitude',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '点',
          id: 'point',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'map_custom_cond_map_view',
      controlType: 'MAP',
      height: 600,
      logicName: '地图_自定义条件_地图部件',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'map',
      },
      modelId: '8b7bd5eb0b1e0a48e2a1e73453103734',
      modelType: 'PSSYSMAPVIEW',
      name: 'map',
      id: 'web.master.map_custom_cond_map_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '地图_自定义条件',
      codeName: 'map_custom_cond_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'map_custom_cond_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMAPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '地图_自定义条件',
  viewStyle: 'DEFAULT',
  viewType: 'DEMAPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '223731041f597f6540930f7c3f606a8f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERmap_custom_cond',
  id: 'web.master_map_custom_cond',
};
