export default {
  deviewCodeName: 'panel_panel_ctrl_pos',
  deviewId: 'ec5234284c358d8436153b38046f2ed3',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '面板_面板部件占位',
  codeName: 'master_panel_panel_ctrl_pos',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        caption: '表格',
        itemStyle: 'DEFAULT',
        itemType: 'CTRLPOS',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'grid',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        orderValueAppDEFieldId: 'px',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MASTER.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'region_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'region_id',
          },
          {
            appDEFieldId: 'category_type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdatatype',
          },
          {
            appDEFieldId: 'category_type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'category_type',
          },
          {
            appDEFieldId: 'category_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'category_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'wf_status',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'wf_status',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        hasWFDataItems: true,
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.master',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main86',
        controlType: 'GRID',
        logicName: '面板_面板部件占位_表格',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'grid',
        },
        modelId: 'cbd264f23941b228757f78aa6e129381',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.master.main86',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '面板_面板部件占位',
        codeName: 'panel_panel_ctrl_pos_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'panel_panel_ctrl_pos_captionbar',
      },
    ],
    codeName: 'a4118dd950a7e67c5eb',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'panel_panel_ctrl_pos',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '0c849368481ad216f237e29836ee97f8',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a4118dd950a7e67c5eb',
  },
  title: '面板_面板部件占位',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1416c99e2b447da5efe16bb63e109914',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERpanel_panel_ctrl_pos',
  id: 'web.master_panel_panel_ctrl_pos',
};
