export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'ui_action_next',
  deviewId: '569a8dbfcc0e5482769bccbd88fd6a93',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '后续界面行为',
  codeName: 'master_ui_action_next',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'ui_action_next',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MASTER.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'type',
          excelCaption: '类型',
          appCodeListId: 'web.mock__cl_categories',
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类型',
          codeName: 'type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'description',
          excelCaption: '描述',
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '描述',
          codeName: 'description',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'description',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'create_time',
          excelCaption: '创建时间',
          appDEFieldId: 'create_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MASTER.CREATE_TIME',
          },
          caption: '创建时间',
          codeName: 'create_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'create_time',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type',
        },
        {
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'description',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'create_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'create_time',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'region_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'category_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdatatype',
        },
        {
          appDEFieldId: 'category_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_type',
        },
        {
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'wf_status',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'wf_status',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      hasWFDataItems: true,
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'grid',
      },
      modelId: '85200473bedfecd4cc3a1c3c7e98fb8a',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.master.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main170',
      controlType: 'SEARCHFORM',
      logicName: '界面行为_后续界面行为_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'd91bb821981b51560b1485ae483ca953',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.main170',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'ui_action_next@master',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '后续界面行为（前台）',
          itemType: 'DEUIACTION',
          tooltip: '后续界面行为（前台）',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'ui_action_next_backend@master',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '后续界面行为（后台）',
          itemType: 'DEUIACTION',
          tooltip: '后续界面行为（后台）',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'ui_action_next_toolbar',
      controlType: 'TOOLBAR',
      logicName: '界面行为_后续界面行为_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '215ac48feba5fd9e4c5b2761a5674729',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'ui_action_next_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '后续界面行为',
      codeName: 'ui_action_next_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'ui_action_next_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '界面行为_后续界面行为',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c01a65f6dc6a33e29b9047d40941a16e',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERui_action_next',
  id: 'web.master_ui_action_next',
};
