export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'editformHoverTabExpView',
  deviewId: '4dc8f557df2deb0f83f595d27ff10be0',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑模式',
  codeName: 'master_editform_hover_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'edit_hover_mode',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '默认',
          appViewId: 'web.master_usr1225_edit_view',
          id: 'base',
        },
        {
          caption: '无值显示直接内容占位',
          appViewId: 'web.master_form_hover',
          id: 'default',
        },
        {
          caption: '无值显示空白占位文本',
          appViewId: 'web.master_hovershowplaceholder',
          id: 'placeholder',
        },
      ],
      dataRelationTag: 'DataRelation21',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_editform_hover_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation21',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'ece9cee9f6ccc8db57b2f55ed9319f99',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation21',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑模式',
      codeName: 'editform_hover_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editform_hover_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑模式',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '996c80b5ec6ba9dca64e122933e29079',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditformHoverTabExpView',
  id: 'web.master_editform_hover_tab_exp_view',
};
