export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tabexppanel_top',
  deviewId: 'eead3da98ddc6dfa496984f7b8f37027',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '分页导航面板_上方',
  codeName: 'master_tabexppanel_top',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      tabExpPageIds: ['region', 'category', 'master'],
      tabLayout: 'TOP',
      uniqueTag: 'master_tabexppanel_top__tabexppanel',
      appViewRefs: [
        {
          realTitle: '区划表格视图',
          refAppViewId: 'web.region_grid_view',
          name: 'EXPITEM:region',
          id: 'expitem:region',
        },
        {
          realTitle: '分类表格视图',
          refAppViewId: 'web.category_grid_view',
          name: 'EXPITEM:category',
          id: 'expitem:category',
        },
        {
          realTitle: '主数据表格视图',
          refAppViewId: 'web.master_main_grid',
          name: 'EXPITEM:master',
          id: 'expitem:master',
        },
      ],
      controls: [
        {
          caption: '区划',
          embeddedAppDEViewId: 'web.region_grid_view',
          codeName: 'tabexppanel_top_region',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'region',
          },
          modelId: '62c7be5e26cf4edcf34f990b4613bc2f_region',
          modelType: 'PSVIEWPANEL',
          name: 'region',
          id: 'tabexppanel_top_region',
        },
        {
          caption: '分类',
          embeddedAppDEViewId: 'web.category_grid_view',
          codeName: 'tabexppanel_top_category',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'category',
          },
          modelId: '62c7be5e26cf4edcf34f990b4613bc2f_category',
          modelType: 'PSVIEWPANEL',
          name: 'category',
          id: 'tabexppanel_top_category',
        },
        {
          caption: '主数据',
          embeddedAppDEViewId: 'web.master_main_grid',
          codeName: 'tabexppanel_top_master',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'master',
          },
          modelId: '62c7be5e26cf4edcf34f990b4613bc2f_master',
          modelType: 'PSVIEWPANEL',
          name: 'master',
          id: 'tabexppanel_top_master',
        },
      ],
      codeName: 'tabexppanel_top_tabexppanel',
      controlType: 'TABEXPPANEL',
      appDataEntityId: 'web.master',
      controlParam: {},
      modelId: '62c7be5e26cf4edcf34f990b4613bc2f_tabexppanel',
      modelType: 'PSTABEXPPANEL',
      name: 'tabexppanel',
      id: 'tabexppanel_top_tabexppanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '分页导航面板_上方',
      codeName: 'tabexppanel_top_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tabexppanel_top_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '分页导航面板_上方',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '62c7be5e26cf4edcf34f990b4613bc2f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtabexppanel_top',
  id: 'web.master_tabexppanel_top',
};
