export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'editor_dropdown_list',
  deviewId: 'd0cf1df8302d06b84c1c251c1056c42f',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_下拉列表框',
  codeName: 'master_editor_dropdown_list',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'editor_dropdown_list',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'editor_dropdown_list_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_下拉列表框_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '1bd3a493f6e2fef9c8fe3edb465fd675',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editor_dropdown_list_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformItemUpdates: [
        {
          codeName: 'fill_value6',
          defiupdateDetails: [
            {
              id: 'value6',
            },
          ],
          scriptCode:
            "return {value6: data.formitem4 != null ? data.formitem4: ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value6',
        },
        {
          codeName: 'fill_value2',
          defiupdateDetails: [
            {
              id: 'value2',
            },
          ],
          scriptCode:
            "return {value2: data.formitem2 != null ? data.formitem2 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value2',
        },
        {
          codeName: 'fill_value11',
          defiupdateDetails: [
            {
              id: 'value11',
            },
          ],
          scriptCode:
            "return {value11: data.formitem10 != null ? data.formitem10 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value11',
        },
        {
          codeName: 'fill_value13',
          defiupdateDetails: [
            {
              id: 'value13',
            },
          ],
          scriptCode:
            "return {value13: data.formitem21 != null ?JSON.stringify(data.formitem21) : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value13',
        },
        {
          codeName: 'fill_value5',
          defiupdateDetails: [
            {
              id: 'value5',
            },
          ],
          scriptCode:
            "return {value5: data.formitem != null ? data.formitem : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value5',
        },
        {
          codeName: 'fill_value',
          defiupdateDetails: [
            {
              id: 'value',
            },
          ],
          scriptCode:
            "return {value: data.formitem1 != null ? data.formitem1 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value',
        },
        {
          codeName: 'fill_value12',
          defiupdateDetails: [
            {
              id: 'value12',
            },
          ],
          scriptCode:
            "return {value12: data.formitem11 != null ? data.formitem11 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value12',
        },
        {
          codeName: 'fill_value3',
          defiupdateDetails: [
            {
              id: 'value3',
            },
          ],
          scriptCode:
            "return {value3: data.formitem3 != null ? data.formitem3 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value3',
        },
        {
          codeName: 'fill_value9',
          defiupdateDetails: [
            {
              id: 'value9',
            },
          ],
          scriptCode:
            "return {value9: data.formitem8 != null ? data.formitem8 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value9',
        },
        {
          codeName: 'fill_value4',
          defiupdateDetails: [
            {
              id: 'value4',
            },
          ],
          scriptCode:
            "return {value4: data.formitem7 != null ? data.formitem7 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value4',
        },
        {
          codeName: 'fill_value10',
          defiupdateDetails: [
            {
              id: 'value10',
            },
          ],
          scriptCode:
            "return {value10: data.formitem9 != null ? data.formitem9 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value10',
        },
        {
          codeName: 'fill_value7',
          defiupdateDetails: [
            {
              id: 'value7',
            },
          ],
          scriptCode:
            "return {value7: data.formitem5 != null ? data.formitem5 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value7',
        },
        {
          codeName: 'fill_value8',
          defiupdateDetails: [
            {
              id: 'value8',
            },
          ],
          scriptCode:
            "return {value8: data.formitem6 != null ? data.formitem6 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value8',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  outputCodeListConfigMode: 1,
                  deformItemUpdateId: 'fill_value',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.codelist85',
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  needCodeListConfig: true,
                  caption: '下拉列表框',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value',
                },
              ],
              caption: '下拉列表框',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  itemWidth: 100,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  outputCodeListConfigMode: 1,
                  deformItemUpdateId: 'fill_value2',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.codelist46',
                    editorType: 'DROPDOWNLIST_100',
                    editorWidth: 100,
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  needCodeListConfig: true,
                  caption: '下拉列表框（100宽度）',
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value2',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value2',
                },
              ],
              caption: '下拉列表框（100宽度）',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  outputCodeListConfigMode: 1,
                  deformItemUpdateId: 'fill_value3',
                  editor: {
                    appCodeListId: 'web.codelist46',
                    editorType: 'MDROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  needCodeListConfig: true,
                  caption: '下拉列表框（多选）',
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value3',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value3',
                },
              ],
              caption: '下拉列表框（多选）',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value4',
                  editor: {
                    appCodeListId: 'web.mock__cl_region',
                    editorType: 'MDROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '树选择',
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem7',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value4',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value4',
                },
              ],
              caption: '树选择',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value5',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.codelist85',
                    editorParams: {
                      forceselection: 'false',
                    },
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value5',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value5',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用forceselection参数控制下拉列表框是否禁止创建并选中未包含在初始选项中的条目。当前下拉列表框可以创建并选中未包含在初始选项中的条目',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: '创建新的选项',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value6',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__cl_region',
                    editorParams: {
                      defaultfirstoption: 'true',
                    },
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value6',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value6',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用defaultfirstoption参数控制下拉列表框是否在输入框按下回车时选择第一个匹配项。当前下拉列表框在输入框按下回车时会选择第一个匹配项',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
              ],
              caption: '回车选中第一个选项',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value7',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.codelist85',
                    editorParams: {
                      blankitemname: '空白项',
                    },
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value7',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value7',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用blankitemname参数控制下拉列表框是否在下拉数据顶部添加一条空白项数据。当前下拉列表框会在下拉数据顶部添加一条空白项数据，空白项数据的文本为空白项',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
              ],
              caption: '空白项数据',
              codeName: 'grouppanel7',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel7',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value8',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__codelist3',
                    editorParams: {
                      alwaysload: 'true',
                    },
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem6',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value8',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value8',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用alwaysload参数控制下拉列表框在值改变和下拉框出现时，是否重新加载代码表数据。当前下拉列表框在值改变和下拉框出现时。会重新加载代码表数据',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem4',
                  },
                  codeName: 'rawitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem4',
                },
              ],
              caption: '下拉数据加载模式',
              codeName: 'grouppanel8',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel8',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value9',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__codelist',
                    editorParams: {
                      type: 'round',
                    },
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem8',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem8',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value9',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value9',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用type参数控制下拉列表框下拉选项的呈现模式。当前下拉列表框下拉选项会以圆角按钮的形式呈现',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem6',
                  },
                  codeName: 'rawitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem6',
                },
              ],
              caption: '圆角按钮下拉列表框',
              codeName: 'grouppanel9',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel9',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 200,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value10',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.mock__codelist2',
                    editorParams: {
                      overflowmode: 'ellipsis',
                    },
                    editorType: 'DROPDOWNLIST',
                    editorWidth: 200,
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem9',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem9',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value10',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value10',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用overflowmode参数控制下拉列表框下拉区域的宽度显示方式，可选值有auto和ellipsis。当参数为auto时，下拉区域宽度会根据内容自动展开；当参数为ellipsis时，下拉区域宽度将与输入框保持一致，若内容超出宽度则会显示省略号，鼠标悬浮在内容上时会出现提示信息。当前下拉列表框的overflowmode参数值为ellipsis',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem5',
                  },
                  codeName: 'rawitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem5',
                },
              ],
              caption: '宽度模式',
              codeName: 'grouppanel10',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel10',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value11',
                  editor: {
                    appCodeListId: 'web.codelist85',
                    allItems: true,
                    editorParams: {
                      itemstext: '选择全部',
                      allitems: 'true',
                    },
                    editorType: 'MDROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem10',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem10',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value11',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value11',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value11',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用allitems参数控制下拉列表框是否显示全部项，使用itemstext参数指定全部项的文本。当前下拉列表框已显示全部项，全部项的文本为选择全部',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem7',
                  },
                  codeName: 'rawitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem7',
                },
              ],
              caption: '全部项',
              codeName: 'grouppanel11',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel11',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value12',
                  editor: {
                    appCodeListId: 'web.codelist46',
                    editorParams: {
                      valueseparator: ';',
                    },
                    editorType: 'MDROPDOWNLIST',
                    placeHolder: '请选择',
                    valueSeparator: ';',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem11',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '下拉列表框',
                  codeName: 'formitem11',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem11',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value12',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value12',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value12',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用valueseparator参数指定下拉列表框的值分隔符。当前下拉列表框的值分隔符为;',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem8',
                  },
                  codeName: 'rawitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem8',
                },
              ],
              caption: '值分隔符',
              codeName: 'grouppanel12',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel12',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value13',
                  editor: {
                    appCodeListId: 'web.codelist46',
                    editorParams: {
                      valuetype: 'SIMPLES',
                    },
                    editorType: 'MDROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLES',
                    editable: true,
                    id: 'formitem21',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem21',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem21',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value13',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value13',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value13',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用valuetype指定编辑器的值类型。当前编辑器的值类型为SIMPLES',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem9',
                  },
                  codeName: 'rawitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem9',
                },
              ],
              caption: '值类型为SIMPLES',
              codeName: 'grouppanel13',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel13',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '6',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.codelist46',
                    editorParams: {
                      readonly: 'true',
                    },
                    editorType: 'DROPDOWNLIST',
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem23',
                  },
                  updateDV: '6',
                  allowEmpty: true,
                  needCodeListConfig: true,
                  codeName: 'formitem23',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem23',
                },
                {
                  createDV: '6',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value14',
                  },
                  updateDV: '6',
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value14',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value14',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用readonly参数控制编辑器是否为只读态。当前编辑器为只读态',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem10',
                  },
                  codeName: 'rawitem10',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem10',
                },
              ],
              caption: '只读态',
              codeName: 'grouppanel14',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel14',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '下拉列表框',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'editor_dropdown_list_form',
      controlType: 'FORM',
      logicName: '编辑器_下拉列表框_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'cde1edf298fd56704810b23b1479553d',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.editor_dropdown_list_form',
    },
    {
      codeName: 'editor_dropdown_list_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editor_dropdown_list_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_下拉列表框',
      codeName: 'editor_dropdown_list_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editor_dropdown_list_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_下拉列表框',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '158eb47e622ba6d44c3ad73d2a2b685e',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditor_dropdown_list',
  id: 'web.master_editor_dropdown_list',
};
