export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'gantt',
  loadDefault: true,
  deviewCodeName: 'gantt_layout',
  deviewId: '22d23e74580213c5f6b936119379f954',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '甘特图_项布局面板',
  codeName: 'master_gantt_layout',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'gantt_layout',
  controls: [
    {
      beginDataItemName: 'begin',
      endDataItemName: 'end',
      finishDataItemName: 'finish',
      prevDataItemName: 'prev',
      sndataItemName: 'sn',
      totalDataItemName: 'total',
      detreeColumns: [
        {
          caption: '编号',
          codeName: 'sn',
          columnType: 'DEFGRIDCOLUMN',
          width: 120,
          widthUnit: 'px',
          id: 'sn',
        },
        {
          caption: '标题',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'name',
        },
        {
          caption: '开始时间',
          codeName: 'begin',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'begin',
        },
        {
          caption: '结束时间',
          codeName: 'end',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'end',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.master',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_time',
              appDEFieldId: 'end_time',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              codeName: 'end_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'id',
              appDEFieldId: 'id',
              valueType: 'SIMPLE',
              codeName: 'id',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'sn',
              id: 'id',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_time',
              appDEFieldId: 'start_time',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              codeName: 'start_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_time',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_time',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              format: 'YYYY-MM-DD',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'id',
              detreeColumnId: 'sn',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'id',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_time',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              format: 'YYYY-MM-DD',
              id: 'start_time',
            },
          ],
          treeNodeType: 'DE',
          controlRenders: [
            {
              layoutPanel: {
                layoutMode: 'TABLE_24COL',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                rootPanelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            viewFieldName: 'NAME',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'name',
                          },
                          {
                            rawItem: {
                              sysImage: {
                                cssClass: 'fa fa-tags',
                                glyph: 'xf02c@FontAwesome',
                              },
                              contentType: 'IMAGE',
                              predefinedType: 'STATIC_IMAGE',
                              id: 'static_image',
                            },
                            caption: '图片',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERSMALL',
                            },
                            sysImage: {
                              cssClass: 'fa fa-tags',
                              glyph: 'xf02c@FontAwesome',
                            },
                            showCaption: true,
                            id: 'static_image',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingBottom: 'OUTERMEDIUM',
                        },
                        id: 'container1',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  caption: '创建人',
                                  halign: 'LEFT',
                                  renderMode: 'TEXT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  contentType: 'RAW',
                                  predefinedType: 'STATIC_TEXT',
                                  id: 'static_text',
                                },
                                caption: '文本',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'static_text',
                              },
                              {
                                editor: {
                                  halign: 'LEFT',
                                  renderMode: 'TEXT_DYNAMIC',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId: 'web.sysoperator',
                                  editorType: 'SPAN',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'create_man',
                                },
                                viewFieldName: 'CREATE_MAN',
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '文本(动态)',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'create_man',
                              },
                            ],
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '面板容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              grow: 4,
                              shrink: 1,
                              layout: 'SIMPLEFLEX',
                            },
                            id: 'container2',
                          },
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  caption: '开始时间',
                                  halign: 'LEFT',
                                  renderMode: 'TEXT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  contentType: 'RAW',
                                  predefinedType: 'STATIC_TEXT',
                                  id: 'static_text1',
                                },
                                caption: '文本',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'static_text1',
                              },
                              {
                                editor: {
                                  halign: 'LEFT',
                                  renderMode: 'TEXT_DYNAMIC',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'start_time',
                                },
                                viewFieldName: 'START_TIME',
                                allowEmpty: true,
                                caption: '文本(动态)',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'start_time',
                              },
                            ],
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '面板容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              grow: 4,
                              shrink: 1,
                              layout: 'SIMPLEFLEX',
                            },
                            id: 'container3',
                          },
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  caption: '结束时间',
                                  halign: 'LEFT',
                                  renderMode: 'TEXT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  contentType: 'RAW',
                                  predefinedType: 'STATIC_TEXT',
                                  id: 'static_text2',
                                },
                                caption: '文本',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'static_text2',
                              },
                              {
                                editor: {
                                  halign: 'LEFT',
                                  renderMode: 'TEXT_DYNAMIC',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'end_time',
                                },
                                viewFieldName: 'END_TIME',
                                allowEmpty: true,
                                caption: '文本(动态)',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                id: 'end_time',
                              },
                            ],
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '面板容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              grow: 4,
                              shrink: 1,
                              layout: 'SIMPLEFLEX',
                            },
                            id: 'container4',
                          },
                        ],
                        predefinedType: 'CONTAINER_GRID',
                        layout: {
                          layout: 'SIMPLEFLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '栅格容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container_grid',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'container',
                  },
                ],
                layoutPanel: true,
                mobilePanel: true,
                codeName: 'a8757d512b0b1ed09eb',
                controlType: 'PANEL',
                logicName: '甘特图_项布局面板',
                appDataEntityId: 'web.master',
                controlParam: {},
                modelId: '4b30db81ef215e64ce734d69dfe0f5dc',
                modelType: 'PSSYSVIEWPANEL',
                name: 'render_layout',
                id: 'web.master.a8757d512b0b1ed09eb',
              },
              renderType: 'LAYOUTPANEL',
              id: 'render_layout',
            },
          ],
          name: '主数据',
          id: 'node',
        },
      ],
      treeGridMode: 2,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'gantt_layout_gantt',
      controlType: 'GANTT',
      height: 510,
      logicName: '甘特图_项布局面板_甘特部件',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'gantt',
      },
      modelId: 'd7857aaf4bccddc01e22679c3ecd2e02',
      modelType: 'PSDEGANTT',
      name: 'gantt',
      id: 'web.master.gantt_layout_gantt',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '甘特图_项布局面板',
      codeName: 'gantt_layout_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_layout_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGANTTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '甘特图_项布局面板',
  viewStyle: 'DEFAULT',
  viewType: 'DEGANTTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e8fc88a852947074fec2dfd264652f35',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgantt_layout',
  id: 'web.master_gantt_layout',
};
