export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'treeExpbarNavparamTreeExpView',
  deviewId: 'a09f544e8c8c19bd630e0ee9078931bc',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树导航栏_导航参数',
  codeName: 'master_tree_expbar_navparam_tree_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'treeexp_navparam',
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realOpenMode: 'POPUPMODAL',
          realTitle: '区划信息',
          refAppViewId: 'web.region_info_view',
          name: 'EXPITEM:node',
          id: 'expitem:node',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                pickupDEFName: 'PARENT_ID',
                codeName: 'parent',
                dertype: 'DER1N',
                logicName: '上级区划',
                orderValue: 100,
                serviceCodeName: 'parent',
                name: 'DER1N_REGION_REGION_PARENT_ID',
                id: 'mock.region.der1n_region_region_parent_id',
              },
              parentDETreeNodeId: 'node',
              parentValueLevel: 1,
              searchMode: 3,
              id: '区划（node）-区划（node）',
            },
            {
              childDETreeNodeId: 'node',
              parentAppDEFieldId: 'parent_id',
              parentDER1N: {
                pickupDEFName: 'PARENT_ID',
                codeName: 'parent',
                dertype: 'DER1N',
                logicName: '上级区划',
                orderValue: 100,
                serviceCodeName: 'parent',
                name: 'DER1N_REGION_REGION_PARENT_ID',
                id: 'mock.region.der1n_region_region_parent_id',
              },
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-区划（node）',
              id: '默认根节点（root）-区划（node）',
            },
          ],
          detreeNodes: [
            {
              nodeValue: '86',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              enableQuickSearch: true,
              expanded: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              dataSourceType: 'DEDATASET',
              idAppDEFieldId: 'id',
              leafFlagAppDEFieldId: 'leaf',
              appDEDataSetId: 'fetch_default',
              sortAppDEFieldId: 'sort',
              textAppDEFieldId: 'name',
              navAppViewId: 'web.region_info_view',
              nodeType: 'node',
              appDataEntityId: 'web.region',
              navigateParams: [
                {
                  key: 'name',
                  value: 'name',
                  id: 'name',
                },
              ],
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              enableQuickSearch: true,
              expanded: true,
              name: '区划',
              id: 'node',
            },
          ],
          outputIconDefault: true,
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.master',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'web.master',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.master',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'tree_expbar_navparam_tree_exp_view_tree_view',
          controlType: 'TREEVIEW',
          logicName: '树导航栏_导航参数_树视图',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          modelId: 'b9edc923954da56ff060583b8df16da3',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'web.master.tree_expbar_navparam_tree_exp_view_tree_view',
        },
      ],
      codeName: 'tree_expbar_navparam_tree_exp_view_treeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'treeexpbar',
      },
      width: 500,
      modelId: 'bb475fab0b8217834c4eb05664b81aca_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'tree_expbar_navparam_tree_exp_view_treeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树导航栏_导航参数',
      codeName: 'tree_expbar_navparam_tree_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_expbar_navparam_tree_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树导航栏_导航参数',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'bb475fab0b8217834c4eb05664b81aca',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreeExpbarNavparamTreeExpView',
  id: 'web.master_tree_expbar_navparam_tree_exp_view',
};
