export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'PIcker_singletabexpview',
  deviewId: 'de2c23fab6c31493176976a02e717ba6',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '选择视图面板_单选分页导航视图',
  codeName: 'master_p_icker_singletabexpview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_pickup_edit_view',
          id: 'default',
        },
        {
          caption: '左右关系',
          appViewId: 'web.master_pickup_editview2',
          id: 'leftright',
        },
      ],
      dataRelationTag: 'DataRelation102',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_p_icker_singletabexpview__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation102',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '8892700ef787081a82f8fcfb9e7f780a',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation102',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '选择视图面板_单选分页导航视图',
      codeName: 'p_icker_singletabexpview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'p_icker_singletabexpview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_单选分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c37cb8601508080f635bea177ca5831d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPIcker_singletabexpview',
  id: 'web.master_p_icker_singletabexpview',
};
