export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendar_contextmenu',
  deviewId: 'bb9382a7caebf094cae73fba8b6cff70',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_上下文菜单',
  codeName: 'master_calendar_contextmenu',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'calendar_contextmenu',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '天',
          appViewId: 'web.master_calendar_contextmenu_day',
          id: 'day',
        },
        {
          caption: '周',
          appViewId: 'web.master_calendar_contextmenu_week',
          id: 'week',
        },
        {
          caption: '月',
          appViewId: 'web.master_calendar_contextmenu_month',
          id: 'month',
        },
        {
          caption: '时间轴',
          appViewId: 'web.master_calendar_contextmenu_timeline',
          id: 'timeline',
        },
        {
          caption: '用户自定义',
          appViewId: 'web.master_calendar_contextmenu_user',
          id: 'user',
        },
        {
          caption: '多数据源',
          appViewId: 'web.master_calendar_contextmenu_multiple_data',
          id: 'multiple_data',
        },
      ],
      dataRelationTag: 'calendar_contextmenu_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar_contextmenu__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_contextmenu_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '4876e8a8cc77af31bd6c320ed0a46940',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'calendar_contextmenu_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_上下文菜单',
      codeName: 'calendar_contextmenu_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_contextmenu_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_上下文菜单',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '61262bb90acc9b16dc24bcca84c4d089',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_contextmenu',
  id: 'web.master_calendar_contextmenu',
};
