export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'DefaultDateTabExpView',
  deviewId: '74c18cc827ebbfa9c8d8602ad1fbeeca',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '设置默认日期',
  codeName: 'master_default_date_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup14',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '天',
          appViewId: 'web.master_default_date_calendar_view_day',
          id: 'day',
        },
        {
          caption: '周',
          appViewId: 'web.master_default_date_calendar_view_week',
          id: 'week',
        },
        {
          caption: '月',
          appViewId: 'web.master_default_date_calendar_view_month',
          id: 'month',
        },
        {
          caption: '用户自定义',
          appViewId: 'web.master_default_date_calendar_view_custom',
          id: 'custom',
        },
      ],
      dataRelationTag: 'DataRelation119',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_default_date_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation119',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '36b9e0eb25487f720b1cc500491d5036',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation119',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '设置默认日期',
      codeName: 'default_date_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'default_date_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '设置默认日期',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '8c52bc4289fdf713b6ff1cb61cf6be06',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERDefaultDateTabExpView',
  id: 'web.master_default_date_tab_exp_view',
};
