export default {
  deviewCodeName: 'WizardView_logic',
  deviewId: '500aaaf885ba4cd350ea50835b39f396',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '逻辑',
  codeName: 'master_wizard_view_logic',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'WizardView',
      id: 'engine',
    },
  ],
  appViewParams: [
    {
      key: 'SRFRENEWSESSION',
      value: 'true',
      name: 'SRFRENEWSESSION',
      id: 'srfrenewsession',
    },
  ],
  controls: [
    {
      finishControlAction: {
        appDEMethodId: 'mock_create',
        appDataEntityId: 'web.master',
        id: 'finish',
      },
      initControlAction: {
        appDEMethodId: 'createtemp',
        appDataEntityId: 'web.master',
        id: 'init',
      },
      deeditForms: [
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'step1',
            goNextEnableScriptCode: 'data.name',
            deformName: '向导表单1（启用条件）',
            dewizardStepId: '步骤1',
            stepActions: ['NEXT'],
            stepTag: 'step1',
            firstForm: true,
            id: '向导表单1',
          },
          formFuncMode: 'WIZARDFORM',
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.MASTER.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  rawItem: {
                    contentType: 'INFO',
                    rawContent:
                      '{"title":"当名称有值时才会显示下一步按钮","closeabled":false,"showIcon":true}',
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.MASTER.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'wizardform4',
          controlType: 'FORM',
          logicName: '向导表单1（启用条件）',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_step1',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_step1',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_step1',
          },
          modelId: '6d7891f3adb8e0415b770b742e78e2d7',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_step1',
          id: 'web.master.wizardform4',
        },
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'step2',
            goPrevEnableScriptCode: '!data.quantity',
            deformName: '向导表单2（启用条件）',
            dewizardStepId: '步骤2',
            stepActions: ['PREV', 'NEXT'],
            stepTag: 'step2',
            id: '向导表单2',
          },
          formFuncMode: 'WIZARDFORM',
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 6,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'quantity',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'quantity',
                  },
                  allowEmpty: true,
                  caption: '数量',
                  codeName: 'quantity',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'quantity',
                },
                {
                  rawItem: {
                    contentType: 'INFO',
                    rawContent:
                      '{"title":"当数量有值时会隐藏上一步按钮","closeabled":false,"showIcon":true}',
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.MASTER.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'wizardform5',
          controlType: 'FORM',
          logicName: '向导表单2（启用条件）',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_step2',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_step2',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_step2',
          },
          modelId: 'c97e2c1b3a5751f2e5a1f2bd156ee1e2',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_step2',
          id: 'web.master.wizardform5',
        },
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'step3',
            goFinishEnableScriptCode: 'data.description',
            deformName: '向导表单3（启用条件）',
            dewizardStepId: '步骤3',
            stepActions: ['PREV', 'FINISH'],
            stepTag: 'step3',
            id: '向导表单3',
          },
          formFuncMode: 'WIZARDFORM',
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemHeight: 200,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    maxLength: 2000,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'description',
                  },
                  allowEmpty: true,
                  caption: '描述',
                  codeName: 'description',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'description',
                },
                {
                  rawItem: {
                    contentType: 'INFO',
                    rawContent:
                      '{"title":"当描述有值时才会显示完成按钮","closeabled":false,"showIcon":true}',
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.MASTER.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'wizardform6',
          controlType: 'FORM',
          logicName: '向导表单3（启用条件）',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_step3',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_step3',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_step3',
          },
          modelId: 'bff6939386e61a87f7f48d5a5bc60267',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_step3',
          id: 'web.master.wizardform6',
        },
      ],
      dewizard: {
        codeName: 'Wizard_logic',
        finishCaption: '完成',
        firstDEWizardFormId: '向导表单1',
        nextCaption: '下一步',
        dewizardForms: [
          {
            formTag: 'step1',
            goNextEnableScriptCode: 'data.name',
            deformName: '向导表单1（启用条件）',
            dewizardStepId: '步骤1',
            stepActions: ['NEXT'],
            stepTag: 'step1',
            firstForm: true,
            id: '向导表单1',
          },
          {
            formTag: 'step2',
            goPrevEnableScriptCode: '!data.quantity',
            deformName: '向导表单2（启用条件）',
            dewizardStepId: '步骤2',
            stepActions: ['PREV', 'NEXT'],
            stepTag: 'step2',
            id: '向导表单2',
          },
          {
            formTag: 'step3',
            goFinishEnableScriptCode: 'data.description',
            deformName: '向导表单3（启用条件）',
            dewizardStepId: '步骤3',
            stepActions: ['PREV', 'FINISH'],
            stepTag: 'step3',
            id: '向导表单3',
          },
        ],
        dewizardSteps: [
          {
            stepTag: 'step1',
            title: '步骤1',
            id: '步骤1',
          },
          {
            stepTag: 'step2',
            title: '步骤2',
            id: '步骤2',
          },
          {
            stepTag: 'step3',
            title: '步骤3',
            id: '步骤3',
          },
        ],
        prevCaption: '上一步',
        wizardStyle: 'DEFAULT',
        name: '向导_启用逻辑',
        id: 'mock.master.wizard_logic',
      },
      wizardStyle: 'DEFAULT',
      showActionBar: true,
      showStepBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'wizard_logic',
      controlType: 'WIZARDPANEL',
      logicName: '向导_启用逻辑',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'wizardpanel',
      },
      modelId: '042de4f838a61389b41129e86551c8e6',
      modelType: 'PSDEWIZARDPANEL',
      name: 'wizardpanel',
      id: 'web.master.wizard_logic',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '逻辑',
      codeName: 'wizard_view_logic_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'wizard_view_logic_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEWIZARDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '向导_逻辑_向导视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEWIZARDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9846b02928fab21d9c29ef25c33195ab',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERWizardView_logic',
  id: 'web.master_wizard_view_logic',
};
