export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'kanban',
  loadDefault: true,
  deviewCodeName: 'kannam_order__draggable',
  deviewId: '238c312f41c7ba0ba454ddd9fb44a32d',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '看板_排序拖拽',
  codeName: 'master_kannam_order_draggable',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'KanBanView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      updateGroupControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'updategroup',
      },
      groupLayout: 'ROW',
      groupMode: 'CODELIST',
      groupAppDEFieldId: 'status',
      groupCodeListId: 'web.mock__cl_status',
      groupStyle: 'DEFAULT',
      minorSortDir: 'ASC',
      minorSortAppDEFieldId: 'px',
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      enableCardEdit: true,
      enableCardEditOrder: true,
      enableGroup: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      moveControlAction: {
        appDEMethodId: 'move',
        appDataEntityId: 'web.master',
        id: 'move',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'kanban_order_draggable',
      controlType: 'KANBAN',
      height: 700,
      logicName: '看板_排序拖拽',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'kanban',
      },
      modelId: '5130e87f6ef0efdc0e348c7446784d80',
      modelType: 'PSDEKANBAN',
      name: 'kanban',
      id: 'web.master.kanban_order_draggable',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '看板_排序拖拽',
      codeName: 'kannam_order_draggable_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'kannam_order_draggable_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEKANBANVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '看板_排序拖拽',
  viewStyle: 'DEFAULT',
  viewType: 'DEKANBANVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0e159a7b10a09c72f8fd594903c757a7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERkannam_order__draggable',
  id: 'web.master_kannam_order_draggable',
};
