export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'treegridex',
  loadDefault: true,
  deviewCodeName: 'TreeGridEx_css',
  deviewId: '1d36bb2093d974042826a7479473dca9',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树表格增强_界面样式及图标',
  codeName: 'master_tree_grid_ex_css',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeGridExView',
      id: 'engine',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detreeColumns: [
        {
          align: 'CENTER',
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 250,
          widthUnit: 'px',
          id: 'name',
        },
        {
          align: 'CENTER',
          caption: '编码',
          cellSysCss: {
            cssName: 'gird-cell-brack',
          },
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          headerSysCss: {
            cssName: 'gird-red-border',
          },
          sysImage: {
            cssClass: 'snow',
          },
          width: 200,
          widthUnit: 'px',
          id: 'code',
        },
        {
          align: 'CENTER',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'STAR',
          id: 'status',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '区域数据（node）-区域数据（node）',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-顶级区域（node）',
          id: '默认根节点（root）-顶级区域（node）',
        },
      ],
      detreeNodes: [
        {
          nodeValue: '86',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.region',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'code',
              appDEFieldId: 'code',
              valueType: 'SIMPLE',
              codeName: 'code',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'code',
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'FRONT',
              dataItemName: 'status',
              appCodeListId: 'web.mock__cl_status',
              appDEFieldId: 'status',
              valueType: 'SIMPLE',
              codeName: 'status',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'status',
              id: 'status',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'code',
              detreeColumnId: 'code',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'status',
              detreeColumnId: 'status',
              valueType: 'SIMPLE',
              dataType: 9,
              id: 'status',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '区域数据',
          id: 'node',
        },
      ],
      treeGridMode: 1,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_grid_ex_css_tree_grid',
      controlType: 'TREEGRIDEX',
      logicName: '树表格增强_界面样式及图标_树表格',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'treegridex',
      },
      modelId: '13b94bb6dd5408076f53865c38a4b167',
      modelType: 'PSDETREEGRIDEX',
      name: 'treegridex',
      id: 'web.master.tree_grid_ex_css_tree_grid',
    },
    {
      xdataControlName: 'treegridex',
      codeName: 'tree_grid_ex_css_toolbar',
      controlType: 'TOOLBAR',
      logicName: '树表格增强_界面样式及图标_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '122d58fc1898807ba877a2281ec66ee9',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'tree_grid_ex_css_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树表格增强_界面样式及图标',
      codeName: 'tree_grid_ex_css_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_grid_ex_css_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEGRIDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格增强_界面样式及图标',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDEXVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '72bd19a2c94c9cb68ab44a92b8d676ff',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTreeGridEx_css',
  id: 'web.master_tree_grid_ex_css',
};
