export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'list_sort_exp',
  deviewId: '9d703a68f8363b81b5014b4c38680868',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_排序导航视图',
  codeName: 'master_list_sort_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '默认排序',
          appViewId: 'web.master_list_default_sort',
          id: 'default',
        },
        {
          caption: '禁用排序',
          appViewId: 'web.master_list_disable_sort',
          id: 'disable',
        },
      ],
      dataRelationTag: 'list_sort_exp_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_list_sort_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_sort_exp_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'e27ff6bf0c26322fa3d9b1888b22593c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'list_sort_exp_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '列表_排序导航视图',
      codeName: 'list_sort_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'list_sort_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表_排序导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a7f470ef442ac9269d4dcdd237a8eec4',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_sort_exp',
  id: 'web.master_list_sort_exp',
};
