export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'kanban_swimlane_draggable_exp',
  deviewId: 'd3e3e423990b7dd40e9fca27dad47f05',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '看板_泳道拖拽导航视图',
  codeName: 'master_kanban_swimlane_draggable_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'usrvmgroup0718426410',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '无拖拽',
          appViewId: 'web.master_kanban_swimlane_no_draggable',
          id: 'no',
        },
        {
          caption: '仅同分组拖拽',
          appViewId: 'web.master_kanban_swimlane_group_draggable',
          id: 'group',
        },
        {
          caption: '仅同泳道拖拽',
          appViewId: 'web.master_kanban_swimlane_lane_draggable',
          id: 'lane',
        },
        {
          caption: '均可拖拽',
          appViewId: 'web.master_kanban_swimlane_draggable',
          id: 'all',
        },
      ],
      dataRelationTag: 'DataRelation77',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_kanban_swimlane_draggable_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation77',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '96e6038c6060bd1779df3a9b8a2b612c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation77',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '看板_泳道拖拽导航视图',
      codeName: 'kanban_swimlane_draggable_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'kanban_swimlane_draggable_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '看板_泳道拖拽导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '7931e7a6256f488e4f0103011fdacd75',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERkanban_swimlane_draggable_exp',
  id: 'web.master_kanban_swimlane_draggable_exp',
};
