export default {
  deviewCodeName: 'Pickup_treepickupview',
  deviewId: '7eed7c1beedc2ef420a8e56ee206cb44',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树数据选择视图',
  codeName: 'master_pickup_treepickupview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onSelectionChange',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'pickupviewpanel',
      scriptCode:
        "const tips = '选择视图面板的选中数据变更事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips, `选中数据:`, data);",
      builtinLogic: true,
      id: 'logic',
    },
  ],
  appViewMsgGroupId: 'pickup_eventandcall',
  controls: [
    {
      embeddedAppDEViewId: 'web.master_pickup_treepickupcontrolview',
      codeName: 'pickup_treepickupview_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_treepickupview_pickupviewpanel',
    },
    {
      codeName: 'pickup_treepickupview_toolbar',
      controlType: 'TOOLBAR',
      logicName: '选择视图面板工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fa9213d29a94558349d0f4fd85a15a32',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'pickup_treepickupview_toolbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树数据选择视图',
      codeName: 'pickup_treepickupview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_treepickupview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_树数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6be3dcd5819a07cebb7041a76804cf1a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_treepickupview',
  id: 'web.master_pickup_treepickupview',
};
