export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'tree_appgloable_datasource',
  deviewId: 'ad8eb4e43e4079f6dd9b120d8ef3fe8f',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_应用全局变量数据源',
  codeName: 'master_tree_appgloable_datasource',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onCreated',
      logicTrigger: 'VIEWEVENT',
      logicType: 'SCRIPT',
      scriptCode:
        "const state = ibiz.util.getGlobalParam();\r\nstate.master=[\r\n    { id: '1', name: '应用全局变量参数1' },\r\n    { id: '2', name: '应用全局变量参数2' },\r\n    { id: '3', name: '应用全局变量参数3' },\r\n]",
      builtinLogic: true,
      name: 'onCreated',
      id: 'oncreated',
    },
  ],
  appViewMsgGroupId: 'vmgroup57',
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 应用全局变量数据源',
        },
        {
          childDETreeNodeId: 'master',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '应用全局变量数据源 - 主数据',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataName: 'master',
          dataSourceType: 'APPGLOBALPARAM',
          idAppDEFieldId: 'id',
          textAppDEFieldId: 'name',
          nodeType: 'master',
          appDataEntityId: 'web.master',
          treeNodeType: 'DE',
          name: '主数据',
          id: 'master',
        },
        {
          text: '应用全局变量数据源',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          name: '应用全局变量数据源',
          id: 'node',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_appgloable_datasource',
      controlType: 'TREEVIEW',
      logicName: '树视图_应用全局变量数据源',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: '67b718749c3ba2d7734455299295f308',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_appgloable_datasource',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_应用全局变量数据源',
      codeName: 'tree_appgloable_datasource_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_appgloable_datasource_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_应用全局变量数据源',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1748c251d837cd0cbe739a8ad77b1276',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtree_appgloable_datasource',
  id: 'web.master_tree_appgloable_datasource',
};
