export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_bottomnav_timeline',
  deviewId: 'c8dcf68563c356e67de4c58871702448',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置导航栏_下方导航_时间轴',
  codeName: 'master_calendar_bottomnav_timeline',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '日历',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'calendar',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        contentHeight: 1000,
        height: 1000,
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          height: 1000,
          heightMode: 'PX',
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        calendarStyle: 'TIMELINE',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'start_time',
            endTimeAppDEFieldId: 'end_time',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'master',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.master',
            navAppViewId: 'web.master_info_view',
            name: '主数据',
            id: 'master',
          },
        ],
        navViewHeight: 300,
        navViewPos: 'BOTTOM',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'calendar_bottomnav_timeline',
        controlType: 'CALENDAR',
        logicName: '日历_内置导航栏_下方导航_时间轴',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'calendar',
        },
        modelId: 'c1de316949b88756d7b34ebafd58f12c',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.master.calendar_bottomnav_timeline',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '日历_内置导航栏_下方导航_时间轴',
        codeName: 'calendar_bottomnav_timeline_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'calendar_bottomnav_timeline_captionbar',
      },
    ],
    codeName: 'a1c4293956239f22919',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'calendar_bottomnav_timeline日历视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '7194e44247fd7aec148224ad12c6ef47',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a1c4293956239f22919',
  },
  title: '日历_内置导航栏_下方导航_时间轴',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9804ebf3f0dbc6788c0d2055504e8ef5',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_bottomnav_timeline',
  id: 'web.master_calendar_bottomnav_timeline',
};
