export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'form_value_display',
  deviewId: 'fb20348b9add0ebec519a6cfaea1a64d',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑表单_值显示',
  codeName: 'master_form_value_display',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'form_value_display',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'form_value_display_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑表单_值显示_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'd12ede5a7135facb3dcc6590ad4ab090',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'form_value_display_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get_sample_data',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      createDV: '1234.1',
                      dataType: 6,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'numberval',
                      editor: {
                        editorType: 'NUMBER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'format1',
                      },
                      updateDV: '1234.1',
                      valueFormat: '#.#\\元',
                      allowEmpty: true,
                      caption: '数值编辑器格式化',
                      codeName: 'format1',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      defdgroupLogics: [
                        {
                          logicCat: 'SCRIPTCODE_CHANGE',
                          groupOP: 'AND',
                          defdlogics: [
                            {
                              value: 'data.customformat1 = data.format1',
                              logicType: 'SINGLE',
                              id: ' data.customformat1 = data.format1',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 350,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'format1',
                    },
                    {
                      createDV: '1234.1',
                      dataType: 6,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'numberval',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorParams: {
                          format: '#.0#元',
                        },
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'customformat1',
                      },
                      updateDV: '1234.1',
                      valueFormat: '#.#\\元',
                      allowEmpty: true,
                      caption: '格式化后',
                      codeName: 'customformat1',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'customformat1',
                    },
                  ],
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel1',
                },
                {
                  rawItem: {
                    caption:
                      '说明：值【1234.1】，使用【#.#\\元】进行格式化，预期效果【1234.1元】。格式编码参考：https://github.com/13601313270/vue-format',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
                {
                  createDV: '1',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 200,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'web.mock__cl_status',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'datatype',
                  },
                  updateDV: '1',
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '代码表未转换代码项文本',
                  codeName: 'datatype',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'datatype',
                },
                {
                  createDV: '0',
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 200,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'web.mock__cl_status',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  updateDV: '0',
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  needCodeListConfig: true,
                  caption: '代码表转换代码项文本',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem',
                },
                {
                  rawItem: {
                    caption:
                      '说明：可通过配置决定是否转换代码表，不转换时显示代码表项的原值，转换时显示代码表项对应的文本值',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem5',
                  },
                  codeName: 'rawitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem5',
                },
              ],
              caption: '分组',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main19',
      controlType: 'FORM',
      logicName: '编辑表单_值显示_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'a6ca50b8df9aabf623b9753a6e3f7ed4',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main19',
    },
    {
      codeName: 'form_value_display_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'form_value_display_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑表单_值显示',
      codeName: 'form_value_display_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'form_value_display_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑表单_值显示',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ec720366e627d080a1903b30e3ba15fb',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERform_value_display',
  id: 'web.master_form_value_display',
};
