export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'treegridex',
  loadDefault: true,
  deviewCodeName: 'treegridex_nav_bottom',
  deviewId: '7acf14614d0a95d96a542ae157bcce2f',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树表格增强_底部导航',
  codeName: 'master_treegridex_nav_bottom',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '树表格',
            contentHeight: 600,
            height: 600,
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              height: 600,
              heightMode: 'PX',
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'treegridex',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'TreeGridExView',
        id: 'engine',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '主数据编辑视图',
        refAppViewId: 'web.master_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detreeColumns: [
          {
            align: 'CENTER',
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            width: 250,
            widthUnit: 'px',
            id: 'name',
          },
          {
            align: 'CENTER',
            caption: '编码',
            codeName: 'code',
            columnType: 'DEFGRIDCOLUMN',
            width: 200,
            widthUnit: 'px',
            id: 'code',
          },
          {
            align: 'CENTER',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            width: 100,
            widthUnit: 'STAR',
            id: 'status',
          },
        ],
        detreeNodeRSs: [
          {
            childDETreeNodeId: 'node',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '父项',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
              id: 'mock.category.der1n_category_category_parent_id',
            },
            parentDETreeNodeId: 'node',
            parentValueLevel: 1,
            searchMode: 3,
            id: 'null - null',
          },
          {
            childDETreeNodeId: 'node',
            parentAppDEFieldId: 'parent_id',
            parentDER1N: {
              pickupDEFName: 'PARENT_ID',
              codeName: 'parent',
              dertype: 'DER1N',
              logicName: '父项',
              orderValue: 100,
              serviceCodeName: 'parent',
              name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
              id: 'mock.category.der1n_category_category_parent_id',
            },
            parentDETreeNodeId: 'root',
            parentValueLevel: 1,
            searchMode: 3,
            id: 'null - null',
          },
        ],
        detreeNodes: [
          {
            nodeValue: '86',
            text: '默认根节点',
            nodeType: 'ROOT',
            treeNodeType: 'STATIC',
            hasDETreeNodeRSs: true,
            rootNode: true,
            name: '默认根节点',
            id: 'root',
          },
          {
            dataSourceType: 'DEDATASET',
            idAppDEFieldId: 'id',
            leafFlagAppDEFieldId: 'leaf',
            appDEDataSetId: 'fetch_default',
            textAppDEFieldId: 'name',
            navAppViewId: 'web.region_info_view',
            nodeType: 'node',
            appDataEntityId: 'web.region',
            detreeNodeColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'code',
                appDEFieldId: 'code',
                valueType: 'SIMPLE',
                codeName: 'code',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                detreeColumnId: 'code',
                id: 'code',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'name',
                appDEFieldId: 'name',
                valueType: 'SIMPLE',
                codeName: 'name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                detreeColumnId: 'name',
                id: 'name',
              },
              {
                clconvertMode: 'FRONT',
                dataItemName: 'status',
                appCodeListId: 'web.mock__cl_status',
                appDEFieldId: 'status',
                valueType: 'SIMPLE',
                codeName: 'status',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                detreeColumnId: 'status',
                id: 'status',
              },
            ],
            detreeNodeDataItems: [
              {
                clconvertMode: 'NONE',
                appDEFieldId: 'code',
                detreeColumnId: 'code',
                valueType: 'SIMPLE',
                dataType: 25,
                id: 'code',
              },
              {
                clconvertMode: 'NONE',
                appDEFieldId: 'name',
                detreeColumnId: 'name',
                valueType: 'SIMPLE',
                dataType: 25,
                id: 'name',
              },
              {
                clconvertMode: 'FRONT',
                frontCodeListId: 'web.mock__cl_status',
                appDEFieldId: 'status',
                detreeColumnId: 'status',
                valueType: 'SIMPLE',
                dataType: 9,
                id: 'status',
              },
            ],
            treeNodeType: 'DE',
            hasDETreeNodeRSs: true,
            name: '区域数据',
            id: 'node',
          },
        ],
        treeGridMode: 1,
        outputIconDefault: true,
        navViewHeight: 450,
        navViewPos: 'BOTTOM',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'treegridex_nav_bottom_tree_grid',
        controlType: 'TREEGRIDEX',
        logicName: '树表格增强_底部导航_树表格',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'treegridex',
        },
        modelId: '0e00a3317481f409b8c8a2aec1ae3b09',
        modelType: 'PSDETREEGRIDEX',
        name: 'treegridex',
        id: 'web.master.treegridex_nav_bottom_tree_grid',
      },
      {
        xdataControlName: 'treegridex',
        codeName: 'treegridex_nav_bottom_toolbar',
        controlType: 'TOOLBAR',
        logicName: '树表格增强_底部导航_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'f7627ef5af9adfea4037b0ba691b7667',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'treegridex_nav_bottom_toolbar',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '树表格增强_底部导航',
        codeName: 'treegridex_nav_bottom_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'treegridex_nav_bottom_captionbar',
      },
    ],
    codeName: 'af40052c17cc6322dfa',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'treegridex_nav_bottom树表格（增强）视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '5b1fe0309aadd927efb369ac9a13501c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'af40052c17cc6322dfa',
  },
  title: '树表格增强_底部导航',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDEXVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '14bdd0b710ed55cea0917c6ddfa328b0',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreegridex_nav_bottom',
  id: 'web.master_treegridex_nav_bottom',
};
