export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'card_built_in_toolbar_exp',
  deviewId: 'C157520C-4C01-4191-B924-8FE07B845CA5',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_内置工具栏导航视图',
  codeName: 'master_card_built_in_toolbar_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '快速操作工具栏',
          appViewId: 'web.master_card_quicktoolbar',
          id: 'card_quick_toolbar',
        },
        {
          caption: '批操作工具栏',
          appViewId: 'web.master_card_batchtoolbar',
          id: 'card_batch_toolbar',
        },
      ],
      dataRelationTag: 'DataRelation46',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_card_built_in_toolbar_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation46',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'D409DCA2-6F18-43DB-B79F-2DDE44790582',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation46',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_内置工具栏导航视图',
      codeName: 'card_built_in_toolbar_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_built_in_toolbar_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_内置工具栏导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2baddf95b044040176ce0c8dd2461711',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_built_in_toolbar_exp',
  id: 'web.master_card_built_in_toolbar_exp',
};
