export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_dy_uiaction_group',
  deviewId: '08d0e88cfdce1cd2a3efeabfc21a202e',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_动态界面行为组',
  codeName: 'master_card_dy_uiaction_group',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'vmgroup310',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      cardHeight: 120,
      cardWidth: 300,
      groupLayout: 'ROW',
      groupMode: 'CODELIST',
      groupAppDEFieldId: 'status',
      groupCodeListId: 'web.mock__cl_status',
      groupUIActionGroup: {
        dynamicMode: 1,
        actionLevelAppDEFieldId: 'level',
        buttonStyleAppDEFieldId: 'button_style',
        clsAppDEFieldId: 'style',
        detailAppDEDataSetId: 'fetch_web_data_set',
        detailAppDataEntityId: 'web.ua_group_detail',
        enableScriptAppDEFieldId: 'enable_logic',
        iconClsAppDEFieldId: 'icon_cls',
        appDataEntityId: 'web.master',
        textAppDEFieldId: 'caption',
        tipsAppDEFieldId: 'tooltip',
        uiactionTagAppDEFieldId: 'action_tag',
        uniqueTag: 'master__web_dynamic_ex_ua',
        visibleScriptAppDEFieldId: 'visible_logic',
        name: 'web扩展界面行为组（动态）',
        id: 'web_dynamic_ex_ua',
      },
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      dedataViewItems: [
        {
          dataItemName: 'dataitem',
          itemType: 'ACTIONITEM',
          deuiactionGroup: {
            dynamicMode: 1,
            actionLevelAppDEFieldId: 'level',
            buttonStyleAppDEFieldId: 'button_style',
            clsAppDEFieldId: 'style',
            detailAppDEDataSetId: 'fetch_web_data_set',
            detailAppDataEntityId: 'web.ua_group_detail',
            enableScriptAppDEFieldId: 'enable_logic',
            iconClsAppDEFieldId: 'icon_cls',
            appDataEntityId: 'web.master',
            textAppDEFieldId: 'caption',
            tipsAppDEFieldId: 'tooltip',
            uiactionTagAppDEFieldId: 'action_tag',
            uniqueTag: 'master__web_dynamic_ex_ua',
            visibleScriptAppDEFieldId: 'visible_logic',
            name: 'web扩展界面行为组（动态）',
            id: 'web_dynamic_ex_ua',
          },
          id: 'dataitem',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      enableGroup: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_uiactiongroup_data_view',
      controlType: 'DATAVIEW',
      logicName: '卡片_动态界面行为组_卡片视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: '9b59561967ab611d051f2def33bccf8f',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_uiactiongroup_data_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_动态界面行为组',
      codeName: 'card_dy_uiaction_group_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_dy_uiaction_group_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_动态界面行为组',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd1e71a70d8e45037a3876c43f7af7862',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_dy_uiaction_group',
  id: 'web.master_card_dy_uiaction_group',
};
