export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'report_exp',
  deviewId: '389f3b7ae8f92f1159cb83af8fe28c47',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '报表_导航视图',
  codeName: 'master_report_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '智能报表-数值',
          appViewId: 'web.master_bi_report_number',
          name: 'BIReport_number',
          id: 'bireport_number',
        },
        {
          caption: '智能报表-多序列柱状图',
          appViewId: 'web.master_bi_report_multi_bar',
          name: 'BIReport_multi_bar',
          id: 'bireport_multi_bar',
        },
        {
          caption: '智能报表-多序列堆叠柱状图',
          appViewId: 'web.master_bi_report_multi_stack_bar',
          name: 'BIReport_multi_stack_bar',
          id: 'bireport_multi_stack_bar',
        },
        {
          caption: '智能报表-多序列分区柱状图',
          appViewId: 'web.master_bi_report_multi_partition_bar',
          name: 'BIReport_multi_partition_bar',
          id: 'bireport_multi_partition_bar',
        },
        {
          caption: '智能报表-多序列条形图',
          appViewId: 'web.master_bi_report_multi_strip',
          name: 'BIReport_multi_strip',
          id: 'bireport_multi_strip',
        },
        {
          caption: '智能报表-多序列叠柱条形图',
          appViewId: 'web.master_bi_report_multi_stack_strip',
          name: 'BIReport_multi_stack_strip',
          id: 'bireport_multi_stack_strip',
        },
        {
          caption: '智能报表-多序列折线图 ',
          appViewId: 'web.master_bi_report_multi_line',
          name: 'BIReport_multi_line',
          id: 'bireport_multi_line',
        },
        {
          caption: '智能报表-多序列分区折线图',
          appViewId: 'web.master_bi_report_multi_partition_line',
          name: 'BIReport_multi_partition_line',
          id: 'bireport_multi_partition_line',
        },
        {
          caption: '智能报表-面积图',
          appViewId: 'web.master_bi_report_area',
          name: 'BIReport_area',
          id: 'bireport_area',
        },
        {
          caption: '智能报表-表格',
          appViewId: 'web.master_bi_report_table',
          name: 'BIReport_table',
          id: 'bireport_table',
        },
        {
          caption: '智能报表-交叉表',
          appViewId: 'web.master_bi_report_intersection_table',
          name: 'BIReport_intersection_table',
          id: 'bireport_intersection_table',
        },
        {
          caption: '智能报表-饼图',
          appViewId: 'web.master_bi_report_pie',
          name: 'BIReport_pie',
          id: 'bireport_pie',
        },
        {
          caption: '智能报表-雷达图',
          appViewId: 'web.master_bi_report_radar',
          name: 'BIReport_radar',
          id: 'bireport_radar',
        },
        {
          caption: '智能报表-仪表盘',
          appViewId: 'web.master_bi_report_dashboard',
          name: 'BIReport_dashboard',
          id: 'bireport_dashboard',
        },
        {
          caption: '智能报表-散点图',
          appViewId: 'web.master_bi_report_scatter',
          name: 'BIReport_scatter',
          id: 'bireport_scatter',
        },
      ],
      dataRelationTag: 'DataRelation152',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_report_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation152',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '422b8bb8190df7cced739b478886e009',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation152',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '报表_导航视图',
      codeName: 'report_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'report_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '报表_导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'bf5e362ee92808d20e2da0e597a9dea7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERreport_exp',
  id: 'web.master_report_exp',
};
