export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'kanban_enablefullscreen_exp',
  deviewId: 'c4da9387f1d8355b4d2d8cefecb211b2',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '看板_启用全屏导航视图',
  codeName: 'master_kanban_enablefullscreen_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup49',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '看板不启用全屏',
          appViewId: 'web.master_kanban_enablefullscreen',
          id: 'kanban',
        },
        {
          caption: '泳道不启用全屏',
          appViewId: 'web.master_kanban_swimlane_enablefullscreen',
          id: 'swimlane',
        },
      ],
      dataRelationTag: 'DataRelation111',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_kanban_enablefullscreen_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation111',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'ce3c7982605c4bc1802c4990de5a8e33',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation111',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '看板_启用全屏导航视图',
      codeName: 'kanban_enablefullscreen_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'kanban_enablefullscreen_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '看板_启用全屏导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '86cec7877e0b70a8dd33a6ace9918d86',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERkanban_enablefullscreen_exp',
  id: 'web.master_kanban_enablefullscreen_exp',
};
