export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'Runtime_Components',
  deviewId: '40e95d4f05a1a7a6e6818b90dc20f152',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_运行时组件',
  codeName: 'master_runtime_components',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'runtime_components',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.master',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'web.master',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.master',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.master',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.master',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.master',
          id: 'update',
        },
        wfstartControlAction: {
          appDEMethodId: 'wfstart',
          appDataEntityId: 'web.master',
          id: 'wfstart',
        },
        wfsubmitControlAction: {
          appDEMethodId: 'wfsubmit',
          appDataEntityId: 'web.master',
          id: 'wfsubmit',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 30,
                    noPrivDisplayMode: 1,
                    editor: {
                      singleSelect: true,
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        PICKUPVIEW: 'FALSE',
                      },
                      editorStyle: 'PERSONEL_SELECT',
                      editorType: 'PICKEREX_TRIGGER',
                      sysPFPluginId: 'person_select',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'formitem',
                    },
                    allowEmpty: true,
                    codeName: 'formitem',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'formitem',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 30,
                    noPrivDisplayMode: 1,
                    editor: {
                      singleSelect: true,
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        ISSHOWTAB: 'false',
                        'SRFNAVPARAM.size': '50',
                        CLEARFILTER: 'true',
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        URL: '/user/fetch_default',
                        PICKUPVIEW: 'FALSE',
                        'SRFNAVPARAM.page': '0',
                        SUFFIX: 'department_name',
                        USERMETHOD: 'post',
                        USERMAP: '{"id":"id","name":"display_name"}',
                      },
                      editorStyle: 'PERSONEL_SELECT_ALL',
                      editorType: 'PICKEREX_TRIGGER',
                      sysPFPluginId: 'person_select',
                      valueType: 'SIMPLE',
                      editable: true,
                      navigateParams: [
                        {
                          key: 'size',
                          value: '50',
                          rawValue: true,
                          id: 'size',
                        },
                        {
                          key: 'page',
                          value: '0',
                          rawValue: true,
                          id: 'page',
                        },
                      ],
                      id: 'formitem1',
                    },
                    allowEmpty: true,
                    codeName: 'formitem1',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'formitem1',
                  },
                ],
                caption: '运行时组件',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'field6',
                          editorParams: {
                            url: '/sysorganizations/alls/suborg/picker',
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorStyle: 'ALLORGSELECT',
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'field6',
                            },
                          ],
                          sysPFPluginId: 'orgselect',
                          placeHolder: '请选择单位',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field5',
                        },
                        allowEmpty: true,
                        caption: '全部单位单选',
                        codeName: 'field5',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'field5',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 30,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field6',
                        },
                        allowEmpty: true,
                        caption: '值',
                        codeName: 'field6',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'field6',
                      },
                    ],
                    caption: '【单选】全部单位',
                    codeName: 'grouppanel3',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel3',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'field8',
                          editorParams: {
                            multiple: 'true',
                            url: '/sysorganizations/alls/suborg/picker',
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorStyle: 'ALLORGMULTIPLE',
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'field8',
                            },
                          ],
                          sysPFPluginId: 'orgselect',
                          placeHolder: '请选择单位',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field7',
                        },
                        allowEmpty: true,
                        caption: '全部单位多选',
                        codeName: 'field7',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'field7',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 30,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field8',
                        },
                        allowEmpty: true,
                        caption: '值',
                        codeName: 'field8',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'field8',
                      },
                    ],
                    caption: '【多选】全部单位',
                    codeName: 'grouppanel4',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel4',
                  },
                ],
                caption: '单位选择',
                codeName: 'group2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group2',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'field16',
                          editorParams: {
                            url: '/sysorganizations/${orgid}/sysdepartments/picker',
                            filter: 'srforgid',
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorStyle: 'DEPATMENTSELECT',
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'field16',
                            },
                          ],
                          sysPFPluginId: 'depatmentselect',
                          placeHolder: '请选择部门',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field15',
                        },
                        allowEmpty: true,
                        caption: '本单位部门单选',
                        codeName: 'field15',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'field15',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 30,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field16',
                        },
                        allowEmpty: true,
                        caption: '值',
                        codeName: 'field16',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'field16',
                      },
                    ],
                    caption: '【单选】本单位部门',
                    codeName: 'grouppanel7',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel7',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'field14',
                          editorParams: {
                            multiple: 'true',
                            url: '/sysorganizations/${orgid}/sysdepartments/picker',
                            filter: 'srforgid',
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorStyle: 'DEPATMENTMULTIPLE',
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'field14',
                            },
                          ],
                          sysPFPluginId: 'depatmentselect',
                          placeHolder: '请选择部门',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field13',
                        },
                        allowEmpty: true,
                        caption: '本单位部门多选',
                        codeName: 'field13',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'field13',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 30,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field14',
                        },
                        allowEmpty: true,
                        caption: '值',
                        codeName: 'field14',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'field14',
                      },
                    ],
                    caption: '【多选】本单位部门',
                    codeName: 'grouppanel8',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel8',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem4',
                              editorParams: {
                                url: '/sysorganizations/alls/suborg/picker',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'ALLORGSELECT',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem4',
                                },
                              ],
                              sysPFPluginId: 'orgselect',
                              placeHolder: '请选择单位',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem2',
                            },
                            allowEmpty: true,
                            codeName: 'formitem2',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem2',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem4',
                            },
                            allowEmpty: true,
                            caption: '单位值',
                            codeName: 'formitem4',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem4',
                          },
                        ],
                        codeName: 'grouppanel5',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel5',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem5',
                              editorParams: {
                                url: '/sysorganizations/${orgid}/sysdepartments/picker',
                                filter: 'formitem4',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'DEPATMENTSELECT',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem5',
                                },
                              ],
                              sysPFPluginId: 'depatmentselect',
                              placeHolder: '请选择部门',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem3',
                            },
                            resetItemNames: ['formitem4'],
                            allowEmpty: true,
                            codeName: 'formitem3',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedDetailNames: ['formitem4'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'formitem4',
                                    logicType: 'SINGLE',
                                    name: 'formitem4值不为空(NotNil)',
                                    id: 'formitem4值不为空(notnil)',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem3',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem5',
                            },
                            resetItemNames: ['formitem4'],
                            allowEmpty: true,
                            caption: '部门值',
                            codeName: 'formitem5',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem5',
                          },
                        ],
                        codeName: 'grouppanel6',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel6',
                      },
                    ],
                    caption: '【单选】指定单位部门',
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem8',
                              editorParams: {
                                url: '/sysorganizations/alls/suborg/picker',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'ALLORGSELECT',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem8',
                                },
                              ],
                              sysPFPluginId: 'orgselect',
                              placeHolder: '请选择单位',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem6',
                            },
                            allowEmpty: true,
                            codeName: 'formitem6',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem6',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem8',
                            },
                            allowEmpty: true,
                            caption: '单位值',
                            codeName: 'formitem8',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem8',
                          },
                        ],
                        codeName: 'grouppanel11',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel11',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem9',
                              editorParams: {
                                multiple: 'true',
                                url: '/sysorganizations/${orgid}/sysdepartments/picker',
                                filter: 'formitem8',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'DEPATMENTMULTIPLE',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem9',
                                },
                              ],
                              sysPFPluginId: 'depatmentselect',
                              placeHolder: '请选择部门',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem7',
                            },
                            resetItemNames: ['formitem8'],
                            allowEmpty: true,
                            codeName: 'formitem7',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedDetailNames: ['formitem8'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'formitem8',
                                    logicType: 'SINGLE',
                                    name: 'formitem8值不为空(NotNil)',
                                    id: 'formitem8值不为空(notnil)',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem7',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem9',
                            },
                            resetItemNames: ['formitem8'],
                            allowEmpty: true,
                            caption: '部门值',
                            codeName: 'formitem9',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem9',
                          },
                        ],
                        codeName: 'grouppanel12',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel12',
                      },
                    ],
                    caption: '【多选】指定单位部门',
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel2',
                  },
                ],
                caption: '部门选择',
                codeName: 'group3',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group3',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'field20',
                          editorParams: {
                            multiple: 'false',
                            url: '/sysorganizations/${selected-orgid}/sysemployees/picker',
                            filter: 'srforgid',
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorStyle: 'EMPSELECT',
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'field20',
                            },
                          ],
                          sysPFPluginId: 'personselect',
                          placeHolder: '请选择人员',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field19',
                        },
                        allowEmpty: true,
                        caption: '指定单位人员单选',
                        codeName: 'field19',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'field19',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 30,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field20',
                        },
                        allowEmpty: true,
                        caption: '值',
                        codeName: 'field20',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'field20',
                      },
                    ],
                    caption: '【单选】本单位人员',
                    codeName: 'grouppanel10',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel10',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        editor: {
                          enablePickupView: true,
                          singleSelect: true,
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'field18',
                          editorParams: {
                            multiple: 'true',
                            url: '/sysorganizations/${selected-orgid}/sysemployees/picker',
                            filter: 'srforgid',
                            AC: 'TRUE',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorStyle: 'EMPMULTIPLE',
                          editorType: 'PICKER',
                          editorItems: [
                            {
                              id: 'field18',
                            },
                          ],
                          sysPFPluginId: 'personselect',
                          placeHolder: '请选择人员',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field17',
                        },
                        allowEmpty: true,
                        caption: '指定单位人员多选',
                        codeName: 'field17',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'field17',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 30,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field18',
                        },
                        allowEmpty: true,
                        caption: '值',
                        codeName: 'field18',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'field18',
                      },
                    ],
                    caption: '【多选】本单位人员',
                    codeName: 'grouppanel9',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel9',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem11',
                              editorParams: {
                                url: '/sysorganizations/alls/suborg/picker',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'ALLORGSELECT',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem11',
                                },
                              ],
                              sysPFPluginId: 'orgselect',
                              placeHolder: '请选择单位',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem10',
                            },
                            allowEmpty: true,
                            codeName: 'formitem10',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem10',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem11',
                            },
                            allowEmpty: true,
                            caption: '单位值',
                            codeName: 'formitem11',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem11',
                          },
                        ],
                        codeName: 'grouppanel15',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel15',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem13',
                              editorParams: {
                                multiple: 'false',
                                url: '/sysorganizations/${selected-orgid}/sysemployees/picker',
                                filter: 'srforgid',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'EMPSELECT',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem13',
                                },
                              ],
                              sysPFPluginId: 'personselect',
                              placeHolder: '请选择人员',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem12',
                            },
                            resetItemNames: ['formitem11'],
                            allowEmpty: true,
                            codeName: 'formitem12',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedDetailNames: ['formitem11'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'formitem11',
                                    logicType: 'SINGLE',
                                    name: 'formitem11值不为空(NotNil)',
                                    id: 'formitem11值不为空(notnil)',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem12',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem13',
                            },
                            resetItemNames: ['formitem11'],
                            allowEmpty: true,
                            caption: '人员值',
                            codeName: 'formitem13',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem13',
                          },
                        ],
                        codeName: 'grouppanel16',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel16',
                      },
                    ],
                    caption: '【单选】指定单位人员',
                    codeName: 'grouppanel13',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel13',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem15',
                              editorParams: {
                                url: '/sysorganizations/alls/suborg/picker',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'ALLORGSELECT',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem15',
                                },
                              ],
                              sysPFPluginId: 'orgselect',
                              placeHolder: '请选择单位',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem14',
                            },
                            allowEmpty: true,
                            codeName: 'formitem14',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem14',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem15',
                            },
                            allowEmpty: true,
                            caption: '单位值',
                            codeName: 'formitem15',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem15',
                          },
                        ],
                        codeName: 'grouppanel17',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel17',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            editor: {
                              enablePickupView: true,
                              singleSelect: true,
                              enableAC: true,
                              forceSelection: true,
                              showTrigger: true,
                              valueItemName: 'formitem17',
                              editorParams: {
                                multiple: 'true',
                                url: '/sysorganizations/${selected-orgid}/sysemployees/picker',
                                filter: 'srforgid',
                                AC: 'TRUE',
                                PICKUPVIEW: 'TRUE',
                              },
                              editorStyle: 'EMPMULTIPLE',
                              editorType: 'PICKER',
                              editorItems: [
                                {
                                  id: 'formitem17',
                                },
                              ],
                              sysPFPluginId: 'personselect',
                              placeHolder: '请选择人员',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem16',
                            },
                            resetItemNames: ['formitem15'],
                            allowEmpty: true,
                            codeName: 'formitem16',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedDetailNames: ['formitem15'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'formitem15',
                                    logicType: 'SINGLE',
                                    name: 'formitem15值不为空(NotNil)',
                                    id: 'formitem15值不为空(notnil)',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'formitem16',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 56,
                            noPrivDisplayMode: 1,
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'formitem17',
                            },
                            resetItemNames: ['formitem15'],
                            allowEmpty: true,
                            caption: '人员值',
                            codeName: 'formitem17',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            defdgroupLogics: [
                              {
                                logicCat: 'ITEMENABLE',
                                relatedDetailNames: ['formitem15'],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'formitem15',
                                    logicType: 'SINGLE',
                                    name: 'formitem15值不为空(NotNil)',
                                    id: 'formitem15值不为空(notnil)',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'formitem17',
                          },
                        ],
                        codeName: 'grouppanel18',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          colSM: 12,
                          colXS: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel18',
                      },
                    ],
                    caption: '【多选】指定单位人员',
                    codeName: 'grouppanel14',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel14',
                  },
                ],
                caption: '人员选择',
                codeName: 'group4',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group4',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 260,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.MASTER.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '运行时组件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main67',
        controlType: 'FORM',
        logicName: '编辑器_运行时组件_表单',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'form',
        },
        modelId: '24fca17698f3a12334c703815d99df13',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'web.master.main67',
      },
      {
        xdataControlName: 'form',
        codeName: 'runtime_components_toolbar',
        controlType: 'TOOLBAR',
        logicName: '编辑器_运行时组件_工具栏',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '66a85d893820ff6fe1c24fa36dbbda5c',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'runtime_components_toolbar',
      },
      {
        codeName: 'runtime_components_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'web.master',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'runtime_components_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '编辑器_运行时组件',
        codeName: 'runtime_components_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'runtime_components_captionbar',
      },
    ],
    codeName: 'a6af108fc05f471a0b7',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'Runtime_Components编辑视图布局面板',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: '40b3e24f418b583ec1be865f98b87feb',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a6af108fc05f471a0b7',
  },
  title: '编辑器_运行时组件',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '55516cb6ca69f69e116aa7473ffec8a1',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERRuntime_Components',
  id: 'web.master_runtime_components',
};
