export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'actions_federation',
  deviewId: '3f4335ba376f74e223f303ac5e612a33',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '界面行为组融合示例',
  codeName: 'master_actions_federation',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'web.master_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'web.master_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '主数据数据重定向视图',
      refAppViewId: 'web.master_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          groupExtractMode: 'ITEM',
          uiactionGroup: {
            appDataEntityId: 'web.master',
            uniqueTag: 'master__toolbar_actions_federation',
            name: '界面行为组融合（工具栏）',
            id: 'toolbar_actions_federation',
          },
          valid: true,
          itemType: 'ITEMS',
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem3',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_editaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EDIT',
          },
          caption: '编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-edit',
            glyph: 'xf044@FontAwesome',
          },
          tooltip: '编辑',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EDIT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem4',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem6',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem7',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem8',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem9',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_exportaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EXPORT',
          },
          caption: '导出',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-excel-o',
            glyph: 'xf1c3@FontAwesome',
          },
          tooltip: '导出',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EXPORT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem13',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem10',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_printaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.PRINT',
          },
          caption: '打印',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-print',
            glyph: 'xf02f@FontAwesome',
          },
          tooltip: '打印',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.PRINT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem11',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem12',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem15',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              itemType: 'SEPERATOR',
              id: 'tbitem20',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_exportxmlaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'MENUITEM.CAPTION.*.EXPORTSRF',
              },
              caption: '导出数据模型',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-download',
                glyph: 'xf019@FontAwesome',
              },
              tooltip: '导出数据模型',
              showCaption: true,
              showIcon: true,
              id: 'tbitem21',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_importbar',
              valid: true,
              caption: '数据导入',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-upload',
                glyph: 'xf093@FontAwesome',
              },
              tooltip: '数据导入',
              showCaption: true,
              showIcon: true,
              id: 'tbitem23',
            },
          ],
          valid: true,
          caption: '其它',
          itemType: 'ITEMS',
          tooltip: '其它',
          showCaption: true,
          showIcon: true,
          id: 'tbitem16',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem17',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_searchbar',
          enableToggleMode: true,
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.FILTER',
          },
          caption: '过滤',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-filter',
            glyph: 'xf0b0@FontAwesome',
          },
          tooltip: '过滤',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.FILTER',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem19',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'actions_federation_toolbar',
      controlType: 'TOOLBAR',
      logicName: '表格工具栏带扩展区(通用)',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '6a258c5f1775ba8e4b9a3f56e6510dfc',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'actions_federation_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MASTER.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'update_man',
          excelCaption: '更新人',
          appCodeListId: 'web.sysoperator',
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeName: 'update_man',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_man',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'update_time',
          excelCaption: '更新时间',
          appDEFieldId: 'update_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          codeName: 'update_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'update_time',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.EDIT',
                },
                caption: '编辑',
                detailType: 'DEUIACTION',
                uiactionId: 'gridview_editaction',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.EDIT',
                },
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                id: 'u3189d93',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.VIEW',
                },
                caption: '查看',
                detailType: 'DEUIACTION',
                uiactionId: 'gridview_viewaction',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.VIEW',
                },
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                id: 'u62d21a1',
              },
            ],
            appDataEntityId: 'web.master',
            uniqueTag: 'master__grid_column_actions_federation',
            name: '界面行为组融合（表格列）',
            id: 'grid_column_actions_federation',
          },
          aggMode: 'NONE',
          align: 'RIGHT',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'update_man',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'update_man',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'update_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'update_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'region_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'region_id',
        },
        {
          appDEFieldId: 'category_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdatatype',
        },
        {
          appDEFieldId: 'category_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_type',
        },
        {
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'wf_status',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'wf_status',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      hasWFDataItems: true,
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'actions_federation_grid',
      controlType: 'GRID',
      logicName: '界面行为组融合示例_表格',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'grid',
      },
      modelId: '5c865e816fec0aa0197d09e444d7cc51',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.master.actions_federation_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'actions_federation_search_form',
      controlType: 'SEARCHFORM',
      logicName: '界面行为组融合示例_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '765ff0f82ae8d37b1441fdeaa211f3ca',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.actions_federation_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '界面行为组融合示例',
      codeName: 'actions_federation_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'actions_federation_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '界面行为组融合示例',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '01f2debbbd3b10e5bfe52a25eee50c85',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERactions_federation',
  id: 'web.master_actions_federation',
};
