export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'gantt',
  deviewId: '34f66865c7658bab652e2c718c079eec',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '甘特图',
  codeName: 'master_gantt',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_gantt_base',
          id: 'base',
        },
        {
          caption: '项布局面板',
          appViewId: 'web.master_gantt_layout',
          id: 'layout',
        },
        {
          caption: '上下文菜单',
          appViewId: 'web.master_gantt_contextmenu',
          id: 'limitsize',
        },
        {
          caption: '拖拽排序',
          appViewId: 'web.master_gantt_draggablesort',
          id: 'draggablesort',
        },
        {
          caption: '禁用滑块拖拽',
          appViewId: 'web.master_gantt_disabled_sliderdraggable',
          id: 'disabled_sliderdraggable',
        },
        {
          caption: '单元格编辑',
          appViewId: 'web.master_gantt_celledit',
          id: 'mustshowcolumns',
        },
        {
          caption: '启用列选择按钮',
          appViewId: 'web.master_gantt_enablecustomized',
          id: 'column_selection',
        },
        {
          caption: '刷新模式',
          appViewId: 'web.master_gantt_refreshmode',
          id: 'refreshmode',
        },
        {
          caption: '列界面行为组',
          appViewId: 'web.master_gantt_column_uiaction_group',
          id: 'column_uiaction_group',
        },
        {
          caption: '动态界面行为组',
          appViewId: 'web.master_gantt_column_dy_uiaction_group_exp',
          id: 'dy_uiaction_group',
        },
        {
          caption: '指定展开图标列',
          appViewId: 'web.master_gantt_column_expand_icon',
          id: 'column_expand_icon',
        },
        {
          caption: '事件及调用',
          appViewId: 'web.master_gantt_event_and_call',
          id: 'event_and_call',
        },
      ],
      dataRelationTag: 'gantt_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_gantt__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'gantt_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '30fe7a1965adbeda54af4a0831c3165a',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'gantt_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '甘特图',
      codeName: 'gantt_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '甘特图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '81083b0d654dc9e3a41360a5a8a49c87',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgantt',
  id: 'web.master_gantt',
};
