export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'upload_file_upload',
  deviewId: '31dc0707c17390d1130d394511fa4c4d',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_文件上传',
  codeName: 'master_upload_file_upload',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'upload_file_upload',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'upload_file_upload_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_文件上传_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '40aad0a03ea611e3e13a65ec58a0ec87',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'upload_file_upload_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformItemUpdates: [
        {
          codeName: 'fill_value2',
          defiupdateDetails: [
            {
              id: 'value2',
            },
          ],
          scriptCode:
            "return {value2: data.formitem1 != null ? data.formitem1 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value2',
        },
        {
          codeName: 'fill_value5',
          defiupdateDetails: [
            {
              id: 'value5',
            },
          ],
          scriptCode:
            "return {value5: data.formitem4 != null ? data.formitem4 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value5',
        },
        {
          codeName: 'fill_value',
          defiupdateDetails: [
            {
              id: 'value',
            },
          ],
          scriptCode:
            "return {value: data.formitem != null ? data.formitem : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value',
        },
        {
          codeName: 'fill_value6',
          defiupdateDetails: [
            {
              id: 'value6',
            },
          ],
          scriptCode:
            "return {value6: data.formitem5 != null ? data.formitem5 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value6',
        },
        {
          codeName: 'fill_value4',
          defiupdateDetails: [
            {
              id: 'value4',
            },
          ],
          scriptCode:
            "return {value4: data.formitem3 != null ? data.formitem3 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value4',
        },
        {
          codeName: 'fill_value8',
          defiupdateDetails: [
            {
              id: 'value8',
            },
          ],
          scriptCode:
            "return {value8: data.formitem7 != null ? data.formitem7 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value8',
        },
        {
          codeName: 'fill_value10',
          defiupdateDetails: [
            {
              id: 'value10',
            },
          ],
          scriptCode:
            "return {value10: data.formitem18 != null ? data.formitem18 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value10',
        },
        {
          codeName: 'fill_value21',
          defiupdateDetails: [
            {
              id: 'formitem21',
            },
          ],
          scriptCode:
            "return {formitem21: data.formitem20 != null ? data.formitem20 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value21',
        },
        {
          codeName: 'fill_value7',
          defiupdateDetails: [
            {
              id: 'value7',
            },
          ],
          scriptCode:
            "return {value7: data.formitem6 != null ? data.formitem6: ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value7',
        },
        {
          codeName: 'fill_value3',
          defiupdateDetails: [
            {
              id: 'value3',
            },
          ],
          scriptCode:
            "return {value3: data.formitem2 != null ? data.formitem2 : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value3',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value',
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '文件控件',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  defdgroupLogics: [
                    {
                      logicCat: 'SCRIPTCODE_CHANGE',
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          logicType: 'SINGLE',
                          id: ' util.message.info(data.formitem);',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value',
                },
              ],
              caption: '文件上传',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value2',
                  editor: {
                    editorParams: {
                      MAXFILECNT: '1',
                    },
                    editorType: 'FILEUPLOADER_ONE',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '文件控件（单项）',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value2',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value2',
                },
              ],
              caption: '文件控件（单项）',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              actionGroupExtractMode: 'ITEM',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '添加附件',
                    detailType: 'DEUIACTION',
                    uiactionId: 'add_attachments@master',
                    showCaption: true,
                    showIcon: true,
                    sysImage: {
                      cssClass: 'fa fa-plus',
                      glyph: 'xf067@FontAwesome',
                    },
                    id: 'ucd4510f',
                  },
                ],
                appDataEntityId: 'web.master',
                uniqueTag: 'master__Usr0102014691',
                name: '新建附件',
                id: 'usr0102014691',
              },
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  contentControl: {
                    aggMode: 'NONE',
                    columnEnableFilter: 2,
                    columnEnableLink: 2,
                    groupMode: 'NONE',
                    groupStyle: 'DEFAULT',
                    degridColumns: [
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'name',
                        excelCaption: '名称',
                        appDEFieldId: 'name',
                        deuiactionId: 'attachment_preview@attachment',
                        valueType: 'SIMPLE',
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '名称',
                        codeName: 'name',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 250,
                        widthUnit: 'STAR',
                        enableSort: true,
                        id: 'name',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'create_time',
                        excelCaption: '上传时间',
                        appDEFieldId: 'create_time',
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        valueType: 'SIMPLE',
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '上传时间',
                        codeName: 'create_time',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 200,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'create_time',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'owner_id',
                        excelCaption: '所属数据标识',
                        appDEFieldId: 'owner_id',
                        valueType: 'SIMPLE',
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '所属数据标识',
                        codeName: 'owner_id',
                        columnType: 'DEFGRIDCOLUMN',
                        hideMode: 1,
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        enableSort: true,
                        hideDefault: true,
                        id: 'owner_id',
                      },
                      {
                        deuiactionGroup: {
                          uiactionGroupDetails: [
                            {
                              actionLevel: 250,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              detailType: 'DEUIACTION',
                              uiactionId: 'download@attachment',
                              tooltip: '下载当前附件',
                              showIcon: true,
                              sysImage: {
                                cssClass: 'fa fa-download',
                                glyph: 'xf019@FontAwesome',
                              },
                              id: 'u3f91aed',
                            },
                            {
                              actionLevel: 100,
                              afterItemType: 'NONE',
                              beforeItemType: 'NONE',
                              buttonStyle: 'DEFAULT',
                              caption: '删除',
                              detailType: 'DEUIACTION',
                              uiactionId: 'delete@attachment',
                              tooltip: '删除',
                              showCaption: true,
                              showIcon: true,
                              sysImage: {
                                cssClass: 'fa fa-trash-o',
                                glyph: 'xf014@FontAwesome',
                              },
                              id: 'u9f7d084',
                            },
                          ],
                          appDataEntityId: 'web.attachment',
                          uniqueTag: 'attachment__Usr0103721999',
                          name: '附件表格操作列',
                          id: 'usr0103721999',
                        },
                        aggMode: 'NONE',
                        align: 'RIGHT',
                        caption: '操作',
                        codeName: 'uagridcolumn1',
                        columnType: 'UAGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        id: 'uagridcolumn1',
                      },
                    ],
                    degridDataItems: [
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'name',
                      },
                      {
                        format: 'YYYY-MM-DD HH:mm:ss',
                        appDEFieldId: 'create_time',
                        valueType: 'SIMPLE',
                        dataType: 5,
                        id: 'create_time',
                      },
                      {
                        appDEFieldId: 'owner_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'owner_id',
                      },
                      {
                        appDEFieldId: 'file_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'file_id',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfkey',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfdataaccaction',
                      },
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfmajortext',
                      },
                    ],
                    degridEditItems: [
                      {
                        caption: '标识',
                        codeName: 'srfkey',
                        enableCond: 3,
                        appDEFieldId: 'id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfkey',
                        },
                        allowEmpty: true,
                        id: 'srfkey',
                      },
                    ],
                    pagingSize: 20,
                    sortMode: 'REMOTE',
                    hasWFDataItems: true,
                    enableRowEdit: true,
                    enableRowNew: true,
                    singleSelect: true,
                    navViewPos: 'NONE',
                    createControlAction: {
                      appDEMethodId: 'create',
                      appDataEntityId: 'web.attachment',
                      id: 'create',
                    },
                    fetchControlAction: {
                      appDEMethodId: 'fetch_default',
                      appDataEntityId: 'web.attachment',
                      id: 'fetch',
                    },
                    getDraftControlAction: {
                      appDEMethodId: 'get_draft',
                      appDataEntityId: 'web.attachment',
                      id: 'loaddraft',
                    },
                    getControlAction: {
                      appDEMethodId: 'get',
                      appDataEntityId: 'web.attachment',
                      id: 'load',
                    },
                    removeControlAction: {
                      appDEMethodId: 'remove',
                      appDataEntityId: 'web.attachment',
                      id: 'remove',
                    },
                    updateControlAction: {
                      appDEMethodId: 'update',
                      appDataEntityId: 'web.attachment',
                      id: 'update',
                    },
                    autoLoad: true,
                    showBusyIndicator: true,
                    codeName: 'attach',
                    controlStyle: 'ATTACHMENT_GRID',
                    controlType: 'GRID',
                    logicName: '附件表格',
                    appDataEntityId: 'web.attachment',
                    controlLogics: [
                      {
                        eventNames: 'onLoadSuccess',
                        logicTag: 'attachments_grid',
                        logicType: 'APPDEUILOGIC',
                        appDEUILogicId: 'calc_attachment_hidden',
                        appDataEntityId: 'web.attachment',
                        triggerType: 'CTRLEVENT',
                        id: 'logic2',
                      },
                    ],
                    controlParam: {},
                    sysPFPluginId: 'attachment_grid',
                    modelId: '0a109435fff80754feb0da5154907b7a',
                    modelType: 'PSDEGRID',
                    name: 'attachments_grid',
                    id: 'web.attachment.attach',
                  },
                  contentType: 'GRID',
                  appDEFieldId: 'attachments',
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  codeName: 'attachments',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'attachments',
                },
              ],
              caption: '多数据部件',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['formitem'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'formitem',
                      value: '1',
                      logicType: 'SINGLE',
                      id: 'formitem等于(=) 1',
                    },
                  ],
                  logicType: 'GROUP',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value3',
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                      isdrag: 'true',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value3',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value3',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用isdrag参数控制编辑器是否可以拖拽上传。当前编辑器可以拖拽上传',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: '拖拽上传',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value4',
                  editor: {
                    editorParams: {
                      multiple: 'true',
                      FILEEXTS: '',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value4',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value4',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用multiple参数控制编辑器是否可以选择多个文件上传。当前编辑器可以选择多个文件上传',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
              ],
              caption: '多选',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value5',
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      accept: '.png, .jpg, .jpeg',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value5',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value5',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用accept参数指定编辑器可上传的文件类型。当前编辑器可上传的文件类型为png、jpg、jpeg',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
              ],
              caption: '上传文件类型',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value6',
                  editor: {
                    editorParams: {
                      uploadparams: '{"username":"%srfusername%"}',
                      FILEEXTS: '',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value6',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value6',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用uploadparams参数指定文件上传的参数，用于计算上传路径。当前编辑器文件上传的参数为{"username":"%srfusername%"}',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem4',
                  },
                  codeName: 'rawitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem4',
                },
              ],
              caption: '上传参数',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value7',
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      exportparams: '{"username":"%srfusername%"}',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem6',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value7',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value7',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用exportparams参数指定文件下载的参数，用于计算下载路径。当前编辑器文件下载的参数为{"username":"%srfusername%"}',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem5',
                  },
                  codeName: 'rawitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem5',
                },
              ],
              caption: '下载参数',
              codeName: 'grouppanel7',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel7',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value8',
                  editor: {
                    osscat: 'cat',
                    editorParams: {
                      FILEEXTS: '',
                      osscat: 'cat',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem7',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value8',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value8',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用osscat参数指定文件上传下载的OSS参数，用于计算上传路径和下载路径。当前编辑器文件上传下载的OSS参数为cat',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem6',
                  },
                  codeName: 'rawitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem6',
                },
              ],
              caption: 'OSS参数',
              codeName: 'grouppanel8',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel8',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value10',
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      infomap: 'filesize:size;fileext:ext',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem18',
                  },
                  allowEmpty: true,
                  codeName: 'formitem18',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem18',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value10',
                  },
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value10',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用infomap参数转换文件数据，用于在文件上传成功后，将返回的数据转换为保存数据所需格式。当前编辑器infomap参数为filesize:size;fileext:ext',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem8',
                  },
                  codeName: 'rawitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem8',
                },
              ],
              caption: 'infomap参数',
              codeName: 'grouppanel10',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel10',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV:
                    '[{"name":"welcome.svg","id":"31542be6d731d68490da21ec5ffcbc7c"}]',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      readonly: 'true',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem16',
                  },
                  updateDV:
                    '[{"name":"welcome.svg","id":"31542be6d731d68490da21ec5ffcbc7c"}]',
                  allowEmpty: true,
                  codeName: 'formitem16',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem16',
                },
                {
                  createDV:
                    '[{"name":"welcome.svg","id":"31542be6d731d68490da21ec5ffcbc7c"}]',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value9',
                  },
                  updateDV:
                    '[{"name":"welcome.svg","id":"31542be6d731d68490da21ec5ffcbc7c"}]',
                  allowEmpty: true,
                  caption: '当前值：',
                  codeName: 'value9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value9',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用readonly参数控制编辑器是否为只读态。当前编辑器为只读态',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem7',
                  },
                  codeName: 'rawitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem7',
                },
              ],
              caption: '只读态',
              codeName: 'grouppanel9',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel9',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value21',
                  editor: {
                    editorParams: {
                      FILEEXTS: '',
                      appentitytag: 'web.master',
                      datafieldtag: 'id',
                      MAXFILESIZE: '',
                      MINFILECNT: '',
                      MAXFILECNT: '',
                    },
                    editorType: 'FILEUPLOADER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem20',
                  },
                  allowEmpty: true,
                  codeName: 'formitem20',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem20',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem21',
                  },
                  allowEmpty: true,
                  caption: '当前值',
                  codeName: 'formitem21',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem21',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用appentitytag参数和datafieldtag参数约束编辑器在应用启用下载授权时手动指定当前文件所属实体及关联数据属性',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem9',
                  },
                  codeName: 'rawitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem9',
                },
              ],
              caption: '下载启用鉴权',
              codeName: 'grouppanel11',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel11',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '文件上传',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main52',
      controlType: 'FORM',
      logicName: '编辑器_文件上传_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '0ce6f432a3a12358d0a06bb3b459d9fa',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main52',
    },
    {
      codeName: 'upload_file_upload_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'upload_file_upload_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_文件上传',
      codeName: 'upload_file_upload_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'upload_file_upload_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_文件上传',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a76850044de5729bd9dbea86b21a65aa',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERupload_file_upload',
  id: 'web.master_upload_file_upload',
};
