export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'cardBaseDataViewExpView',
  deviewId: 'd36d88bf70cb5266ab03cb27c935e2d9',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片导航视图_基础',
  codeName: 'master_card_base_data_view_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataViewExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      sysImage: {
        cssClass: 'fa fa-cube',
        glyph: 'xf1b2@FontAwesome',
      },
      title: '卡片导航',
      xdataControlName: 'dataviewexpbar_dataview',
      enableCounter: true,
      enableSearch: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '导航栏导航编辑视图',
          refAppViewId: 'web.master_usr4409_edit_view',
          name: 'EXPITEM:DEFAULT',
          id: 'expitem:default',
        },
      ],
      controls: [
        {
          groupMode: 'NONE',
          groupStyle: 'DEFAULT',
          itemLayoutPanel: {
            layoutMode: 'TABLE_24COL',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      sysImage: {
                        rawContent:
                          '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                      },
                      contentType: 'IMAGE',
                      predefinedType: 'STATIC_IMAGE',
                      rawItemHeight: 48,
                      rawItemWidth: 48,
                      id: 'static_image',
                    },
                    caption: '图片',
                    contentHeight: 48,
                    contentWidth: 48,
                    height: 48,
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      height: 48,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      width: 48,
                      widthMode: 'PX',
                    },
                    sysImage: {
                      rawContent:
                        '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                    },
                    width: 48,
                    showCaption: true,
                    id: 'static_image',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'quantity',
                        },
                        viewFieldName: 'quantity',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'quantity',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.mock__cl_status',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'status',
                        },
                        viewFieldName: 'status',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'status',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERMEDIUM',
                    },
                    id: 'container1',
                  },
                ],
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'container',
              },
            ],
            layoutPanel: true,
            codeName: 'a5bb8e528c61a12c4da',
            controlType: 'PANEL',
            logicName: '卡片导航_缓存',
            appDataEntityId: 'web.master',
            controlParam: {},
            modelId: 'cf7bccc9874ed145333a3618f147782e',
            modelType: 'PSSYSVIEWPANEL',
            name: 'itemlayoutpanel',
            id: 'web.master.a5bb8e528c61a12c4da',
          },
          orderValueAppDEFieldId: 'px',
          dedataViewDataItems: [
            {
              appDEFieldId: 'id',
              dataType: 25,
              id: 'srfkey',
            },
            {
              appDEFieldId: 'name',
              dataType: 25,
              id: 'srfmajortext',
            },
          ],
          pagingMode: 1,
          pagingSize: 20,
          enablePagingBar: true,
          navAppViewId: 'web.master_usr4409_edit_view',
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.master',
            id: 'create',
          },
          fetchControlAction: {
            appDEMethodId: 'fetch_default',
            appDataEntityId: 'web.master',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.master',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'card_base_data_view_exp_view_data_view',
          controlType: 'DATAVIEW',
          logicName: '卡片导航视图_基础_卡片视图',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'dataviewexpbar_dataview',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'dataviewexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'dataviewexpbar_dataview',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'dataviewexpbar_load',
            },
          ],
          controlParam: {
            id: 'dataviewexpbar_dataview',
          },
          modelId: '9630fe2ed36c2c1f8ddd28b4ddd8f38e',
          modelType: 'PSDEDATAVIEW',
          name: 'dataviewexpbar_dataview',
          id: 'web.master.card_base_data_view_exp_view_data_view',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_refreshaction',
              valid: true,
              caption: '刷新',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-refresh',
                glyph: 'xf021@FontAwesome',
              },
              tooltip: '刷新',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
          ],
          codeName: 'card_base_data_view_exp_view_dataviewexpbar_toolbar',
          controlType: 'TOOLBAR',
          logicName: '卡片导航_工具栏',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'dataviewexpbar_toolbar',
          },
          modelId: 'a102d4ead58301bd23e74119c0ca772c',
          modelType: 'PSDETOOLBAR',
          name: 'dataviewexpbar_toolbar',
          id: 'card_base_data_view_exp_view_dataviewexpbar_toolbar',
        },
      ],
      codeName: 'card_base_data_view_exp_view_dataviewexpbar',
      controlType: 'DATAVIEWEXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataviewexpbar',
      },
      width: 750,
      modelId: '4949564a387e79edae8dc9ef2435eaec_dataviewexpbar',
      modelType: 'PSEXPBAR',
      name: 'dataviewexpbar',
      id: 'card_base_data_view_exp_view_dataviewexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片导航视图_基础',
      codeName: 'card_base_data_view_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_base_data_view_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEWEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片导航视图_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEWEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4949564a387e79edae8dc9ef2435eaec',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcardBaseDataViewExpView',
  id: 'web.master_card_base_data_view_exp_view',
};
