export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_group_action',
  deviewId: 'B2CCE1C1-1642-4153-A234-7BD0228226A7',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_分组界面行为',
  codeName: 'master_card_group_action',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupLayout: 'ROW',
      groupMode: 'CODELIST',
      groupAppDEFieldId: 'status',
      groupCodeListId: 'web.mock__cl_status',
      groupUIActionGroup: {
        uiactionGroupDetails: [
          {
            actionLevel: 200,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            caption: '打开关于',
            detailType: 'DEUIACTION',
            uiactionId: 'open_about@master',
            showCaption: true,
            showIcon: true,
            sysImage: {
              cssClass: 'fa fa-info-circle',
              glyph: 'xf05a@FontAwesome',
            },
            id: 'ub9b7b34',
          },
          {
            actionLevel: 50,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            caption: '打开文档',
            detailType: 'DEUIACTION',
            uiactionId: 'open_document@master',
            showCaption: true,
            showIcon: true,
            id: 'u888567e',
          },
          {
            actionLevel: 50,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            caption: '打开弹窗',
            detailType: 'DEUIACTION',
            uiactionId: 'open_dialog@master',
            showCaption: true,
            showIcon: true,
            id: 'u4be1ad5',
          },
          {
            actionLevel: 50,
            afterItemType: 'NONE',
            beforeItemType: 'NONE',
            buttonStyle: 'DEFAULT',
            detailType: 'DEUIACTIONGROUP',
            refUIActionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  capLanguageRes: {
                    lanResTag: 'TBB.TEXT.*.REMOVE',
                  },
                  caption: '删除',
                  detailType: 'DEUIACTION',
                  uiactionId: 'gridview_removeaction',
                  tooltipLanguageRes: {
                    lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                  },
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-remove',
                    glyph: 'xf00d@FontAwesome',
                  },
                  id: 'u6995654',
                },
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  capLanguageRes: {
                    lanResTag: 'TBB.TEXT.*.EDIT',
                  },
                  caption: '编辑',
                  detailType: 'DEUIACTION',
                  uiactionId: 'gridview_editaction',
                  tooltipLanguageRes: {
                    lanResTag: 'TBB.TOOLTIP.*.EDIT',
                  },
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'ued804e3',
                },
              ],
              id: '更多',
            },
            showCaption: true,
            showIcon: true,
            id: 'u292614b',
          },
        ],
        appDataEntityId: 'web.master',
        id: '分组界面行为组',
      },
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      enableGroup: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_group_action',
      controlType: 'DATAVIEW',
      logicName: '卡片_分组界面行为组',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: '9a51bc11a7f49721693b058060647c43',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_group_action',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_分组界面行为',
      codeName: 'card_group_action_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_group_action_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_分组界面行为',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '7904ee939a4a437cf94f0a56004ef8d8',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_group_action',
  id: 'web.master_card_group_action',
};
