export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'navparam_groupmode_exp',
  deviewId: 'c59935c9557c1755d9a5148e99ae0ade',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表_导航参数_分组模式导航视图',
  codeName: 'master_navparam_groupmode_exp',
  height: 500,
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      xdataControlName: 'chartexpbar_chart',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '表格视图',
          refAppViewId: 'web.master_grid_view_read',
          name: 'EXPITEM:bar',
          id: 'expitem:bar',
        },
      ],
      controls: [
        {
          chartCoordinateSystems: [
            {
              chartGrid: {
                chartGridXAxis0Id: '0',
                chartGridYAxis0Id: '0',
                chartCoordinateSystemId: '0',
                type: 'grid',
                name: '[bar_0]直角坐标系[0]',
                id: '0',
              },
              echartsType: 'cartesian2d',
              type: 'XY',
              name: '[bar_0]直角坐标系[0]',
              id: '0',
            },
          ],
          dechartDataGrid: {
            id: '0',
          },
          dechartLegend: {
            showLegend: true,
            id: '0',
          },
          dechartSerieses: [
            {
              catalogField: 'START_TIME',
              echartsType: 'bar',
              groupMode: 'MONTH',
              chartCoordinateSystemId: '0',
              chartDataSetId: '0',
              chartSeriesEncode: {
                chartXAxisId: '0',
                chartYAxisId: '0',
                x: ['START_TIME'],
                y: ['QUANTITY'],
                type: 'XY',
                name: '坐标系编码',
                id: '0',
              },
              seriesLayoutBy: 'column',
              seriesType: 'bar',
              valueField: 'QUANTITY',
              enableChartDataSet: true,
              navAppViewId: 'web.master_grid_view_read',
              navigateParams: [
                {
                  key: 'n_status_eq',
                  value: 'status',
                  id: 'n_status_eq',
                },
              ],
              id: 'bar_0',
            },
          ],
          dechartTitle: {
            title: '图表导航栏_导航参数_分组模式',
            id: '0',
          },
          chartDataSetGroups: [
            {
              appDEDataSetId: 'fetch_default',
              appDataEntityId: 'web.master',
              name: 'DEFAULT',
              id: '0',
            },
          ],
          chartDataSets: [
            {
              chartDataSetFields: [
                {
                  groupMode: 'MONTH',
                  groupField: true,
                  name: 'START_TIME',
                  id: '0',
                },
                {
                  index: 1,
                  name: 'QUANTITY',
                  id: '1',
                },
              ],
              name: 'bar_0-DEFAULT',
              id: '0',
            },
          ],
          chartGrids: [
            {
              chartGridXAxis0Id: '0',
              chartGridYAxis0Id: '0',
              chartCoordinateSystemId: '0',
              type: 'grid',
              name: '[bar_0]直角坐标系[0]',
              id: '0',
            },
          ],
          chartXAxises: [
            {
              echartsPos: 'xAxis',
              echartsType: 'category',
              position: 'bottom',
              type: 'category',
              name: 'axis_xAxis_1',
              id: '0',
            },
          ],
          chartYAxises: [
            {
              echartsPos: 'yAxis',
              echartsType: 'value',
              position: 'left',
              type: 'numeric',
              name: 'axis_yAxis_0',
              id: '0',
            },
          ],
          navViewPos: 'NONE',
          fetchControlAction: {
            appDEMethodId: 'fetch_default',
            appDataEntityId: 'web.master',
            id: 'fetch',
          },
          readOnly: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'chart_expbar_navparam_groupmode',
          controlType: 'CHART',
          logicName: 'Chart35',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'chartexpbar_chart',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'chartexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'chartexpbar_chart',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'chartexpbar_load',
            },
          ],
          controlParam: {
            id: 'chartexpbar_chart',
          },
          modelId: '95a4ceab72ce3beb5307d55e22ddc8e4',
          modelType: 'PSDECHART',
          name: 'chartexpbar_chart',
          id: 'web.master.chart_expbar_navparam_groupmode',
        },
      ],
      codeName: 'navparam_groupmode_exp_chartexpbar',
      controlType: 'CHARTEXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'chartexpbar',
      },
      modelId: '61248d4da1f0ce2eb20d59fdbae99077_chartexpbar',
      modelType: 'PSEXPBAR',
      name: 'chartexpbar',
      id: 'navparam_groupmode_exp_chartexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表_导航参数_分组模式导航视图',
      codeName: 'navparam_groupmode_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'navparam_groupmode_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表_导航参数_分组模式导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '61248d4da1f0ce2eb20d59fdbae99077',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERnavparam_groupmode_exp',
  id: 'web.master_navparam_groupmode_exp',
};
