export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'kanban_base_exp',
  deviewId: 'ee98f8e1913250011904e7ab4dcfe054',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '看板_常规导航视图',
  codeName: 'master_kanban_base_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础看板',
          appViewId: 'web.master_kanban_base',
          id: 'base',
        },
        {
          caption: '卡片新建',
          appViewId: 'web.master_kanban_card_new',
          id: 'card_new',
        },
        {
          caption: '项行为',
          appViewId: 'web.master_kanban_item_action',
          id: 'itemaction',
        },
        {
          caption: '泳道看板',
          appViewId: 'web.master_kanban_swimlane',
          id: 'swimlane',
        },
        {
          caption: '分页数量',
          appViewId: 'web.master_kanban_page',
          id: 'page',
        },
      ],
      dataRelationTag: 'DataRelation68',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_kanban_base_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation68',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'bd73d13dc5a424c33debdc7fc70d017a',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation68',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '看板_常规导航视图',
      codeName: 'kanban_base_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'kanban_base_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '看板_常规导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0ac7abf1d56b92e49a9fdae45f6fe7c6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERkanban_base_exp',
  id: 'web.master_kanban_base_exp',
};
