export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tabexppanel_base',
  deviewId: 'e356b19849ba0f9f8fbb8a75e1d8ec2c',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '分页导航面板_基础',
  codeName: 'master_tabexppanel_base',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      tabExpPageIds: ['region', 'category', 'master'],
      tabLayout: 'TOP',
      uniqueTag: 'master_tabexppanel_base__tabexppanel',
      appViewRefs: [
        {
          realTitle: '区划表格视图',
          refAppViewId: 'web.region_grid_view',
          name: 'EXPITEM:region',
          id: 'expitem:region',
        },
        {
          realTitle: '分类表格视图',
          refAppViewId: 'web.category_grid_view',
          name: 'EXPITEM:category',
          id: 'expitem:category',
        },
        {
          realTitle: '主数据表格视图',
          refAppViewId: 'web.master_main_grid',
          name: 'EXPITEM:master',
          id: 'expitem:master',
        },
      ],
      controls: [
        {
          caption: '区划',
          embeddedAppDEViewId: 'web.region_grid_view',
          codeName: 'tabexppanel_base_region',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'region',
          },
          modelId: '1d211828d27580525496c58f619ad6a5_region',
          modelType: 'PSVIEWPANEL',
          name: 'region',
          id: 'tabexppanel_base_region',
        },
        {
          caption: '分类',
          embeddedAppDEViewId: 'web.category_grid_view',
          codeName: 'tabexppanel_base_category',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'category',
          },
          modelId: '1d211828d27580525496c58f619ad6a5_category',
          modelType: 'PSVIEWPANEL',
          name: 'category',
          id: 'tabexppanel_base_category',
        },
        {
          caption: '主数据',
          embeddedAppDEViewId: 'web.master_main_grid',
          codeName: 'tabexppanel_base_master',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'master',
          },
          modelId: '1d211828d27580525496c58f619ad6a5_master',
          modelType: 'PSVIEWPANEL',
          name: 'master',
          id: 'tabexppanel_base_master',
        },
      ],
      codeName: 'tabexppanel_base_tabexppanel',
      controlType: 'TABEXPPANEL',
      appDataEntityId: 'web.master',
      controlParam: {},
      modelId: '1d211828d27580525496c58f619ad6a5_tabexppanel',
      modelType: 'PSTABEXPPANEL',
      name: 'tabexppanel',
      id: 'tabexppanel_base_tabexppanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '分页导航面板_基础',
      codeName: 'tabexppanel_base_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tabexppanel_base_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '分页导航面板_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1d211828d27580525496c58f619ad6a5',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtabexppanel_base',
  id: 'web.master_tabexppanel_base',
};
