export default {
  deviewCodeName: 'Pickup_gridpickupview',
  deviewId: 'c9dc2da426b575890ed17f541022d73b',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格数据选择视图',
  codeName: 'master_pickup_gridpickupview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onSelectionChange',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'pickupviewpanel',
      scriptCode:
        "const tips = '选择视图面板的选中数据变更事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips, `选中数据:`, data);",
      builtinLogic: true,
      id: 'logic',
    },
  ],
  appViewMsgGroupId: 'pickup_eventandcall',
  controls: [
    {
      codeName: 'pickup_gridpickupview_toolbar',
      controlType: 'TOOLBAR',
      logicName: '选择视图面板工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fa9213d29a94558349d0f4fd85a15a32',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'pickup_gridpickupview_toolbar',
    },
    {
      embeddedAppDEViewId: 'web.master_pickup_gridpickupview_pickup_grid_view',
      codeName: 'pickup_gridpickupview_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_gridpickupview_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格数据选择视图',
      codeName: 'pickup_gridpickupview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_gridpickupview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_表格数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'e691bacc2e2a2d36e99d8fe614d4fbfd',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_gridpickupview',
  id: 'web.master_pickup_gridpickupview',
};
