export default {
  deviewCodeName: 'Pickup_treepickupview2',
  deviewId: '3c4a1a0ac3147108cc6cc52a5ce140d3',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树数据选择视图（左右关系）',
  codeName: 'master_pickup_treepickupview2',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      eventNames: 'onSelectionChange',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'pickupviewpanel',
      scriptCode:
        "const tips = '选择视图面板的选中数据变更事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips, `选中数据:`, data);",
      builtinLogic: true,
      id: 'logic',
    },
  ],
  appViewMsgGroupId: 'pickup_eventandcall',
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'all',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-根节点（node）',
              id: '默认根节点（root）-根节点（node）',
            },
            {
              childDETreeNodeId: 'enable',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-正常（enable）',
              id: '默认根节点（root）-正常（enable）',
            },
            {
              childDETreeNodeId: 'disable',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              name: '默认根节点（ROOT）-停用（disable）',
              id: '默认根节点（root）-停用（disable）',
            },
          ],
          detreeNodes: [
            {
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '全部',
              nodeType: 'all',
              treeNodeType: 'STATIC',
              name: '全部',
              id: 'all',
            },
            {
              text: '停用',
              nodeType: 'disable',
              navigateParams: [
                {
                  key: 'n_status_eq',
                  value: '0',
                  rawValue: true,
                  id: 'n_status_eq',
                },
              ],
              treeNodeType: 'STATIC',
              name: '停用',
              id: 'disable',
            },
            {
              text: '正常',
              nodeType: 'enable',
              navigateParams: [
                {
                  key: 'n_status_eq',
                  value: '1',
                  rawValue: true,
                  id: 'n_status_eq',
                },
              ],
              treeNodeType: 'STATIC',
              name: '正常',
              id: 'enable',
            },
          ],
          outputIconDefault: true,
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.master',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'web.master',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.master',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.master',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.master',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'pickup_pickupview2_tree_view',
          controlType: 'TREEVIEW',
          logicName: '选择视图面板_数据选择视图（左右关系）_树视图',
          appDataEntityId: 'web.master',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          modelId: '1548d405c97707a8548330b7b7c76ad9',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'web.master.pickup_pickupview2_tree_view',
        },
      ],
      codeName: 'pickup_treepickupview2_treeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '988475cf3336944b3622b680556a108d_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'pickup_treepickupview2_treeexpbar',
    },
    {
      embeddedAppDEViewId: 'web.master_pickup_treepickupcontrolview',
      codeName: 'pickup_treepickupview2_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_treepickupview2_pickupviewpanel',
    },
    {
      codeName: 'pickup_treepickupview2_toolbar',
      controlType: 'TOOLBAR',
      logicName: '选择视图面板工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fa9213d29a94558349d0f4fd85a15a32',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'pickup_treepickupview2_toolbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树数据选择视图（左右关系）',
      codeName: 'pickup_treepickupview2_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_treepickupview2_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW2',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_树数据选择视图（左右关系）',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW2',
  enableDP: true,
  showCaptionBar: true,
  modelId: '988475cf3336944b3622b680556a108d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_treepickupview2',
  id: 'web.master_pickup_treepickupview2',
};
