export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tree_datasource_exp',
  deviewId: '9016dcf2ce836988106e972872f99993',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_数据源导航视图',
  codeName: 'master_tree_datasource_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '实体行为',
          appViewId: 'web.master_tree_deaction_datasource',
          id: 'deaction',
        },
        {
          caption: '实体集合',
          appViewId: 'web.master_tree_dedataset_datasource',
          id: 'dedataset',
        },
        {
          caption: '实体逻辑',
          appViewId: 'web.master_tree_delogic_datasource',
          id: 'delogic',
        },
        {
          caption: '父数据变量',
          appViewId: 'web.master_tree_parent_datasource',
          id: 'parentdata',
        },
        {
          caption: '应用全局变量',
          appViewId: 'web.master_tree_appgloable_datasource',
          id: 'appgloable',
        },
        {
          caption: '顶级视图会话变量',
          appViewId: 'web.master_tree_topsession_datasource',
          id: 'topsession',
        },
        {
          caption: '当前视图会话变量',
          appViewId: 'web.master_tree_cursession_datasource',
          id: 'cursession',
        },
        {
          caption: '自定义代码',
          appViewId: 'web.master_tree_custom_datasource',
          id: 'custom',
        },
      ],
      dataRelationTag: 'DataRelation127',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tree_datasource_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation127',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'd05891ace07e95d5d1e7b7ff676471e8',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation127',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_数据源导航视图',
      codeName: 'tree_datasource_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_datasource_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_数据源导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '742609444d386d56701faa8e1540c39f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtree_datasource_exp',
  id: 'web.master_tree_datasource_exp',
};
