export default {
  enableSearch: true,
  loadDefault: true,
  deviewCodeName: 'ChartGridView_Base',
  deviewId: 'dfc607b44b99506f37932879f8f8108a',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '图表数据表格_基础',
  codeName: 'master_chart_grid_view_base',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ChartView',
      id: 'engine',
    },
  ],
  controls: [
    {
      coordinateSystem: 'XY',
      chartCoordinateSystems: [
        {
          chartGrid: {
            chartGridXAxis0Id: '0',
            chartGridYAxis0Id: '0',
            chartCoordinateSystemId: '0',
            type: 'grid',
            name: '[bar_0]直角坐标系[0]',
            id: '0',
          },
          echartsType: 'cartesian2d',
          type: 'XY',
          name: '[bar_0]直角坐标系[0]',
          id: '0',
        },
      ],
      dechartDataGrid: {
        dataGridPos: 'BOTTOM',
        showDataGrid: true,
        id: '0',
      },
      dechartLegend: {
        id: '0',
      },
      dechartSerieses: [
        {
          caption: '柱状',
          catalogField: 'TYPE',
          echartsType: 'bar',
          chartCoordinateSystemId: '0',
          chartDataSetId: '0',
          chartSeriesEncode: {
            chartXAxisId: '0',
            chartYAxisId: '0',
            x: ['TYPE'],
            y: ['QUANTITY'],
            type: 'XY',
            name: '坐标系编码',
            id: '0',
          },
          seriesLayoutBy: 'column',
          seriesType: 'bar',
          valueField: 'QUANTITY',
          enableChartDataSet: true,
          id: 'bar_0',
        },
      ],
      dechartTitle: {
        title: '图表数据表格_基础_图表',
        id: '0',
      },
      chartDataSetGroups: [
        {
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.master',
          name: 'DEFAULT',
          id: '0',
        },
      ],
      chartDataSets: [
        {
          chartDataSetFields: [
            {
              groupField: true,
              name: 'TYPE',
              id: '0',
            },
            {
              index: 1,
              name: 'QUANTITY',
              id: '1',
            },
          ],
          name: 'bar_0-DEFAULT',
          id: '0',
        },
      ],
      chartGrids: [
        {
          chartGridXAxis0Id: '0',
          chartGridYAxis0Id: '0',
          chartCoordinateSystemId: '0',
          type: 'grid',
          name: '[bar_0]直角坐标系[0]',
          id: '0',
        },
      ],
      chartXAxises: [
        {
          echartsPos: 'xAxis',
          echartsType: 'category',
          position: 'bottom',
          type: 'category',
          name: 'axis_xAxis_0',
          id: '0',
        },
      ],
      chartYAxises: [
        {
          echartsPos: 'yAxis',
          echartsType: 'value',
          position: 'left',
          type: 'numeric',
          name: 'axis_yAxis_0',
          id: '0',
        },
      ],
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      readOnly: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_grid_view_base_chart',
      controlType: 'CHART',
      height: 400,
      logicName: 'Chart45',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'chart',
      },
      modelId: '003079761579c644d701e8cb136a9b2a',
      modelType: 'PSDECHART',
      name: 'chart',
      id: 'web.master.chart_grid_view_base_chart',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main195',
      controlType: 'SEARCHFORM',
      logicName: '图表数据表格_基础_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '4772c850c2f1d28ff3e3ae5113121a6f',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.main195',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '图表数据表格_基础',
      codeName: 'chart_grid_view_base_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_grid_view_base_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '图表数据表格_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ac16dedcade258b186a90a3a9dda0d4e',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERChartGridView_Base',
  id: 'web.master_chart_grid_view_base',
};
