export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'list_nav_exp',
  deviewId: '829dc183b06d74741f7a3ed4836a7d2b',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '列表_内置导航导航视图',
  codeName: 'master_list_nav_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '右侧内置导航',
          appViewId: 'web.master_list_nav_right',
          id: 'right',
        },
        {
          caption: '下方内置导航',
          appViewId: 'web.master_list_nav_bottom',
          id: 'bottom',
        },
        {
          caption: '行明细',
          appViewId: 'web.master_list_rowdetail_nav',
          id: 'rowdetail',
        },
      ],
      dataRelationTag: 'DataRelation58',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_list_nav_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation58',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '5a1a321b524894e235f86f67dda99f71',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation58',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '列表_内置导航导航视图',
      codeName: 'list_nav_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'list_nav_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表_内置导航导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'cb43ea46a194504dc98e8846bf12d803',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERlist_nav_exp',
  id: 'web.master_list_nav_exp',
};
