export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'ui_logic_tabexpview',
  deviewId: '72519507ca75920977bd1c75cb555675',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '界面逻辑',
  codeName: 'master_ui_logic_tabexpview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '逻辑变量',
          appViewId: 'web.master_ui_logic_params',
          id: 'params',
        },
        {
          caption: '逻辑节点',
          appViewId: 'web.master_ui_logic_nodetabexpview',
          id: 'node',
        },
        {
          caption: '逻辑连接',
          appViewId: 'web.master_ui_logic_link',
          id: 'link',
        },
      ],
      dataRelationTag: 'DataRelation114',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_ui_logic_tabexpview__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation114',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'd8668efc5b0ac7ba6e4337ffbe5c3f7e',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation114',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '界面逻辑',
      codeName: 'ui_logic_tabexpview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'ui_logic_tabexpview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '界面逻辑_分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4917af01dead111cb6be9e40caa48fd4',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERui_logic_tabexpview',
  id: 'web.master_ui_logic_tabexpview',
};
