export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'color_picker',
  deviewId: '89cedf7efeeed0ed165703cf7d9f61ed',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_颜色选择器',
  codeName: 'master_color_picker',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'color_picker',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'color_picker_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_颜色选择器_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '47d4300d5b2b775b26c1075c552cba79',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'color_picker_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '颜色选择器',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: '颜色选择器',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      multiple: 'true',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用multiple参数控制颜色选择器是否启用多选模式。当前颜色选择器已开启多选模式',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: '多选',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      multiple: 'true',
                      custom: 'true',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem2',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用custom参数控制颜色选择器是否开启自定义模式。当前颜色选择器已开启自定义模式',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
              ],
              caption: '自定义模式',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      multiple: 'true',
                      defaultval: '["#409EFF","#67C23A","#E6A23C"]',
                      custom: 'true',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用defaultval参数指定颜色选择器自定义模式下默认呈现的颜色数组。当前颜色选择器自定义模式下默认呈现的颜色数组为["#409EFF","#67C23A","#E6A23C"]',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
              ],
              caption: '默认颜色数组',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      multiple: 'true',
                      type: 'ITEM',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用type参数指定颜色选择器颜色数组的类型，可选值有ITEM和ITEMS，当值为ITEM时，表示下拉选择的颜色数组仅有一个颜色；当值为ITEMS时，表示下拉选择的颜色数组包含多个颜色。当前颜色选择器颜色数组的类型为ITEM',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem4',
                  },
                  codeName: 'rawitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem4',
                },
              ],
              caption: '颜色数组类型',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      ishiddentext: 'true',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用ishiddentext参数控制是否隐藏颜色选择器中的颜色文本。当前颜色选择器已隐藏颜色文本',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem5',
                  },
                  codeName: 'rawitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem5',
                },
              ],
              caption: '颜色文本显示状态',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      multiple: 'true',
                      customcolorlist:
                        '[{"text":"蓝色","value":["#409EFF","#337ecc"]},{"text":"绿色","value":["#67C23A","#529b2e"]}]',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem6',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用customcolorlist参数控制颜色选择器自定义模式下显示的颜色列表。当前颜色选择器自定义模式下显示的颜色列表为[{"text":"蓝色","value":["#409EFF","#337ecc"]},{"text":"绿色","value":["#67C23A","#529b2e"]}]',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem6',
                  },
                  codeName: 'rawitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem6',
                },
              ],
              caption: '自定义颜色列表',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: 'rgba(24, 160, 251, 1)',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    editorParams: {
                      readonly: 'true',
                    },
                    editorType: 'COLORPICKER',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem7',
                  },
                  updateDV: 'rgba(24, 160, 251, 1)',
                  allowEmpty: true,
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem7',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用readonly参数控制编辑器是否为只读态。当前编辑器为只读态',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem7',
                  },
                  codeName: 'rawitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem7',
                },
              ],
              caption: '只读态',
              codeName: 'grouppanel7',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel7',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '颜色选择器',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main49',
      controlType: 'FORM',
      logicName: '编辑器_颜色选择器_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '01e061a11e618f51682752a7373bed77',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main49',
    },
    {
      codeName: 'color_picker_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'color_picker_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_颜色选择器',
      codeName: 'color_picker_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'color_picker_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_颜色选择器',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'dab04202b104f469ed54eef607efaca2',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcolor_picker',
  id: 'web.master_color_picker',
};
