export default {
  mdctrlActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'Tree_selectpickup',
  deviewId: '899df3ad7152724628d1668e6313ba4e',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树选择',
  codeName: 'master_tree_selectpickup',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupTreeView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-主数据（node）',
          id: '默认根节点（root）-主数据（node）',
        },
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '主数据（node）-名称（node_1）',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          text: '主数据',
          nodeType: 'node',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          name: '主数据',
          id: 'node',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node_1',
          appDataEntityId: 'web.master',
          treeNodeType: 'DE',
          name: '名称',
          id: 'node_1',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'tree_selectpickup_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树选择下拉_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: 'a076419e40832a7e7670951129749892',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_selectpickup_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树选择',
      codeName: 'tree_selectpickup_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_selectpickup_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPTREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树选择',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPTREEVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '99b19d96e6311ba5d0cfe0e09c720f1f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_selectpickup',
  id: 'web.master_tree_selectpickup',
};
