export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_multiple_data_user',
  deviewId: 'f2321a398fbebbe71f1d415b5185e9b1',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_多数据源_用户自定义',
  codeName: 'master_calendar_multiple_data_user',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      id: 'editdata@master',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      id: 'editdata@region',
    },
  ],
  controls: [
    {
      calendarStyle: 'USER',
      groupMode: 'NONE',
      legendPos: 'TOP',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          endTimeAppDEFieldId: 'end_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.master',
          name: '主数据',
          id: 'master',
        },
        {
          beginTimeAppDEFieldId: 'create_time',
          endTimeAppDEFieldId: 'update_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'region',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.region',
          name: '区划数据',
          id: 'region',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_multiple_data_user',
      controlType: 'CALENDAR',
      height: 650,
      logicName: '日历_多数据源_用户自定义',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'calendar',
      },
      modelId: '5815b51312d0f1cdf6b16691ed43f8b1',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.master.calendar_multiple_data_user',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_多数据源_用户自定义',
      codeName: 'calendar_multiple_data_user_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_multiple_data_user_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_多数据源_用户自定义',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9ae21f2a626114079215a1e570177c3c',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_multiple_data_user',
  id: 'web.master_calendar_multiple_data_user',
};
