export default {
  tabLayout: 'TOP_DROPDOWNLIST',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'drtab_dropdown',
  deviewId: 'd975335158b672638736bb79ebc0f9fb',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '数据关系分页_下拉',
  codeName: 'master_drtab_dropdown',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '区划',
          appViewId: 'web.region_grid_view',
          id: 'region',
        },
        {
          caption: '分类',
          appViewId: 'web.category_grid_view',
          id: 'category',
        },
        {
          caption: '主数据',
          appViewId: 'web.master_main_grid',
          id: 'master',
        },
      ],
      dataRelationTag: 'Drtab1',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '基本信息',
      uniqueTag: 'master_drtab_dropdown__tabexppanel',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'drtab1',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'd4454b8e0d09c198610f29e7521edbbe',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'drtab1',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '数据关系分页_下拉',
      codeName: 'drtab_dropdown_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'drtab_dropdown_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据关系分页_下拉',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '0d02bdf01b5ea1d425c06d4cf2e942e6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdrtab_dropdown',
  id: 'web.master_drtab_dropdown',
};
