export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendarCacheTabExpView',
  deviewId: '9CAD275E-DD6A-4E80-9C18-5A109D26332D',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历导航栏_缓存分页',
  codeName: 'master_calendar_cache_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'calendarexpbar_cache',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '启用缓存',
          appViewId: 'web.master_calendar_exp_view_cache',
          id: 'cache',
        },
        {
          caption: '不启用缓存',
          appViewId: 'web.master_calendar_exp_view_no_cache',
          id: 'no_cache',
        },
      ],
      dataRelationTag: 'calendarCacheTabExpView_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar_cache_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_cache_tab_exp_view_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '7BD8AFB9-9E96-4B88-B879-0154EC4C3C6E',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'calendar_cache_tab_exp_view_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历导航栏_缓存分页',
      codeName: 'calendar_cache_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_cache_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历导航栏_缓存分页',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '297c1e1ca53af28e52391bba163610d3',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendarCacheTabExpView',
  id: 'web.master_calendar_cache_tab_exp_view',
};
