export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'data_picker_select_view',
  deviewId: '47d53e87ad27233fa29adb71eef905c6',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_数据选择（下拉视图）',
  codeName: 'master_data_picker_select_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'data_picker_select_view',
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'data_picker_select_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_数据选择（下拉视图）_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '5f5d447a4885c8275c5c24944635ebd6',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'data_picker_select_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformItemUpdates: [
        {
          codeName: 'fill_value',
          defiupdateDetails: [
            {
              id: 'value',
            },
          ],
          scriptCode:
            "return {value: data.formitem11 != null ? JSON.stringify(data.formitem11) : ''}",
          customCode: true,
          showBusyIndicator: true,
          id: 'fill_value',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem2',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      pickupViewHeight: '500',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem2',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem2',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view2',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem27',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem27',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem26',
                  },
                  allowEmpty: true,
                  codeName: 'formitem26',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem26',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem27',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem27',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem27',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_grid_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem17',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem17',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem14',
                  },
                  allowEmpty: true,
                  codeName: 'formitem14',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem14',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem17',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem17',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem17',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_data_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem18',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem18',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem15',
                  },
                  allowEmpty: true,
                  codeName: 'formitem15',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem15',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem18',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem18',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem18',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_tree_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem19',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem19',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem16',
                  },
                  allowEmpty: true,
                  codeName: 'formitem16',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem16',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem19',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem19',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem19',
                },
              ],
              caption: '数据选择（下拉视图）',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_m_pickup_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem6',
                    editorParams: {
                      multiple: 'true',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem6',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem6',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_m_pickup_view2',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem29',
                    editorParams: {
                      multiple: 'true',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem29',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem28',
                  },
                  allowEmpty: true,
                  codeName: 'formitem28',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem28',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem29',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem29',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem29',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_grid_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem23',
                    editorParams: {
                      multiple: 'true',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem23',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem20',
                  },
                  allowEmpty: true,
                  codeName: 'formitem20',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem20',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem23',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem23',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem23',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_data_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem24',
                    editorParams: {
                      multiple: 'true',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem24',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem21',
                  },
                  allowEmpty: true,
                  codeName: 'formitem21',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem21',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem24',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem24',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem24',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_tree_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem25',
                    editorParams: {
                      multiple: 'true',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem25',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem22',
                  },
                  allowEmpty: true,
                  codeName: 'formitem22',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem22',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem25',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem25',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem25',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用multiple参数控制数据选择（下拉视图）是否可以多选。当前数据选择（下拉视图）可以多选',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colLG: 24,
                    colMD: 24,
                    colSM: 24,
                    colXS: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: '多选',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    linkAppViewId: 'web.region_info_view',
                    dropDownView: true,
                    enableLinkView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem3',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      LINKVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW_LINK',
                    editorItems: [
                      {
                        id: 'formitem3',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem3',
                },
              ],
              caption: '数据选择（下拉视图、数据链接）',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem7',
                    editorParams: {
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      pickupviewheight: '600',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem7',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem7',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用pickupviewheight参数指定下拉视图的高度。当前下拉视图的高度为600px',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
              ],
              caption: '下拉视图高度',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem9',
                    editorParams: {
                      valuetype: 'OBJECT',
                      objectvaluefield: 'value',
                      objectnamefield: 'name',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      objectidfield: 'id',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    objectIdField: 'id',
                    objectNameField: 'name',
                    objectValueField: 'value',
                    editorItems: [
                      {
                        id: 'formitem9',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'OBJECT',
                    editable: true,
                    id: 'formitem8',
                  },
                  allowEmpty: true,
                  codeName: 'formitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem8',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem9',
                  },
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem9',
                },
                {
                  rawItem: {
                    caption:
                      '说明：可使用valuetype指定编辑器值类型，值类型为OBJECT时，可使用objectidfield、objectnamefield、objectvaluefield参数分别指定对象的标识属性、名称属性、值属性。当前数据选择（下拉视图）值类型类型为OBJECT，对象的标识属性、名称属性、值属性分别为id、name、value',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
              ],
              caption: '值类型为OBJECT',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'fill_value',
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_grid_view',
                    forceSelection: true,
                    showTrigger: true,
                    editorParams: {
                      objectidfield: 'id',
                      objectvaluefield: 'value',
                      objectnamefield: 'name',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                      DROPDOWNVIEW: 'TRUE',
                      valuetype: 'OBJECTS',
                      multiple: 'true',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    objectIdField: 'id',
                    objectNameField: 'name',
                    objectValueField: 'value',
                    placeHolder: '请选择',
                    valueType: 'OBJECTS',
                    editable: true,
                    id: 'formitem11',
                  },
                  allowEmpty: true,
                  codeName: 'formitem11',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem11',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'value',
                  },
                  allowEmpty: true,
                  caption: '选取值：',
                  codeName: 'value',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'value',
                },
                {
                  rawItem: {
                    caption:
                      '说明：可使用valuetype指定编辑器值类型，值类型为OBJECTS时，可使用objectidfield、objectnamefield、objectvaluefield参数分别指定对象的标识属性、名称属性、值属性。当前数据选择（下拉视图）值类型为OBJECTS，对象的标识属性、名称属性、值属性分别为id、name、value',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem4',
                  },
                  codeName: 'rawitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem4',
                },
              ],
              caption: '值类型为OBJECTS',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '四川省',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    dropDownView: true,
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'web.region_pickup_grid_view',
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'formitem12',
                    editorParams: {
                      readonly: 'true',
                      DROPDOWNVIEW: 'TRUE',
                      AC: 'FALSE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKEREX_DROPDOWNVIEW',
                    editorItems: [
                      {
                        id: 'formitem12',
                      },
                    ],
                    placeHolder: '请选择',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem10',
                  },
                  updateDV: '四川省',
                  allowEmpty: true,
                  codeName: 'formitem10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem10',
                },
                {
                  createDV: '510000',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'WRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem12',
                  },
                  updateDV: '510000',
                  allowEmpty: true,
                  caption: '选取值项：',
                  codeName: 'formitem12',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem12',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用readonly参数控制编辑器是否为只读态。当前编辑器为只读态',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem5',
                  },
                  codeName: 'rawitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem5',
                },
              ],
              caption: '只读态',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '数据选择（下拉视图）',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main47',
      controlType: 'FORM',
      logicName: '编辑器_数据选择（下拉视图）_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: 'b6027e1616aebb35c40a12c03ecf3252',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main47',
    },
    {
      codeName: 'data_picker_select_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'data_picker_select_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_数据选择（下拉视图）',
      codeName: 'data_picker_select_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'data_picker_select_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_数据选择（下拉视图）',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '37acb087c08db79f9586a410e19b0b40',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdata_picker_select_view',
  id: 'web.master_data_picker_select_view',
};
