export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'gantt',
  loadDefault: true,
  deviewCodeName: 'gantt_draggablesort',
  deviewId: '80719e37e64a47942f329a69229db8d1',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '甘特图_拖拽排序',
  codeName: 'master_gantt_draggablesort',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'gantt_draggablesort',
  controls: [
    {
      beginDataItemName: 'begin',
      endDataItemName: 'end',
      finishDataItemName: 'finish',
      prevDataItemName: 'prev',
      sndataItemName: 'sn',
      totalDataItemName: 'total',
      detreeColumns: [
        {
          caption: '编号',
          codeName: 'sn',
          columnType: 'DEFGRIDCOLUMN',
          width: 120,
          widthUnit: 'px',
          id: 'sn',
        },
        {
          caption: '标题',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'name',
        },
        {
          caption: '开始时间',
          codeName: 'begin',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'begin',
        },
        {
          caption: '结束时间',
          codeName: 'end',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'end',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          moveAppDEActionId: 'move',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.master',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_time',
              appDEFieldId: 'end_time',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              codeName: 'end_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'id',
              appDEFieldId: 'id',
              valueType: 'SIMPLE',
              codeName: 'id',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'sn',
              id: 'id',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_time',
              appDEFieldId: 'start_time',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              codeName: 'start_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_time',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_time',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              format: 'YYYY-MM-DD',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'id',
              detreeColumnId: 'sn',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'id',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_time',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              format: 'YYYY-MM-DD',
              id: 'start_time',
            },
          ],
          treeNodeType: 'DE',
          allowDrag: true,
          allowDrop: true,
          allowOrder: true,
          name: '主数据',
          id: 'node',
        },
      ],
      treeGridMode: 2,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'gantt_draggablesort_gantt',
      controlType: 'GANTT',
      height: 510,
      logicName: '甘特图_拖拽排序_甘特部件',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'gantt',
      },
      modelId: 'b5e20ed30da2b73ca2ae89f5ec681f47',
      modelType: 'PSDEGANTT',
      name: 'gantt',
      id: 'web.master.gantt_draggablesort_gantt',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '甘特图_拖拽排序',
      codeName: 'gantt_draggablesort_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_draggablesort_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGANTTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '甘特图_拖拽排序',
  viewStyle: 'DEFAULT',
  viewType: 'DEGANTTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '477d2010d676544f5f3fe25d5c6fa3b7',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgantt_draggablesort',
  id: 'web.master_gantt_draggablesort',
};
