export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'Tree_eventcall',
  deviewId: '312d48ee9df0d2dbcd629a5a418b00b0',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_事件及调用',
  codeName: 'master_tree_eventcall',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '树部件事件',
          appViewId: 'web.master_tree_event',
          id: 'tree_event',
        },
        {
          caption: '树部件能力',
          appViewId: 'web.master_tree_call',
          id: 'tree_call',
        },
      ],
      dataRelationTag: 'DataRelation79',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tree_eventcall__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation79',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'c4717a1efbaf64d7b774eb1ef73e46d6',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation79',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_事件及调用',
      codeName: 'tree_eventcall_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_eventcall_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_事件及调用',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'feed006e9ed870a3a9696abbb93e1618',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERTree_eventcall',
  id: 'web.master_tree_eventcall',
};
