export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'gantt',
  loadDefault: true,
  deviewCodeName: 'gantt_column_expand_icon',
  deviewId: 'e4e6ae59691ad7776fedb45438b3a926',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '甘特图_指定展开图标列',
  codeName: 'master_gantt_column_expand_icon',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'vmgroup65',
  controls: [
    {
      beginDataItemName: 'begin',
      endDataItemName: 'end',
      finishDataItemName: 'finish',
      prevDataItemName: 'prev',
      sndataItemName: 'sn',
      totalDataItemName: 'total',
      detreeColumns: [
        {
          caption: '编号',
          codeName: 'sn',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'STAR',
          id: 'sn',
        },
        {
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'PX',
          id: 'name',
        },
        {
          caption: '开始时间',
          codeName: 'begin',
          columnType: 'DEFGRIDCOLUMN',
          width: 180,
          widthUnit: 'px',
          id: 'begin',
        },
        {
          caption: '结束时间',
          codeName: 'end',
          columnType: 'DEFGRIDCOLUMN',
          width: 180,
          widthUnit: 'px',
          id: 'end',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: '区域数据（node）-区域数据（node）',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          name: '默认根节点（ROOT）-区域数据（node）',
          id: '默认根节点（root）-区域数据（node）',
        },
      ],
      detreeNodes: [
        {
          nodeValue: '86',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.region',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_time',
              appDEFieldId: 'end_time',
              valueFormat: 'YYYY-MM-DD HH:mm:ss',
              valueType: 'SIMPLE',
              codeName: 'end_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'sort',
              appDEFieldId: 'sort',
              valueType: 'SIMPLE',
              codeName: 'sort',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'sn',
              id: 'sort',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_time',
              appDEFieldId: 'start_time',
              valueFormat: 'YYYY-MM-DD HH:mm:ss',
              valueType: 'SIMPLE',
              codeName: 'start_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_time',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_time',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'sort',
              detreeColumnId: 'sn',
              valueType: 'SIMPLE',
              dataType: 9,
              id: 'sort',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_time',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              id: 'start_time',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          name: '区域数据',
          id: 'node',
        },
      ],
      treeGridMode: 2,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'gantt_column_expand_icon',
      controlType: 'GANTT',
      height: 510,
      logicName: '甘特图_指定展开图标列',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          EXPANDICONCOLUMN: 'name',
        },
        id: 'gantt',
      },
      modelId: '85f341092567ff2fe725766433f26c28',
      modelType: 'PSDEGANTT',
      name: 'gantt',
      id: 'web.master.gantt_column_expand_icon',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '甘特图_指定展开图标列',
      codeName: 'gantt_column_expand_icon_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_column_expand_icon_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGANTTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '甘特图_指定展开图标列',
  viewStyle: 'DEFAULT',
  viewType: 'DEGANTTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5ff5195718f848ff4d3d68428b91416b',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgantt_column_expand_icon',
  id: 'web.master_gantt_column_expand_icon',
};
