export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'gantt',
  loadDefault: true,
  deviewCodeName: 'gantt_logic_event',
  deviewId: 'd1c5f50fac7c163171e81d29fec63708',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '甘特图_事件及调用_事件',
  codeName: 'master_gantt_logic_event',
  appDataEntityId: 'web.master',
  appViewMsgGroupId: 'gantt_event',
  controls: [
    {
      beginDataItemName: 'begin',
      endDataItemName: 'end',
      finishDataItemName: 'finish',
      prevDataItemName: 'prev',
      sndataItemName: 'sn',
      totalDataItemName: 'total',
      detreeColumns: [
        {
          caption: '编号',
          codeName: 'sn',
          columnType: 'DEFGRIDCOLUMN',
          width: 120,
          widthUnit: 'px',
          id: 'sn',
        },
        {
          caption: '标题',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'name',
        },
        {
          caption: '开始时间',
          codeName: 'begin',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'begin',
        },
        {
          caption: '结束时间',
          codeName: 'end',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'end',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          enableQuickSearch: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.master',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'end_time',
              appDEFieldId: 'end_time',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              codeName: 'end_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'end',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'id',
              appDEFieldId: 'id',
              valueType: 'SIMPLE',
              codeName: 'id',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'sn',
              id: 'id',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'start_time',
              appDEFieldId: 'start_time',
              valueFormat: 'YYYY-MM-DD',
              valueType: 'SIMPLE',
              codeName: 'start_time',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'begin',
              id: 'start_time',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'end_time',
              detreeColumnId: 'end',
              valueType: 'SIMPLE',
              dataType: 5,
              format: 'YYYY-MM-DD',
              id: 'end_time',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'id',
              detreeColumnId: 'sn',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'id',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'start_time',
              detreeColumnId: 'begin',
              valueType: 'SIMPLE',
              dataType: 5,
              format: 'YYYY-MM-DD',
              id: 'start_time',
            },
          ],
          treeNodeType: 'DE',
          enableQuickSearch: true,
          name: '主数据',
          id: 'node',
        },
      ],
      treeGridMode: 2,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'gantt_logic_event',
      controlType: 'GANTT',
      height: 510,
      logicName: '甘特图_事件及调用_事件',
      appDataEntityId: 'web.master',
      controlLogics: [
        {
          eventNames: 'onSelectionChange',
          logicTag: 'gantt',
          logicType: 'SCRIPT',
          scriptCode:
            "const tips = '甘特图数据选中事件触发';\r\nibiz.message.info(tips);\r\nconsole.log(tips, `甘特图数据选中事件触发`, data);",
          triggerType: 'CTRLEVENT',
          id: 'logic_selectionchange',
        },
        {
          eventNames: 'onLoadSuccess',
          logicTag: 'gantt',
          logicType: 'SCRIPT',
          scriptCode: "console.log('甘特图数据加载成功事件触发');",
          triggerType: 'CTRLEVENT',
          id: 'logic_load_success',
        },
      ],
      controlParam: {
        id: 'gantt',
      },
      modelId: '9619144f40ec889acdac891d264c0853',
      modelType: 'PSDEGANTT',
      name: 'gantt',
      id: 'web.master.gantt_logic_event',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      codeName: 'tab_search_bar',
      controlType: 'SEARCHBAR',
      logicName: '选项卡搜索栏',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          TELEPORTFLAG: 'true',
        },
        id: 'tabsearchbar',
      },
      modelId: '7d96aeb25c21d55beb1d5861df28bf80',
      modelType: 'PSSYSSEARCHBAR',
      name: 'tabsearchbar',
      id: 'web.master.tab_search_bar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '甘特图_事件及调用_事件',
      codeName: 'gantt_logic_event_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'gantt_logic_event_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGANTTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '甘特图_事件及调用_事件',
  viewStyle: 'DEFAULT',
  viewType: 'DEGANTTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'bdc1bf3d9c40773f3ff30dacafa8d1f2',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgantt_logic_event',
  id: 'web.master_gantt_logic_event',
};
