export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_logic',
  deviewId: '32f2b6cf2e5ad052280d358cfc892d7c',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片调用基础',
  codeName: 'master_card_logic',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'event_and_call',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main82',
      controlType: 'SEARCHFORM',
      logicName: '卡片_事件及调用_搜索表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchform',
      },
      modelId: '8b8c25cb35f7fab892b0ea6ae8c22c25',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.master.main82',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'single_data_key@master',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '单选数据（主键）',
          itemType: 'DEUIACTION',
          tooltip: '单选数据（主键）',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'single_data@master',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '单项数据',
          itemType: 'DEUIACTION',
          tooltip: '单项数据',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'specify_view_parameters@master',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '指定视图参数',
          itemType: 'DEUIACTION',
          tooltip: '指定视图参数',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction3',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'select_data@master',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '输出选择数据',
          itemType: 'DEUIACTION',
          tooltip: '输出选择数据',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction4',
        },
      ],
      xdataControlName: 'dataview',
      codeName: 'card_logic_toolbar',
      controlType: 'TOOLBAR',
      logicName: '卡片_事件及调用_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '8f6726f1a11304c86971fbf8442c5145',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'card_logic_toolbar',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'FLEX',
        layout: {
          layout: 'FLEX',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      sysImage: {
                        rawContent:
                          '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                      },
                      contentType: 'IMAGE',
                      predefinedType: 'STATIC_IMAGE',
                      rawItemHeight: 48,
                      rawItemWidth: 48,
                      id: 'static_image',
                    },
                    caption: '图片',
                    contentHeight: 48,
                    contentWidth: 48,
                    height: 48,
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      height: 48,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      width: 48,
                      widthMode: 'PX',
                    },
                    sysImage: {
                      rawContent:
                        '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                    },
                    width: 48,
                    showCaption: true,
                    id: 'static_image',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            viewFieldName: 'name',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingRight: 'OUTERLARGE',
                            },
                            id: 'name',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'quantity',
                            },
                            viewFieldName: 'quantity',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'quantity',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              appCodeListId: 'web.mock__cl_status',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'status',
                            },
                            viewFieldName: 'status',
                            allowEmpty: true,
                            convertToCodeItemText: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERLARGE',
                            },
                            id: 'status',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container3',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            buttonListType: 'UIACTIONGROUP',
                            uiactionGroup: {
                              uiactionGroupDetails: [
                                {
                                  actionLevel: 100,
                                  afterItemType: 'NONE',
                                  beforeItemType: 'NONE',
                                  buttonStyle: 'DEFAULT',
                                  caption: '单选数据（主键）',
                                  detailType: 'DEUIACTION',
                                  uiactionId: 'single_data_key@master',
                                  showCaption: true,
                                  showIcon: true,
                                  id: 'u150e91a',
                                },
                                {
                                  actionLevel: 100,
                                  afterItemType: 'NONE',
                                  beforeItemType: 'NONE',
                                  buttonStyle: 'DEFAULT',
                                  caption: '单项数据',
                                  detailType: 'DEUIACTION',
                                  uiactionId: 'single_data@master',
                                  showCaption: true,
                                  showIcon: true,
                                  id: 'u1f51398',
                                },
                                {
                                  actionLevel: 100,
                                  afterItemType: 'NONE',
                                  beforeItemType: 'NONE',
                                  buttonStyle: 'DEFAULT',
                                  caption: '指定视图参数',
                                  detailType: 'DEUIACTION',
                                  uiactionId: 'specify_view_parameters@master',
                                  showCaption: true,
                                  showIcon: true,
                                  id: 'u76b11c3',
                                },
                                {
                                  actionLevel: 100,
                                  afterItemType: 'NONE',
                                  beforeItemType: 'NONE',
                                  buttonStyle: 'DEFAULT',
                                  caption: '输出选择数据',
                                  detailType: 'DEUIACTION',
                                  uiactionId: 'select_data@master',
                                  showCaption: true,
                                  showIcon: true,
                                  id: 'u22e5b13',
                                },
                              ],
                              appDataEntityId: 'web.master',
                              uniqueTag: 'master__Aa91a49e130e83674cb',
                              name: '事件及调用行为组',
                              id: 'aa91a49e130e83674cb',
                            },
                            caption: '按钮组',
                            itemStyle: 'DEFAULT',
                            itemType: 'BUTTONLIST',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'buttonlist',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container4',
                      },
                    ],
                    layout: {
                      align: 'center',
                      dir: 'column',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERMEDIUM',
                    },
                    id: 'container2',
                  },
                ],
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layoutPanel: true,
        codeName: 'usr0610469365',
        controlType: 'PANEL',
        logicName: 'card_logic_DataView卡片视图',
        appDataEntityId: 'web.master',
        controlParam: {},
        modelId: 'a25467ca718dec012f18f15ac6a3e39f',
        modelType: 'PSSYSVIEWPANEL',
        name: 'itemlayoutpanel',
        id: 'web.master.usr0610469365',
      },
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      enablePagingBar: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_logic_base',
      controlType: 'DATAVIEW',
      logicName: '卡片_事件及调用（基础）',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: 'b7d60a02adf77844179fb5539525f06b',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_logic_base',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片调用基础',
      codeName: 'card_logic_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_logic_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片调用基础',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd5d0a685d520f4502a3b8e6d05fe7d2d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_logic',
  id: 'web.master_card_logic',
};
