export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_right_nav',
  deviewId: 'A27E168E-A88B-44EC-BD1E-DFADF13029C5',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_右侧内置导航',
  codeName: 'master_card_right_nav',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      cardHeight: 100,
      cardWidth: 180,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'FLEX',
        layout: {
          layout: 'FLEX',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      sysImage: {
                        rawContent:
                          '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                      },
                      contentType: 'IMAGE',
                      predefinedType: 'STATIC_IMAGE',
                      rawItemHeight: 48,
                      rawItemWidth: 48,
                      id: 'static_image',
                    },
                    caption: '图片',
                    contentHeight: 48,
                    contentWidth: 48,
                    height: 48,
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      shrink: 1,
                      height: 48,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      width: 48,
                      widthMode: 'PX',
                    },
                    sysImage: {
                      rawContent:
                        '<svg id="图层_2" data-name="图层 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45.05908 45.05914"><defs><style>.cls-1{fill:#01b0ff;}</style></defs><title>ibizlab. 2</title><path class="cls-1" d="M1.64777,456.35452v45.05914H46.70685V456.35452Zm39.92407,3.86188-9.51965,19.60479L11.59913,460.1221ZM4.35572,497.13931v-34.424c8.37353,26.80664,17.53088,34.424,17.53088,34.424ZM17.424,472.06509l12.64337,12.21838-5.52484,9.77466S16.25531,478.54611,17.424,472.06509Zm9.031,25.07422,6.58728-9.031,7.64978,9.031Zm16.71912-2.99152-7.54029-9.61389,7.63453-13.10132Z" transform="translate(-1.64777 -456.35452)"/></svg>',
                    },
                    width: 48,
                    showCaption: true,
                    id: 'static_image',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'quantity',
                        },
                        viewFieldName: 'quantity',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'quantity',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.mock__cl_status',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'status',
                        },
                        viewFieldName: 'status',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'status',
                      },
                    ],
                    layout: {
                      align: 'center',
                      dir: 'column',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERMEDIUM',
                    },
                    id: 'container2',
                  },
                ],
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layoutPanel: true,
        codeName: 'a40c3b52f4a769ff56b',
        controlType: 'PANEL',
        logicName: 'card_base卡片视图',
        appDataEntityId: 'web.master',
        controlParam: {},
        modelId: 'c7f399249a60560746c2ed9270368a59',
        modelType: 'PSSYSVIEWPANEL',
        name: 'itemlayoutpanel',
        id: 'web.master.a40c3b52f4a769ff56b',
      },
      orderValueAppDEFieldId: 'px',
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingMode: 1,
      pagingSize: 10,
      enablePagingBar: true,
      singleSelect: true,
      navAppViewId: 'web.master_info_view',
      navViewPos: 'RIGHT',
      navViewWidth: 800,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_right_nav',
      controlType: 'DATAVIEW',
      logicName: '卡片_内置导航右',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'dataview',
      },
      modelId: '065188985fbb2365b5cd053fbc18ec27',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'web.master.card_right_nav',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_右侧内置导航',
      codeName: 'card_right_nav_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_right_nav_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_右侧内置导航',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '255c4ba7ac543095adde6eea08fe7a5f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_right_nav',
  id: 'web.master_card_right_nav',
};
