export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'map',
  loadDefault: true,
  deviewCodeName: 'map_mapstyle',
  deviewId: '3509f447bd1c9137dfcddd2f897b4e6a',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '地图_地图样式',
  codeName: 'master_map_mapstyle',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      eventNames: 'onBeforeUpdate',
      logicTrigger: 'CTRLEVENT',
      logicType: 'SCRIPT',
      ctrlName: 'map',
      scriptCode:
        "data.visualMap.max = 5;\r\ndata.series[0].emphasis.itemStyle.areaColor='#c51b1b';",
      builtinLogic: true,
      name: 'onBeforeUpdate',
      id: 'onbeforeupdate',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.master_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.master_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'map_user',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      legendPos: 'RIGHT',
      mapStyle: 'USER',
      sysMapItems: [
        {
          altitudeAppDEFieldId: 'level',
          customCond:
            "{'SRFNAVPARAM.n_parent_id_eq': context.srfareacode===100000?'86':`${context.srfareacode}`}",
          dataAppDEFieldId: 'level',
          idAppDEFieldId: 'id',
          itemStyle: 'REGION',
          itemType: 'area',
          latitudeAppDEFieldId: 'code',
          longitudeAppDEFieldId: 'code',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '区域',
          id: 'area',
        },
        {
          customCond:
            "{'SRFNAVPARAM.n_parent_id_eq': context.srfareacode===100000?'86':`${context.srfareacode}`}",
          dataAppDEFieldId: 'level',
          idAppDEFieldId: 'id',
          itemStyle: 'POINT',
          itemType: 'point',
          latitudeAppDEFieldId: 'latitude',
          longitudeAppDEFieldId: 'longitude',
          appDEDataSetId: 'fetch_default',
          appDataEntityId: 'web.region',
          textAppDEFieldId: 'name',
          name: '点',
          id: 'point',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'user_map_view_map_view',
      controlType: 'MAP',
      height: 600,
      logicName: '地图_地图样式_地图部件',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'map',
      },
      modelId: 'dea69e7b72bd5e345428a7f041d7e279',
      modelType: 'PSSYSMAPVIEW',
      name: 'map',
      id: 'web.master.user_map_view_map_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '地图_地图样式',
      codeName: 'map_mapstyle_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'map_mapstyle_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMAPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '地图_地图样式',
  viewStyle: 'DEFAULT',
  viewType: 'DEMAPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '67b6afa29ad5d613e0e3652fe5f49194',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERmap_mapstyle',
  id: 'web.master_map_mapstyle',
};
