export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'drtab_top',
  deviewId: 'a1bb0d64ab67176823a10444bc2818a1',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '数据关系分页_上方',
  codeName: 'master_drtab_top',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '区划',
          appViewId: 'web.region_grid_view',
          id: 'region',
        },
        {
          caption: '分类',
          appViewId: 'web.category_grid_view',
          id: 'category',
        },
        {
          caption: '主数据',
          appViewId: 'web.master_main_grid',
          id: 'master',
        },
      ],
      dataRelationTag: 'DataRelation35',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_drtab_top__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation35',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'fe6915b7d6bf094c3551b6ed312eb5ce',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation35',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '数据关系分页_上方',
      codeName: 'drtab_top_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'drtab_top_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据关系分页_上方',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '93b457d10e72a07d51ef15a12e0940e9',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdrtab_top',
  id: 'web.master_drtab_top',
};
