export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_contextmenu_month',
  deviewId: '9e02e43d5e38190599457c809d3b3587',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_上下文菜单_月',
  codeName: 'master_calendar_contextmenu_month',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      id: 'newdata@master',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      id: 'editdata@master',
    },
  ],
  controls: [
    {
      calendarStyle: 'MONTH',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          endTimeAppDEFieldId: 'end_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          decontextMenu: {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_newaction',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.NEW',
                },
                caption: '新建',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-file-text-o',
                  glyph: 'xf0f6@FontAwesome',
                },
                tooltip: '新建',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.NEW',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_editaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.EDIT',
                },
                caption: '编辑',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-edit',
                  glyph: 'xf044@FontAwesome',
                },
                tooltip: '编辑',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.EDIT',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_removeaction',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.REMOVE',
                },
                caption: '删除',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.REMOVE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction3',
              },
            ],
            codeName: 'calendar_contextmenu_month_cm',
            controlType: 'CONTEXTMENU',
            logicName: '日历_上下文菜单',
            appDataEntityId: 'web.master',
            controlParam: {
              id: 'cm',
            },
            modelId: 'eeea9e0c46b3ed545a387935c0786683',
            modelType: 'PSDETOOLBAR',
            name: 'cm',
            id: 'calendar_contextmenu_month_cm',
          },
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.master',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      appViewLogics: [
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            actionAfterWizard: 'DEFAULT',
            newDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.master_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_NEWDATA',
            id: '新建数据',
          },
          builtinLogic: true,
          id: 'master_newdata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            openDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
            editMode: true,
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.master_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_OPENDATA',
            id: '编辑数据',
          },
          builtinLogic: true,
          id: 'master_editdata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            openDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.master_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_OPENDATA',
            id: '打开数据',
          },
          builtinLogic: true,
          id: 'master_opendata',
        },
      ],
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_newaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.NEW',
              },
              caption: '新建',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              tooltip: '新建',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.NEW',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_editaction',
              uiactionTarget: 'SINGLEKEY',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.EDIT',
              },
              caption: '编辑',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-edit',
                glyph: 'xf044@FontAwesome',
              },
              tooltip: '编辑',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.EDIT',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_removeaction',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.REMOVE',
              },
              caption: '删除',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-remove',
                glyph: 'xf00d@FontAwesome',
              },
              tooltip: '删除',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.REMOVE',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction3',
            },
          ],
          codeName: 'calendar_contextmenu_month_cm',
          controlType: 'CONTEXTMENU',
          logicName: '日历_上下文菜单',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'cm',
          },
          modelId: 'eeea9e0c46b3ed545a387935c0786683',
          modelType: 'PSDETOOLBAR',
          name: 'cm',
          id: 'calendar_contextmenu_month_cm',
        },
      ],
      codeName: 'calendar_contextmenu_month',
      controlType: 'CALENDAR',
      logicName: '日历_上下文菜单_月',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'calendar',
      },
      modelId: '90e2d2eae9ee38297319adc9e389fae6',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.master.calendar_contextmenu_month',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_上下文菜单_月',
      codeName: 'calendar_contextmenu_month_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_contextmenu_month_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_上下文菜单_月',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '47169317c00d211e70f6b512bafc4f32',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_contextmenu_month',
  id: 'web.master_calendar_contextmenu_month',
};
