export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'card_fast_new',
  deviewId: '479a33e5f3d563e79ebfcdba91686e7c',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_快速新建',
  codeName: 'master_card_fast_new',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规新建',
          appViewId: 'web.master_card_new',
          id: 'new',
        },
        {
          caption: '分组新建',
          appViewId: 'web.master_card_group_new',
          id: 'group_new',
        },
      ],
      dataRelationTag: 'card_fast_new_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_card_fast_new__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'card_fast_new_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'e1a03b88e6f5e806a6b1cc311ba75cba',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'card_fast_new_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_快速新建',
      codeName: 'card_fast_new_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_fast_new_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_快速新建',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2e2a5f794d1c71c381fe8bd7dc9a142b',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_fast_new',
  id: 'web.master_card_fast_new',
};
