export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'count_flowdrtab',
  deviewId: '36aaa32a7de692b67414f3e6e7c48667',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '计数器_分页导航流式布局',
  codeName: 'master_count_flowdrtab',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '编辑表单',
          counterId: 'form',
          appViewId: 'web.master_counter_exp_form',
          id: 'form',
        },
        {
          caption: '表格',
          counterId: 'grid',
          appViewId: 'web.master_counter_exp_grid',
          id: 'grid',
        },
      ],
      dataRelationTag: 'counter_tab_exp_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      appCounterRefId: 'd0a6e348d1ed8a3141d3466137925bc7',
      uniqueTag: 'master_count_flowdrtab__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      appCounterRefs: [
        {
          appCounter: {
            codeName: 'Counter',
            counterType: 'DEDR',
            getAppDEActionId: 'get_counter_data',
            appDataEntityId: 'web.master',
            timer: 60000,
            uniqueTag: 'Counter',
            name: '计数器',
            id: 'web.counter',
          },
          refMode: {
            srfdeid: 'MASTER',
          },
          tag: 'd0a6e348d1ed8a3141d3466137925bc7',
          uniqueTag: 'Counter',
          id: 'd0a6e348d1ed8a3141d3466137925bc7',
        },
      ],
      codeName: 'counter_tab_exp_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          ENABLENAVBAR: 'false',
        },
        id: 'tabexppanel',
      },
      modelId: 'b0773b4f07f717739d5eaa49b39f721c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'counter_tab_exp_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '计数器_分页导航流式布局',
      codeName: 'count_flowdrtab_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'count_flowdrtab_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '计数器_分页导航流式布局',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a1581e7be9a9f80ddb25bb9c05a061df',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcount_flowdrtab',
  id: 'web.master_count_flowdrtab',
};
