export default {
  enableSearch: true,
  expandSearchForm: true,
  loadDefault: true,
  deviewCodeName: 'BIReport_scatter',
  deviewId: '77b25785696df6aa053302aa7a8a2412',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '智能报表-散点图',
  codeName: 'master_bi_report_scatter',
  appDataEntityId: 'web.master',
  controls: [
    {
      appDEReport: {
        codeName: 'BIReport_scatter',
        reportType: 'SYSBIREPORT',
        sysUniResCode: 'EXTENSION__READ_PSSYSBIREPORT',
        appBIReport: {
          appBICubeId: 'master',
          appBIReportDimensions: [
            {
              dimensionName: '所属分类',
              dimensionTag: 'w_categories',
              dimensionType: 'COMMON',
              appCodeListId: 'web.mock__cl_sample',
              appDEFieldId: 'categories',
              stdDataType: 25,
              id: '所属分类',
            },
          ],
          appBIReportMeasures: [
            {
              aggMode: 'SUM',
              measureName: '数量',
              measureTag: 'quantity',
              measureType: 'COMMON',
              appDEFieldId: 'quantity',
              stdDataType: 6,
              id: '数量',
            },
          ],
          appDataEntityId: 'web.master',
          reportTag: 'bireport_scatter',
          reportUIModel:
            '{"chart_type":"SCATTER","chart_color":["#118299","#13B3B3","#73DEB3","#FEC103","#9EB411","#83D0EE"],"xaxis_name":"1","xaxis_nametextstyle_fontstyle":"normal","xaxis_nametextstyle_fontsize":"12","xaxis_nametextstyle_fontcolor":"#000000","xaxis_axislabel_show":1,"xaxis_axislabel_fontstyle":"normal","xaxis_axislabel_fontsize":"12","xaxis_axislabel_fontcolor":"#000000","xaxis_axisline_show":1,"xaxis_axisline_linestyle_type":"solid","xaxis_axisline_linestyle_width":"1","xaxis_axisline_linestyle_color":"#000000","xaxis_splitline_show":1,"xaxis_splitline_linestyle_type":"dashed","xaxis_splitline_linestyle_width":"1","xaxis_splitline_linestyle_color":"#DDDDDD","xaxis_axislabel_interval":null,"yaxis_name":"1","yaxis_nametextstyle_fontstyle":"normal","yaxis_nametextstyle_fontsize":"12","yaxis_nametextstyle_fontcolor":"#000000","yaxis_axislabel_show":"1","yaxis_axislabel_fontstyle":"normal","yaxis_axislabel_fontsize":"12","yaxis_axislabel_fontcolor":"#000000","yaxis_axisline_show":"1","yaxis_axisline_linestyle_type":"solid","yaxis_axisline_linestyle_width":"1","yaxis_axisline_linestyle_color":"#000000","yaxis_splitline_show":1,"yaxis_splitline_linestyle_type":"dashed","yaxis_splitline_linestyle_width":"1","yaxis_splitline_linestyle_color":"#DDDDDD","series_label_show":"1","series_label_fontstyle":"normal","series_label_fontsize":"12","series_label_fontcolor":"#000000","series_label_data_range":"all","legend_show":"1","legend_fontstyle":"normal","legend_fontsize":"12","legend_fontcolor":"#000","legend_position":"right-top","period":null,"number_fontstyle":null,"number_fontsize":null,"number_fontcolor":null,"number_yoy_show":null,"number_yoy_value":null,"number_qoq_show":null,"number_qoq_value":null,"group_tags":null,"series_label_position":null,"series_label_percentage":null,"series_detail_fontstyle":null,"series_detail_fontsize":null,"series_detail_fontcolor":null,"series_max":null,"grid_header_fontstyle":null,"grid_header_fontsize":null,"grid_header_fontcolor":null,"grid_header_position":null,"grid_body_fontstyle":null,"grid_body_fontsize":null,"grid_body_fontcolor":null,"grid_body_position":null,"grid_show_agg":null,"grid_agg_row_position":null,"grid_agg_col_position":null,"grid_function_setting":null,"grid_col_sort":null}',
          name: '智能报表-散点图',
          id: 'bireport_scatter',
        },
        appBISchemeId: 'web.BIScheme',
        name: 'BIReport_scatter',
        id: 'bireport_scatter',
      },
      codeName: 'bi_report_scatter',
      controlType: 'REPORTPANEL',
      height: 500,
      logicName: 'BIReport_scatter',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'reportpanel',
      },
      modelId: '02c8a40a9af731f00d3c7e52b5b8578b',
      modelType: 'PSDEREPORTPANEL',
      name: 'reportpanel',
      id: 'web.master.bi_report_scatter',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '智能报表-散点图',
      codeName: 'bi_report_scatter_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'bi_report_scatter_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREPORTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '智能报表-散点图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREPORTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4c527c4bde93b86cba59607bc74df07a',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERBIReport_scatter',
  id: 'web.master_bi_report_scatter',
};
