export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'Pickup_multabexpview',
  deviewId: '8aec92702459e455a5f6cfc8a44be617',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '选择视图面板_多选分页导航视图',
  codeName: 'master_pickup_multabexpview',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '常规',
          appViewId: 'web.master_pickup_muleditview',
          id: 'default',
        },
        {
          caption: '左右关系',
          appViewId: 'web.master_pickup_muleditview2',
          id: 'leftright',
        },
      ],
      dataRelationTag: 'DataRelation103',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_pickup_multabexpview__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation103',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'b8fafb3d14fc8f8772ce8030ccd0ff1a',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation103',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '选择视图面板_多选分页导航视图',
      codeName: 'pickup_multabexpview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_multabexpview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择视图面板_多选分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'f9420a3e7ee6a7573dc6f9b183d90084',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERPickup_multabexpview',
  id: 'web.master_pickup_multabexpview',
};
