export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_layout_day',
  deviewId: 'ed9fa54c27a306b184360a4702050b26',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_项布局_天',
  codeName: 'master_calendar_layout_day',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'calendar_layout_dayorweek',
  controls: [
    {
      calendarStyle: 'DAY',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          endTimeAppDEFieldId: 'end_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          layoutPanel: {
            layoutMode: 'TABLE_24COL',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '时间范围：',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          rawItemWidth: 80,
                          id: 'static_text',
                        },
                        caption: '文本',
                        contentWidth: 80,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          width: 80,
                          widthMode: 'PX',
                        },
                        width: 80,
                        showCaption: true,
                        id: 'static_text',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'update_time',
                        },
                        viewFieldName: 'update_time',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'update_time',
                      },
                      {
                        rawItem: {
                          caption: '~',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text1',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingLeft: 'OUTERSMALL',
                          spacingRight: 'OUTERSMALL',
                        },
                        showCaption: true,
                        id: 'static_text1',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'update_time2',
                        },
                        viewFieldName: 'update_time',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'update_time2',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container2',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '名称：',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          rawItemWidth: 80,
                          id: 'static_text2',
                        },
                        caption: '文本',
                        contentWidth: 80,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          width: 80,
                          widthMode: 'PX',
                        },
                        width: 80,
                        showCaption: true,
                        id: 'static_text2',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-tags',
                            glyph: 'xf02c@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          predefinedType: 'STATIC_IMAGE',
                          id: 'static_image',
                        },
                        caption: '图片',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingLeft: 'OUTERSMALL',
                        },
                        sysImage: {
                          cssClass: 'fa fa-tags',
                          glyph: 'xf02c@FontAwesome',
                        },
                        showCaption: true,
                        id: 'static_image',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingTop: 'OUTERMEDIUM',
                    },
                    id: 'container1',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'container',
              },
            ],
            layoutPanel: true,
            mobilePanel: true,
            codeName: 'a0e0cac78278e9b94bd',
            controlType: 'PANEL',
            logicName: '日历_项布局面板_天',
            appDataEntityId: 'web.master',
            controlParam: {},
            modelId: 'a64e18a56ca2ccaf86e8d063d74a7486',
            modelType: 'PSSYSVIEWPANEL',
            name: 'masterlayoutpanel',
            id: 'web.master.a0e0cac78278e9b94bd',
          },
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.master',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_layout_day',
      controlType: 'CALENDAR',
      height: 650,
      logicName: '日历_天',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          SHOWDETAIL: 'true',
        },
        id: 'calendar',
      },
      modelId: 'f505af36b1cfd5e0b29222f7cfe75003',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.master.calendar_layout_day',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_项布局_天',
      codeName: 'calendar_layout_day_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_layout_day_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_项布局_天',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2a93765d346500e3cdec4290fff631af',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_layout_day',
  id: 'web.master_calendar_layout_day',
};
