export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'editor_markdown',
  deviewId: '4698926e0260f9cb97aa00562e65fb2e',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '编辑器_Markdown编辑框',
  codeName: 'master_editor_markdown',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'editor_markdown',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'editor_markdown_toolbar',
      controlType: 'TOOLBAR',
      logicName: '编辑器_Markdown编辑框_工具栏',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'c5488280d91f91194cd5b2e7eb189a79',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editor_markdown_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: 'Markdown编辑框',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      customtheme: 'dark',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem1',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用customtheme参数指定Markdown编辑框的主题，可选值有light和dark，值为light时为亮色主题，值为dark时为暗色主题。当前Markdown编辑框为暗色主题',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
              ],
              caption: 'Markdown主题',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      uploadparams: '{"username":"%srfusername%"}',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem3',
                  },
                  allowEmpty: true,
                  codeName: 'formitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem3',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用uploadparams参数指定图片上传的参数，用于计算上传路径。当前Markdown编辑框图片上传的参数为{"username":"%srfusername%"}',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
              ],
              caption: '上传参数',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      exportparams: '{"username":"%srfusername%"}',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem4',
                  },
                  allowEmpty: true,
                  codeName: 'formitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem4',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用exportparams参数指定图片下载的参数，用于计算下载路径。当前Markdown编辑框图片下载的参数为{"username":"%srfusername%"}',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem4',
                  },
                  codeName: 'rawitem4',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem4',
                },
              ],
              caption: '下载参数',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      osscat: 'cat',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem5',
                  },
                  allowEmpty: true,
                  codeName: 'formitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem5',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用osscat参数指定图片上传下载的OSS参数，用于计算上传路径和下载路径。当前Markdown编辑框图片上传下载的OSS参数为cat',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem5',
                  },
                  codeName: 'rawitem5',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem5',
                },
              ],
              caption: 'OSS参数',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      appentitytag: 'web.master',
                      datafieldtag: 'id',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem6',
                  },
                  allowEmpty: true,
                  codeName: 'formitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem6',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用appentitytag参数和datafieldtag参数约束编辑器在应用启用下载授权时手动指定当前文件所属实体及关联数据属性',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem6',
                  },
                  codeName: 'rawitem6',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem6',
                },
              ],
              caption: '下载启用鉴权',
              codeName: 'grouppanel7',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel7',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      enablenoaccess: 'true',
                      osscat: 'cat',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem19',
                  },
                  allowEmpty: true,
                  codeName: 'formitem19',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem19',
                },
                {
                  rawItem: {
                    caption:
                      "说明：使用enablenoaccess参数可启用无权限模式，启用后将不再计算下载授权凭证，且若上传路径中包含文件夹名称，该名称末尾会自动拼接 '$' 字符",
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem19',
                  },
                  codeName: 'rawitem19',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem19',
                },
              ],
              caption: '启用无权限模式',
              codeName: 'grouppanel11',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel11',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      globalfileprifix: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem20',
                  },
                  allowEmpty: true,
                  codeName: 'formitem20',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem20',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用globalfileprifix参数可启用文件全局路径功能，上传和预览路径使用全局文件路径 global/ibizutil/download',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem20',
                  },
                  codeName: 'rawitem20',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem20',
                },
              ],
              caption: '全局文件路径',
              codeName: 'grouppanel12',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel12',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: 'Markdown内容',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      readonly: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem2',
                  },
                  updateDV: 'Markdown内容',
                  allowEmpty: true,
                  codeName: 'formitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem2',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用readonly参数控制编辑器是否为只读态。当前编辑器为只读态',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
              ],
              caption: '只读态',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    showMaxLength: true,
                    editorParams: {
                      showmode: 'manual',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem7',
                  },
                  allowEmpty: true,
                  codeName: 'formitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem7',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用showmode参数约束md编辑器如何呈现，可选值为：default、manual，默认为default，当为manual时，默认预览形态，点击编辑按钮才会切换至编辑形态。',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem7',
                  },
                  codeName: 'rawitem7',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem7',
                },
              ],
              caption: '手动编辑模式',
              codeName: 'grouppanel8',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel8',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                      autoquestion: 'true',
                      autofill: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem10',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  codeName: 'formitem10',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem10',
                },
                {
                  rawItem: {
                    caption:
                      '说明：需配置编辑器参数ac=TRUE，使用聊天补全类型的自填模式控制是否开启输入框的AI聊天自填模式。同时在AI模式下支持编辑器参数autofill（自动填充：AI回答完成之后将数据自动填充到输入框中，未配置时默认为false）；autoquestion（自动提问：在打开AI功能时历史数据最后一个项是用户消息（USER）时是否自动提问，当打开AI行内聊天时是否自动提问，未配置时默认为true）',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem9',
                  },
                  codeName: 'rawitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem9',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                      openmode: 'minimize',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem11',
                  },
                  allowEmpty: true,
                  codeName: 'formitem11',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem11',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用openmode参数指定AI窗口的打开模式，当前HTML编辑框openmode参数为minimize，默认会最小化AI窗口',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem10',
                  },
                  codeName: 'rawitem10',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem10',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                      openmode: 'autoexpand',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem12',
                  },
                  allowEmpty: true,
                  codeName: 'formitem12',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem12',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用openmode参数指定AI窗口的打开模式，当前HTML编辑框openmode参数为autoexpand，默认会最小化AI窗口，当提问完成后自动展开AI窗口',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem13',
                  },
                  codeName: 'rawitem13',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem13',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                      autoclose: '{"mode":"minimize"}',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem13',
                  },
                  allowEmpty: true,
                  codeName: 'formitem13',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem13',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用autoclose参数指定在初始聊天完成后，AI窗口的自动关闭模式。当前HTML编辑框autoclose参数为{"mode":"minimize"}，聊天完成后会最小化AI窗口',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem11',
                  },
                  codeName: 'rawitem11',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem11',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                      autoclose: '{"mode":"close"}',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem14',
                  },
                  allowEmpty: true,
                  codeName: 'formitem14',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem14',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用autoclose参数指定在初始聊天完成后，AI窗口的自动关闭模式。当前HTML编辑框autoclose参数为{"mode":"close"}，聊天完成后会直接关闭AI窗口',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem12',
                  },
                  codeName: 'rawitem12',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem12',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                      autoclose: '{"mode":"closetime","duration":6}',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem15',
                  },
                  allowEmpty: true,
                  codeName: 'formitem15',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem15',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用autoclose参数指定在初始聊天完成后，AI窗口的自动关闭模式。当前HTML编辑框autoclose参数为{"mode":"closetime","duration":6}，聊天完成后会根据 duration 配置的值延时关闭窗口，duration配置单位为秒（s），默认值为 3 秒',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem14',
                  },
                  codeName: 'rawitem14',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem14',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      srfaiappendcurdata: 'true',
                      ac: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem17',
                  },
                  allowEmpty: true,
                  codeName: 'formitem17',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem17',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用srfaiappendcurdata参数用于判断是否传入对象参数，主要用于在请求历史记录时，附加当前参数，打开AI行内聊天时默认为true',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem16',
                  },
                  codeName: 'rawitem16',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem16',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      srfaiappendcurcontent: '登录人是${content.srfusername}',
                      ac: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem18',
                  },
                  allowEmpty: true,
                  codeName: 'formitem18',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem18',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用srfaiappendcurcontent参数时，会将其传入编辑内容作为用户消息，主要用于在请求历史记录后，附加当前编辑内容作为用户消息，当前设置的值为"登录人为${context.srfusername}"',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem17',
                  },
                  codeName: 'rawitem17',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem17',
                },
              ],
              caption: 'AI聊天',
              codeName: 'grouppanel10',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel10',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      ac: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem8',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  codeName: 'formitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem8',
                },
                {
                  rawItem: {
                    caption:
                      '说明：配置编辑参数 ac=true 并开启编辑器 AI 聊天自填模式后，选取文本时将显示行内工具栏；若自填模式配置额外操作行为组，点击 AI 工具栏项即可打开AI聊天上下文菜单。',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem18',
                  },
                  codeName: 'rawitem18',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem18',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      inlineaichatheight: '400',
                      ac: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem9',
                  },
                  allowEmpty: true,
                  codeName: 'formitem9',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem9',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用inlineaichatheight参数指定AI行内聊天框的高度。当前Markdown编辑器inlineaichatheight参数为400',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem8',
                  },
                  codeName: 'rawitem8',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem8',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  editor: {
                    mode: 'EDIT',
                    appDEACModeId: 'aichatautohistory',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'web.master',
                    enableAC: true,
                    showMaxLength: true,
                    editorParams: {
                      inlinecompletionmode: 'sync',
                      ac: 'true',
                    },
                    editorType: 'MARKDOWN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem16',
                  },
                  allowEmpty: true,
                  codeName: 'formitem16',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem16',
                },
                {
                  rawItem: {
                    caption:
                      '说明：使用inlinecompletionmode参数指定AI行内聊天框的请求模式。当前HTML编辑框inlinecompletionmode参数为sync，未指定时默认为async',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    sysCss: {
                      cssName: 'description-text',
                    },
                    id: 'rawitem15',
                  },
                  codeName: 'rawitem15',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'description-text',
                  },
                  showCaption: true,
                  id: 'rawitem15',
                },
              ],
              caption: 'AI行内聊天',
              codeName: 'grouppanel9',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel9',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: 'Markdown编辑框',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main57',
      controlType: 'FORM',
      logicName: '编辑器_Markdown编辑框_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '8634c3e1504c8b64854a4d9b242afaea',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main57',
    },
    {
      codeName: 'editor_markdown_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editor_markdown_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '编辑器_Markdown编辑框',
      codeName: 'editor_markdown_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'editor_markdown_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '编辑器_Markdown编辑框',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '0f955c957623102c3db6d820108c1bfe',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTEReditor_markdown',
  id: 'web.master_editor_markdown',
};
