export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'grid_row_logic',
  deviewId: 'aeb034bb2e7f103328b9631bbe77c795',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表格_逻辑',
  codeName: 'master_grid_row_logic',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '默认值',
          appViewId: 'web.master_grid_dfvalue',
          id: 'defaultvalue',
        },
        {
          caption: '动态启用',
          appViewId: 'web.master_grid_logic_enable',
          id: 'enable',
        },
        {
          caption: '动态空输入',
          appViewId: 'web.master_grid_logic_require',
          id: 'require',
        },
      ],
      dataRelationTag: 'DataRelation24',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_grid_row_logic__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation24',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '96b4a4dcee7394f54ac50fe50f8fc86d',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation24',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表格_逻辑',
      codeName: 'grid_row_logic_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_row_logic_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格_逻辑',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e04d0bde603c894aacd3eb7ad543cd53',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERgrid_row_logic',
  id: 'web.master_grid_row_logic',
};
