export default {
  enableSearch: true,
  expandSearchForm: true,
  loadDefault: true,
  deviewCodeName: 'BIReport_multi_strip',
  deviewId: 'a373061d845de5e7ec36b2783baa8bee',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '智能报表-多序列条形图',
  codeName: 'master_bi_report_multi_strip',
  appDataEntityId: 'web.master',
  controls: [
    {
      appDEReport: {
        codeName: 'BIReport_multi_strip',
        reportType: 'SYSBIREPORT',
        sysUniResCode: 'EXTENSION__READ_PSSYSBIREPORT',
        appBIReport: {
          appBICubeId: 'master',
          appBIReportDimensions: [
            {
              dimensionName: '所属分类',
              dimensionTag: 'w_categories',
              dimensionType: 'COMMON',
              appCodeListId: 'web.mock__cl_sample',
              appDEFieldId: 'categories',
              stdDataType: 25,
              id: '所属分类',
            },
            {
              dimensionName: '状态',
              dimensionTag: 'w_status',
              dimensionType: 'COMMON',
              appCodeListId: 'web.mock__cl_status',
              appDEFieldId: 'status',
              stdDataType: 9,
              id: '状态',
            },
          ],
          appBIReportMeasures: [
            {
              measureFormula: 'countif(ENABLE = 1)',
              measureName: '计数',
              measureTag: 'count',
              measureType: 'CALCULATED',
              id: '计数',
            },
            {
              aggMode: 'SUM',
              measureName: '数量',
              measureTag: 'quantity',
              measureType: 'COMMON',
              appDEFieldId: 'quantity',
              stdDataType: 6,
              id: '数量',
            },
          ],
          appDataEntityId: 'web.master',
          reportTag: 'bireport_multi_strip',
          reportUIModel:
            '{"chart_type":"MULTI_SERIES_BAR","group_tags":"w_status","chart_color":["#6698FF","#73DEB3","#7585A2","#F7BE21","#EE734A","#83D0EE"],"xaxis_name":"1","xaxis_nametextstyle_fontstyle":"normal","xaxis_nametextstyle_fontsize":"12","xaxis_nametextstyle_fontcolor":"#000","xaxis_axislabel_show":"1","xaxis_axislabel_fontstyle":"normal","xaxis_axislabel_fontsize":"12","xaxis_axislabel_fontcolor":"#000","xaxis_axisline_show":"1","xaxis_axisline_linestyle_type":"solid","xaxis_axisline_linestyle_width":"1","xaxis_axisline_linestyle_color":"#000","xaxis_splitline_show":1,"xaxis_splitline_linestyle_type":"dashed","xaxis_splitline_linestyle_width":"1","xaxis_splitline_linestyle_color":"#DDDDDD","xaxis_axislabel_interval":null,"yaxis_name":"1","yaxis_nametextstyle_fontstyle":"normal","yaxis_nametextstyle_fontsize":"12","yaxis_nametextstyle_fontcolor":"#000","yaxis_axislabel_show":"1","yaxis_axislabel_fontstyle":"normal","yaxis_axislabel_fontsize":"12","yaxis_axislabel_fontcolor":"#000","yaxis_axisline_show":"1","yaxis_axisline_linestyle_type":"dashed","yaxis_axisline_linestyle_width":"1","yaxis_axisline_linestyle_color":"#000000","yaxis_splitline_show":1,"yaxis_splitline_linestyle_type":"dashed","yaxis_splitline_linestyle_width":"1","yaxis_splitline_linestyle_color":"#DDDDDD","series_label_show":"1","series_label_fontstyle":"normal","series_label_fontsize":"12","series_label_fontcolor":"#000","series_label_position":"inside","series_label_data_range":"all","legend_show":"1","legend_fontstyle":"normal","legend_fontsize":"12","legend_fontcolor":"#000","legend_position":"right-top","period":null,"number_fontstyle":null,"number_fontsize":null,"number_fontcolor":null,"number_yoy_show":null,"number_yoy_value":null,"number_qoq_show":null,"number_qoq_value":null,"series_label_percentage":null,"series_detail_fontstyle":null,"series_detail_fontsize":null,"series_detail_fontcolor":null,"series_max":null,"grid_header_fontstyle":null,"grid_header_fontsize":null,"grid_header_fontcolor":null,"grid_header_position":null,"grid_body_fontstyle":null,"grid_body_fontsize":null,"grid_body_fontcolor":null,"grid_body_position":null,"grid_show_agg":null,"grid_agg_row_position":null,"grid_agg_col_position":null,"grid_function_setting":null,"grid_col_sort":null}',
          name: '智能报表-多序列条形图',
          id: 'bireport_multi_strip',
        },
        appBISchemeId: 'web.BIScheme',
        name: 'BIReport_multi_strip',
        id: 'bireport_multi_strip',
      },
      codeName: 'bi_report_multi_strip',
      controlType: 'REPORTPANEL',
      height: 500,
      logicName: 'BIReport_multi_strip',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'reportpanel',
      },
      modelId: '0ed8a66605fe17ac999ea797ff173186',
      modelType: 'PSDEREPORTPANEL',
      name: 'reportpanel',
      id: 'web.master.bi_report_multi_strip',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '智能报表-多序列条形图',
      codeName: 'bi_report_multi_strip_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'bi_report_multi_strip_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREPORTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '智能报表-多序列条形图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREPORTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '999f0b5fa98f8e2c96e752d2ceb3d6c6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERBIReport_multi_strip',
  id: 'web.master_bi_report_multi_strip',
};
