export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'tree_dy_uiaction_group_embed',
  deviewId: '8f707148a81ce03bce6906f0c78b8119',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树_成员为动态界面行为组',
  codeName: 'master_tree_dy_uiaction_group_embed',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup318',
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node_1',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
        {
          childDETreeNodeId: 'node',
          parentDETreeNodeId: 'node_1',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.master',
          decontextMenu: {
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '打开弹窗',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_dialog@master',
                      showCaption: true,
                      showIcon: true,
                      id: 'u6d34e27',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      detailType: 'DEUIACTIONGROUP',
                      refUIActionGroup: {
                        dynamicMode: 1,
                        actionLevelAppDEFieldId: 'level',
                        buttonStyleAppDEFieldId: 'button_style',
                        clsAppDEFieldId: 'style',
                        detailAppDEDataSetId: 'fetch_web_data_set',
                        detailAppDataEntityId: 'web.ua_group_detail',
                        enableScriptAppDEFieldId: 'enable_logic',
                        iconClsAppDEFieldId: 'icon_cls',
                        appDataEntityId: 'web.master',
                        textAppDEFieldId: 'caption',
                        tipsAppDEFieldId: 'tooltip',
                        uiactionTagAppDEFieldId: 'action_tag',
                        uniqueTag: 'master__web_dynamic_ex_ua',
                        visibleScriptAppDEFieldId: 'visible_logic',
                        name: 'web扩展界面行为组（动态）',
                        id: 'web_dynamic_ex_ua',
                      },
                      showCaption: true,
                      showIcon: true,
                      id: 'u640401e',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '打开主表格视图',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_main_gridview@master',
                      showCaption: true,
                      showIcon: true,
                      id: 'ud2b4df4',
                    },
                  ],
                  appDataEntityId: 'web.master',
                  id: 'web成员为扩展界面行为组（动态）',
                },
                valid: true,
                caption: '按项展开（第一层）',
                itemType: 'ITEMS',
                tooltip: '按项展开（第一层）',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                groupExtractMode: 'ITEMS',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '打开弹窗',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_dialog@master',
                      showCaption: true,
                      showIcon: true,
                      id: 'u6d34e27',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      detailType: 'DEUIACTIONGROUP',
                      refUIActionGroup: {
                        dynamicMode: 1,
                        actionLevelAppDEFieldId: 'level',
                        buttonStyleAppDEFieldId: 'button_style',
                        clsAppDEFieldId: 'style',
                        detailAppDEDataSetId: 'fetch_web_data_set',
                        detailAppDataEntityId: 'web.ua_group_detail',
                        enableScriptAppDEFieldId: 'enable_logic',
                        iconClsAppDEFieldId: 'icon_cls',
                        appDataEntityId: 'web.master',
                        textAppDEFieldId: 'caption',
                        tipsAppDEFieldId: 'tooltip',
                        uiactionTagAppDEFieldId: 'action_tag',
                        uniqueTag: 'master__web_dynamic_ex_ua',
                        visibleScriptAppDEFieldId: 'visible_logic',
                        name: 'web扩展界面行为组（动态）',
                        id: 'web_dynamic_ex_ua',
                      },
                      showCaption: true,
                      showIcon: true,
                      id: 'u640401e',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '打开主表格视图',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_main_gridview@master',
                      showCaption: true,
                      showIcon: true,
                      id: 'ud2b4df4',
                    },
                  ],
                  appDataEntityId: 'web.master',
                  id: 'web成员为扩展界面行为组（动态）',
                },
                valid: true,
                caption: '按分组展开（第一层）',
                itemType: 'ITEMS',
                tooltip: '按分组展开（第一层）',
                showCaption: true,
                showIcon: true,
                id: 'items2',
              },
              {
                actionLevel: 100,
                groupExtractMode: 'ITEMX',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '打开弹窗',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_dialog@master',
                      showCaption: true,
                      showIcon: true,
                      id: 'u6d34e27',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      detailType: 'DEUIACTIONGROUP',
                      refUIActionGroup: {
                        dynamicMode: 1,
                        actionLevelAppDEFieldId: 'level',
                        buttonStyleAppDEFieldId: 'button_style',
                        clsAppDEFieldId: 'style',
                        detailAppDEDataSetId: 'fetch_web_data_set',
                        detailAppDataEntityId: 'web.ua_group_detail',
                        enableScriptAppDEFieldId: 'enable_logic',
                        iconClsAppDEFieldId: 'icon_cls',
                        appDataEntityId: 'web.master',
                        textAppDEFieldId: 'caption',
                        tipsAppDEFieldId: 'tooltip',
                        uiactionTagAppDEFieldId: 'action_tag',
                        uniqueTag: 'master__web_dynamic_ex_ua',
                        visibleScriptAppDEFieldId: 'visible_logic',
                        name: 'web扩展界面行为组（动态）',
                        id: 'web_dynamic_ex_ua',
                      },
                      showCaption: true,
                      showIcon: true,
                      id: 'u640401e',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '打开主表格视图',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_main_gridview@master',
                      showCaption: true,
                      showIcon: true,
                      id: 'ud2b4df4',
                    },
                  ],
                  appDataEntityId: 'web.master',
                  id: 'web成员为扩展界面行为组（动态）',
                },
                valid: true,
                caption: '首项+分组展开（第一层）',
                itemType: 'ITEMS',
                tooltip: '首项+分组展开（第一层）',
                showCaption: true,
                showIcon: true,
                id: 'items3',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    groupExtractMode: 'ITEMS',
                    uiactionGroup: {
                      uiactionGroupDetails: [
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '打开弹窗',
                          detailType: 'DEUIACTION',
                          uiactionId: 'open_dialog@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'u6d34e27',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          detailType: 'DEUIACTIONGROUP',
                          refUIActionGroup: {
                            dynamicMode: 1,
                            actionLevelAppDEFieldId: 'level',
                            buttonStyleAppDEFieldId: 'button_style',
                            clsAppDEFieldId: 'style',
                            detailAppDEDataSetId: 'fetch_web_data_set',
                            detailAppDataEntityId: 'web.ua_group_detail',
                            enableScriptAppDEFieldId: 'enable_logic',
                            iconClsAppDEFieldId: 'icon_cls',
                            appDataEntityId: 'web.master',
                            textAppDEFieldId: 'caption',
                            tipsAppDEFieldId: 'tooltip',
                            uiactionTagAppDEFieldId: 'action_tag',
                            uniqueTag: 'master__web_dynamic_ex_ua',
                            visibleScriptAppDEFieldId: 'visible_logic',
                            name: 'web扩展界面行为组（动态）',
                            id: 'web_dynamic_ex_ua',
                          },
                          showCaption: true,
                          showIcon: true,
                          id: 'u640401e',
                        },
                        {
                          actionLevel: 100,
                          afterItemType: 'NONE',
                          beforeItemType: 'NONE',
                          buttonStyle: 'DEFAULT',
                          caption: '打开主表格视图',
                          detailType: 'DEUIACTION',
                          uiactionId: 'open_main_gridview@master',
                          showCaption: true,
                          showIcon: true,
                          id: 'ud2b4df4',
                        },
                      ],
                      appDataEntityId: 'web.master',
                      id: 'web成员为扩展界面行为组（动态）',
                    },
                    valid: true,
                    caption: '分组展开（非首层）',
                    itemType: 'ITEMS',
                    tooltip: '分组展开（非首层）',
                    showCaption: true,
                    showIcon: true,
                    id: 'items7',
                  },
                ],
                valid: true,
                caption: '界面行为组测试',
                itemType: 'ITEMS',
                tooltip: '界面行为组测试',
                showCaption: true,
                showIcon: true,
                id: 'items4',
              },
            ],
            codeName: 'tree_dy_uiaction_group_embed_node_cm',
            controlType: 'CONTEXTMENU',
            logicName: '成员为动态界面行为组',
            appDataEntityId: 'web.master',
            controlParam: {
              id: 'node_cm',
            },
            modelId: '71950b2ce27284c0d66ec59c7a82bfa8',
            modelType: 'PSDETOOLBAR',
            name: 'node_cm',
            id: 'tree_dy_uiaction_group_embed_node_cm',
          },
          detreeNodeRVs: [
            {
              refAppViewId: 'web.master_edit_view',
              id: 'editdata',
            },
            {
              refAppViewId: 'web.master_edit_view',
              id: 'newdata',
            },
          ],
          treeNodeType: 'DE',
          enableEditData: true,
          enableNewData: true,
          enableRemoveData: true,
          enableViewData: true,
          expanded: true,
          name: '名称',
          id: 'node',
        },
        {
          text: '主数据',
          nodeType: 'node_1',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          expanded: true,
          name: '主数据',
          id: 'node_1',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'web.master',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      appViewLogics: [
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            actionAfterWizard: 'DEFAULT',
            newDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.master_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_NEWDATA',
            id: '新建数据',
          },
          builtinLogic: true,
          id: 'node_newdata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            openDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.master_edit_view',
            },
            editMode: true,
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.master_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_OPENDATA',
            id: '打开数据',
          },
          builtinLogic: true,
          id: 'node_opendata',
        },
      ],
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              groupExtractMode: 'ITEM',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开弹窗',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_dialog@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'u6d34e27',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      dynamicMode: 1,
                      actionLevelAppDEFieldId: 'level',
                      buttonStyleAppDEFieldId: 'button_style',
                      clsAppDEFieldId: 'style',
                      detailAppDEDataSetId: 'fetch_web_data_set',
                      detailAppDataEntityId: 'web.ua_group_detail',
                      enableScriptAppDEFieldId: 'enable_logic',
                      iconClsAppDEFieldId: 'icon_cls',
                      appDataEntityId: 'web.master',
                      textAppDEFieldId: 'caption',
                      tipsAppDEFieldId: 'tooltip',
                      uiactionTagAppDEFieldId: 'action_tag',
                      uniqueTag: 'master__web_dynamic_ex_ua',
                      visibleScriptAppDEFieldId: 'visible_logic',
                      name: 'web扩展界面行为组（动态）',
                      id: 'web_dynamic_ex_ua',
                    },
                    showCaption: true,
                    showIcon: true,
                    id: 'u640401e',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开主表格视图',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_main_gridview@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'ud2b4df4',
                  },
                ],
                appDataEntityId: 'web.master',
                id: 'web成员为扩展界面行为组（动态）',
              },
              valid: true,
              caption: '按项展开（第一层）',
              itemType: 'ITEMS',
              tooltip: '按项展开（第一层）',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
            {
              actionLevel: 100,
              groupExtractMode: 'ITEMS',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开弹窗',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_dialog@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'u6d34e27',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      dynamicMode: 1,
                      actionLevelAppDEFieldId: 'level',
                      buttonStyleAppDEFieldId: 'button_style',
                      clsAppDEFieldId: 'style',
                      detailAppDEDataSetId: 'fetch_web_data_set',
                      detailAppDataEntityId: 'web.ua_group_detail',
                      enableScriptAppDEFieldId: 'enable_logic',
                      iconClsAppDEFieldId: 'icon_cls',
                      appDataEntityId: 'web.master',
                      textAppDEFieldId: 'caption',
                      tipsAppDEFieldId: 'tooltip',
                      uiactionTagAppDEFieldId: 'action_tag',
                      uniqueTag: 'master__web_dynamic_ex_ua',
                      visibleScriptAppDEFieldId: 'visible_logic',
                      name: 'web扩展界面行为组（动态）',
                      id: 'web_dynamic_ex_ua',
                    },
                    showCaption: true,
                    showIcon: true,
                    id: 'u640401e',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开主表格视图',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_main_gridview@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'ud2b4df4',
                  },
                ],
                appDataEntityId: 'web.master',
                id: 'web成员为扩展界面行为组（动态）',
              },
              valid: true,
              caption: '按分组展开（第一层）',
              itemType: 'ITEMS',
              tooltip: '按分组展开（第一层）',
              showCaption: true,
              showIcon: true,
              id: 'items2',
            },
            {
              actionLevel: 100,
              groupExtractMode: 'ITEMX',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开弹窗',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_dialog@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'u6d34e27',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      dynamicMode: 1,
                      actionLevelAppDEFieldId: 'level',
                      buttonStyleAppDEFieldId: 'button_style',
                      clsAppDEFieldId: 'style',
                      detailAppDEDataSetId: 'fetch_web_data_set',
                      detailAppDataEntityId: 'web.ua_group_detail',
                      enableScriptAppDEFieldId: 'enable_logic',
                      iconClsAppDEFieldId: 'icon_cls',
                      appDataEntityId: 'web.master',
                      textAppDEFieldId: 'caption',
                      tipsAppDEFieldId: 'tooltip',
                      uiactionTagAppDEFieldId: 'action_tag',
                      uniqueTag: 'master__web_dynamic_ex_ua',
                      visibleScriptAppDEFieldId: 'visible_logic',
                      name: 'web扩展界面行为组（动态）',
                      id: 'web_dynamic_ex_ua',
                    },
                    showCaption: true,
                    showIcon: true,
                    id: 'u640401e',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开主表格视图',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_main_gridview@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'ud2b4df4',
                  },
                ],
                appDataEntityId: 'web.master',
                id: 'web成员为扩展界面行为组（动态）',
              },
              valid: true,
              caption: '首项+分组展开（第一层）',
              itemType: 'ITEMS',
              tooltip: '首项+分组展开（第一层）',
              showCaption: true,
              showIcon: true,
              id: 'items3',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  groupExtractMode: 'ITEMS',
                  uiactionGroup: {
                    uiactionGroupDetails: [
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        buttonStyle: 'DEFAULT',
                        caption: '打开弹窗',
                        detailType: 'DEUIACTION',
                        uiactionId: 'open_dialog@master',
                        showCaption: true,
                        showIcon: true,
                        id: 'u6d34e27',
                      },
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        buttonStyle: 'DEFAULT',
                        detailType: 'DEUIACTIONGROUP',
                        refUIActionGroup: {
                          dynamicMode: 1,
                          actionLevelAppDEFieldId: 'level',
                          buttonStyleAppDEFieldId: 'button_style',
                          clsAppDEFieldId: 'style',
                          detailAppDEDataSetId: 'fetch_web_data_set',
                          detailAppDataEntityId: 'web.ua_group_detail',
                          enableScriptAppDEFieldId: 'enable_logic',
                          iconClsAppDEFieldId: 'icon_cls',
                          appDataEntityId: 'web.master',
                          textAppDEFieldId: 'caption',
                          tipsAppDEFieldId: 'tooltip',
                          uiactionTagAppDEFieldId: 'action_tag',
                          uniqueTag: 'master__web_dynamic_ex_ua',
                          visibleScriptAppDEFieldId: 'visible_logic',
                          name: 'web扩展界面行为组（动态）',
                          id: 'web_dynamic_ex_ua',
                        },
                        showCaption: true,
                        showIcon: true,
                        id: 'u640401e',
                      },
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        buttonStyle: 'DEFAULT',
                        caption: '打开主表格视图',
                        detailType: 'DEUIACTION',
                        uiactionId: 'open_main_gridview@master',
                        showCaption: true,
                        showIcon: true,
                        id: 'ud2b4df4',
                      },
                    ],
                    appDataEntityId: 'web.master',
                    id: 'web成员为扩展界面行为组（动态）',
                  },
                  valid: true,
                  caption: '分组展开（非首层）',
                  itemType: 'ITEMS',
                  tooltip: '分组展开（非首层）',
                  showCaption: true,
                  showIcon: true,
                  id: 'items7',
                },
              ],
              valid: true,
              caption: '界面行为组测试',
              itemType: 'ITEMS',
              tooltip: '界面行为组测试',
              showCaption: true,
              showIcon: true,
              id: 'items4',
            },
          ],
          codeName: 'tree_dy_uiaction_group_embed_node_cm',
          controlType: 'CONTEXTMENU',
          logicName: '成员为动态界面行为组',
          appDataEntityId: 'web.master',
          controlParam: {
            id: 'node_cm',
          },
          modelId: '71950b2ce27284c0d66ec59c7a82bfa8',
          modelType: 'PSDETOOLBAR',
          name: 'node_cm',
          id: 'tree_dy_uiaction_group_embed_node_cm',
        },
      ],
      codeName: 'tree_dy_uiaction_group_embed_tree_view',
      controlType: 'TREEVIEW',
      logicName: '树_成员为动态界面行为组_树视图',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tree',
      },
      modelId: 'f66de47a5b9e8ac1c411815ccdc03fa1',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'web.master.tree_dy_uiaction_group_embed_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树_成员为动态界面行为组',
      codeName: 'tree_dy_uiaction_group_embed_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_dy_uiaction_group_embed_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树_成员为动态界面行为组',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a3f80d55da357dc53914e467ee45016d',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtree_dy_uiaction_group_embed',
  id: 'web.master_tree_dy_uiaction_group_embed',
};
