export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendar_nav_day',
  deviewId: '3ac8997071644c272267d6d092c345d1',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置导航栏_天',
  codeName: 'master_calendar_nav_day',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '右侧导航',
          appViewId: 'web.master_calendar_rightnav_day',
          id: 'right',
        },
        {
          caption: '下方导航',
          appViewId: 'web.master_calendar_bottomnav_day',
          id: 'bottom',
        },
      ],
      dataRelationTag: 'calendar_nav_day_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar_nav_day__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_nav_day_dr',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          ENABLENAVBAR: 'false',
        },
        id: 'tabexppanel',
      },
      modelId: 'd8996ac37a624de87285f8f6b0b384bc',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'calendar_nav_day_dr',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_内置导航栏_天',
      codeName: 'calendar_nav_day_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_nav_day_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_内置导航栏_天',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '8a6bb53c01cdc6170299ed1ada08526e',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_nav_day',
  id: 'web.master_calendar_nav_day',
};
