export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'form_dy_uiaction_group',
  deviewId: 'cc2ecb2e8992f178993d35249087098e',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '表单_动态界面行为组',
  codeName: 'master_form_dy_uiaction_group',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup332',
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.master',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.master',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.master',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.master',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.master',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.master',
        id: 'update',
      },
      wfstartControlAction: {
        appDEMethodId: 'wfstart',
        appDataEntityId: 'web.master',
        id: 'wfstart',
      },
      wfsubmitControlAction: {
        appDEMethodId: 'wfsubmit',
        appDataEntityId: 'web.master',
        id: 'wfsubmit',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              actionGroupExtractMode: 'ITEM',
              uiactionGroup: {
                dynamicMode: 1,
                actionLevelAppDEFieldId: 'level',
                buttonStyleAppDEFieldId: 'button_style',
                clsAppDEFieldId: 'style',
                detailAppDEDataSetId: 'fetch_web_data_set',
                detailAppDataEntityId: 'web.ua_group_detail',
                enableScriptAppDEFieldId: 'enable_logic',
                iconClsAppDEFieldId: 'icon_cls',
                appDataEntityId: 'web.master',
                textAppDEFieldId: 'caption',
                tipsAppDEFieldId: 'tooltip',
                uiactionTagAppDEFieldId: 'action_tag',
                uniqueTag: 'master__web_dynamic_ex_ua',
                visibleScriptAppDEFieldId: 'visible_logic',
                name: 'web扩展界面行为组（动态）',
                id: 'web_dynamic_ex_ua',
              },
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  caption: '搜索',
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem',
                },
              ],
              caption: '分组面板',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '按项展开：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem1',
                      },
                      codeName: 'rawitem1',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem1',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      buttonListType: 'UIACTIONGROUP',
                      uiactionGroup: {
                        dynamicMode: 1,
                        actionLevelAppDEFieldId: 'level',
                        buttonStyleAppDEFieldId: 'button_style',
                        clsAppDEFieldId: 'style',
                        detailAppDEDataSetId: 'fetch_web_data_set',
                        detailAppDataEntityId: 'web.ua_group_detail',
                        enableScriptAppDEFieldId: 'enable_logic',
                        iconClsAppDEFieldId: 'icon_cls',
                        appDataEntityId: 'web.master',
                        textAppDEFieldId: 'caption',
                        tipsAppDEFieldId: 'tooltip',
                        uiactionTagAppDEFieldId: 'action_tag',
                        uniqueTag: 'master__web_dynamic_ex_ua',
                        visibleScriptAppDEFieldId: 'visible_logic',
                        name: 'web扩展界面行为组（动态）',
                        id: 'web_dynamic_ex_ua',
                      },
                      codeName: 'buttonlist1',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTONLIST',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'buttonlist1',
                    },
                  ],
                  caption: '按项展开',
                  codeName: 'grouppanel7',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel7',
                },
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '按分组展开：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem2',
                      },
                      codeName: 'rawitem2',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem2',
                    },
                    {
                      actionGroupExtractMode: 'ITEMS',
                      buttonListType: 'UIACTIONGROUP',
                      uiactionGroup: {
                        dynamicMode: 1,
                        actionLevelAppDEFieldId: 'level',
                        buttonStyleAppDEFieldId: 'button_style',
                        clsAppDEFieldId: 'style',
                        detailAppDEDataSetId: 'fetch_web_data_set',
                        detailAppDataEntityId: 'web.ua_group_detail',
                        enableScriptAppDEFieldId: 'enable_logic',
                        iconClsAppDEFieldId: 'icon_cls',
                        appDataEntityId: 'web.master',
                        textAppDEFieldId: 'caption',
                        tipsAppDEFieldId: 'tooltip',
                        uiactionTagAppDEFieldId: 'action_tag',
                        uniqueTag: 'master__web_dynamic_ex_ua',
                        visibleScriptAppDEFieldId: 'visible_logic',
                        name: 'web扩展界面行为组（动态）',
                        id: 'web_dynamic_ex_ua',
                      },
                      caption: '扩展界面行为组（动态）',
                      codeName: 'buttonlist2',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTONLIST',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'buttonlist2',
                    },
                  ],
                  caption: '按分组展开',
                  codeName: 'grouppanel8',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel8',
                },
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '首项+分组展开：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem3',
                      },
                      codeName: 'rawitem3',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem3',
                    },
                    {
                      actionGroupExtractMode: 'ITEMX',
                      buttonListType: 'UIACTIONGROUP',
                      uiactionGroup: {
                        dynamicMode: 1,
                        actionLevelAppDEFieldId: 'level',
                        buttonStyleAppDEFieldId: 'button_style',
                        clsAppDEFieldId: 'style',
                        detailAppDEDataSetId: 'fetch_web_data_set',
                        detailAppDataEntityId: 'web.ua_group_detail',
                        enableScriptAppDEFieldId: 'enable_logic',
                        iconClsAppDEFieldId: 'icon_cls',
                        appDataEntityId: 'web.master',
                        textAppDEFieldId: 'caption',
                        tipsAppDEFieldId: 'tooltip',
                        uiactionTagAppDEFieldId: 'action_tag',
                        uniqueTag: 'master__web_dynamic_ex_ua',
                        visibleScriptAppDEFieldId: 'visible_logic',
                        name: 'web扩展界面行为组（动态）',
                        id: 'web_dynamic_ex_ua',
                      },
                      codeName: 'buttonlist3',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTONLIST',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'buttonlist3',
                    },
                  ],
                  caption: '首项+分组展开',
                  codeName: 'grouppanel9',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel9',
                },
              ],
              caption: '表单按钮组',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  actionGroupExtractMode: 'ITEM',
                  contentControl: {
                    aggMode: 'NONE',
                    columnEnableFilter: 2,
                    columnEnableLink: 2,
                    groupMode: 'NONE',
                    groupStyle: 'DEFAULT',
                    degridColumns: [
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'name',
                        excelCaption: '项名称',
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        enableRowEdit: true,
                        aggMode: 'NONE',
                        align: 'LEFT',
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DETAIL.NAME',
                        },
                        caption: '项名称',
                        codeName: 'name',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 150,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'name',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'num',
                        excelCaption: '数量',
                        appDEFieldId: 'num',
                        valueType: 'SIMPLE',
                        enableRowEdit: true,
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '数量',
                        codeName: 'num',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'num',
                      },
                    ],
                    degridDataItems: [
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'name',
                      },
                      {
                        appDEFieldId: 'num',
                        valueType: 'SIMPLE',
                        dataType: 29,
                        id: 'num',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfkey',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfdataaccaction',
                      },
                      {
                        appDEFieldId: 'master_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'master_id',
                      },
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfmajortext',
                      },
                    ],
                    degridEditItems: [
                      {
                        caption: '项名称',
                        codeName: 'name',
                        enableCond: 3,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        id: 'name',
                      },
                      {
                        caption: '数量',
                        codeName: 'num',
                        enableCond: 3,
                        appDEFieldId: 'num',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'num',
                        },
                        allowEmpty: true,
                        id: 'num',
                      },
                      {
                        caption: '标识',
                        codeName: 'srfkey',
                        enableCond: 3,
                        appDEFieldId: 'id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfkey',
                        },
                        allowEmpty: true,
                        id: 'srfkey',
                      },
                    ],
                    pagingMode: 1,
                    pagingSize: 20,
                    sortMode: 'REMOTE',
                    hasWFDataItems: true,
                    enableCustomized: true,
                    enablePagingBar: true,
                    enableRowEdit: true,
                    enableRowNew: true,
                    navViewPos: 'NONE',
                    createControlAction: {
                      appDEMethodId: 'create',
                      appDataEntityId: 'web.detail',
                      id: 'create',
                    },
                    fetchControlAction: {
                      appDEMethodId: 'fetch_default',
                      appDataEntityId: 'web.detail',
                      id: 'fetch',
                    },
                    getDraftControlAction: {
                      appDEMethodId: 'get_draft',
                      appDataEntityId: 'web.detail',
                      id: 'loaddraft',
                    },
                    getControlAction: {
                      appDEMethodId: 'get',
                      appDataEntityId: 'web.detail',
                      id: 'load',
                    },
                    removeControlAction: {
                      appDEMethodId: 'remove',
                      appDataEntityId: 'web.detail',
                      id: 'remove',
                    },
                    updateControlAction: {
                      appDEMethodId: 'update',
                      appDataEntityId: 'web.detail',
                      id: 'update',
                    },
                    autoLoad: true,
                    showBusyIndicator: true,
                    codeName: 'main2',
                    controlType: 'GRID',
                    logicName: '表单多数据表格',
                    appDataEntityId: 'web.detail',
                    controlParam: {},
                    modelId: 'fec07763d9aca01df76bb83ae82ad802',
                    modelType: 'PSDEGRID',
                    name: 'mdctrl1_grid',
                    id: 'web.detail.main2',
                  },
                  contentType: 'GRID',
                  appDEFieldId: 'details',
                  uiactionGroup: {
                    dynamicMode: 1,
                    actionLevelAppDEFieldId: 'level',
                    buttonStyleAppDEFieldId: 'button_style',
                    clsAppDEFieldId: 'style',
                    detailAppDEDataSetId: 'fetch_web_data_set',
                    detailAppDataEntityId: 'web.ua_group_detail',
                    enableScriptAppDEFieldId: 'enable_logic',
                    iconClsAppDEFieldId: 'icon_cls',
                    appDataEntityId: 'web.master',
                    textAppDEFieldId: 'caption',
                    tipsAppDEFieldId: 'tooltip',
                    uiactionTagAppDEFieldId: 'action_tag',
                    uniqueTag: 'master__web_dynamic_ex_ua',
                    visibleScriptAppDEFieldId: 'visible_logic',
                    name: 'web扩展界面行为组（动态）',
                    id: 'web_dynamic_ex_ua',
                  },
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  caption: '扩展界面行为组（动态）',
                  codeName: 'mdctrl1',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'mdctrl1',
                },
              ],
              caption: '多数据部件',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.MASTER.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '动态界面行为组',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              actionGroupExtractMode: 'ITEM',
              uiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开弹窗',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_dialog@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'u6d34e27',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      dynamicMode: 1,
                      actionLevelAppDEFieldId: 'level',
                      buttonStyleAppDEFieldId: 'button_style',
                      clsAppDEFieldId: 'style',
                      detailAppDEDataSetId: 'fetch_web_data_set',
                      detailAppDataEntityId: 'web.ua_group_detail',
                      enableScriptAppDEFieldId: 'enable_logic',
                      iconClsAppDEFieldId: 'icon_cls',
                      appDataEntityId: 'web.master',
                      textAppDEFieldId: 'caption',
                      tipsAppDEFieldId: 'tooltip',
                      uiactionTagAppDEFieldId: 'action_tag',
                      uniqueTag: 'master__web_dynamic_ex_ua',
                      visibleScriptAppDEFieldId: 'visible_logic',
                      name: 'web扩展界面行为组（动态）',
                      id: 'web_dynamic_ex_ua',
                    },
                    showCaption: true,
                    showIcon: true,
                    id: 'u640401e',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开主表格视图',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_main_gridview@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'ud2b4df4',
                  },
                ],
                appDataEntityId: 'web.master',
                id: 'web成员为扩展界面行为组（动态）',
              },
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'formitem1',
                  },
                  allowEmpty: true,
                  caption: '搜索',
                  codeName: 'formitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'formitem1',
                },
              ],
              caption: '分组面板',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '按项展开：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem4',
                      },
                      codeName: 'rawitem4',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem4',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      buttonListType: 'UIACTIONGROUP',
                      uiactionGroup: {
                        uiactionGroupDetails: [
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            caption: '打开弹窗',
                            detailType: 'DEUIACTION',
                            uiactionId: 'open_dialog@master',
                            showCaption: true,
                            showIcon: true,
                            id: 'u6d34e27',
                          },
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            detailType: 'DEUIACTIONGROUP',
                            refUIActionGroup: {
                              dynamicMode: 1,
                              actionLevelAppDEFieldId: 'level',
                              buttonStyleAppDEFieldId: 'button_style',
                              clsAppDEFieldId: 'style',
                              detailAppDEDataSetId: 'fetch_web_data_set',
                              detailAppDataEntityId: 'web.ua_group_detail',
                              enableScriptAppDEFieldId: 'enable_logic',
                              iconClsAppDEFieldId: 'icon_cls',
                              appDataEntityId: 'web.master',
                              textAppDEFieldId: 'caption',
                              tipsAppDEFieldId: 'tooltip',
                              uiactionTagAppDEFieldId: 'action_tag',
                              uniqueTag: 'master__web_dynamic_ex_ua',
                              visibleScriptAppDEFieldId: 'visible_logic',
                              name: 'web扩展界面行为组（动态）',
                              id: 'web_dynamic_ex_ua',
                            },
                            showCaption: true,
                            showIcon: true,
                            id: 'u640401e',
                          },
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            caption: '打开主表格视图',
                            detailType: 'DEUIACTION',
                            uiactionId: 'open_main_gridview@master',
                            showCaption: true,
                            showIcon: true,
                            id: 'ud2b4df4',
                          },
                        ],
                        appDataEntityId: 'web.master',
                        id: 'web成员为扩展界面行为组（动态）',
                      },
                      codeName: 'buttonlist4',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTONLIST',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'buttonlist4',
                    },
                  ],
                  caption: '按项展开',
                  codeName: 'grouppanel10',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel10',
                },
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '按分组展开：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem5',
                      },
                      codeName: 'rawitem5',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem5',
                    },
                    {
                      actionGroupExtractMode: 'ITEMS',
                      buttonListType: 'UIACTIONGROUP',
                      uiactionGroup: {
                        uiactionGroupDetails: [
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            caption: '打开弹窗',
                            detailType: 'DEUIACTION',
                            uiactionId: 'open_dialog@master',
                            showCaption: true,
                            showIcon: true,
                            id: 'u6d34e27',
                          },
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            detailType: 'DEUIACTIONGROUP',
                            refUIActionGroup: {
                              dynamicMode: 1,
                              actionLevelAppDEFieldId: 'level',
                              buttonStyleAppDEFieldId: 'button_style',
                              clsAppDEFieldId: 'style',
                              detailAppDEDataSetId: 'fetch_web_data_set',
                              detailAppDataEntityId: 'web.ua_group_detail',
                              enableScriptAppDEFieldId: 'enable_logic',
                              iconClsAppDEFieldId: 'icon_cls',
                              appDataEntityId: 'web.master',
                              textAppDEFieldId: 'caption',
                              tipsAppDEFieldId: 'tooltip',
                              uiactionTagAppDEFieldId: 'action_tag',
                              uniqueTag: 'master__web_dynamic_ex_ua',
                              visibleScriptAppDEFieldId: 'visible_logic',
                              name: 'web扩展界面行为组（动态）',
                              id: 'web_dynamic_ex_ua',
                            },
                            showCaption: true,
                            showIcon: true,
                            id: 'u640401e',
                          },
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            caption: '打开主表格视图',
                            detailType: 'DEUIACTION',
                            uiactionId: 'open_main_gridview@master',
                            showCaption: true,
                            showIcon: true,
                            id: 'ud2b4df4',
                          },
                        ],
                        appDataEntityId: 'web.master',
                        id: 'web成员为扩展界面行为组（动态）',
                      },
                      caption: '成员为扩展界面行为组（动态）',
                      codeName: 'buttonlist5',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTONLIST',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'buttonlist5',
                    },
                  ],
                  caption: '按分组展开',
                  codeName: 'grouppanel11',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel11',
                },
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '首项+分组展开：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem6',
                      },
                      codeName: 'rawitem6',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem6',
                    },
                    {
                      actionGroupExtractMode: 'ITEMX',
                      buttonListType: 'UIACTIONGROUP',
                      uiactionGroup: {
                        uiactionGroupDetails: [
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            caption: '打开弹窗',
                            detailType: 'DEUIACTION',
                            uiactionId: 'open_dialog@master',
                            showCaption: true,
                            showIcon: true,
                            id: 'u6d34e27',
                          },
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            detailType: 'DEUIACTIONGROUP',
                            refUIActionGroup: {
                              dynamicMode: 1,
                              actionLevelAppDEFieldId: 'level',
                              buttonStyleAppDEFieldId: 'button_style',
                              clsAppDEFieldId: 'style',
                              detailAppDEDataSetId: 'fetch_web_data_set',
                              detailAppDataEntityId: 'web.ua_group_detail',
                              enableScriptAppDEFieldId: 'enable_logic',
                              iconClsAppDEFieldId: 'icon_cls',
                              appDataEntityId: 'web.master',
                              textAppDEFieldId: 'caption',
                              tipsAppDEFieldId: 'tooltip',
                              uiactionTagAppDEFieldId: 'action_tag',
                              uniqueTag: 'master__web_dynamic_ex_ua',
                              visibleScriptAppDEFieldId: 'visible_logic',
                              name: 'web扩展界面行为组（动态）',
                              id: 'web_dynamic_ex_ua',
                            },
                            showCaption: true,
                            showIcon: true,
                            id: 'u640401e',
                          },
                          {
                            actionLevel: 100,
                            afterItemType: 'NONE',
                            beforeItemType: 'NONE',
                            buttonStyle: 'DEFAULT',
                            caption: '打开主表格视图',
                            detailType: 'DEUIACTION',
                            uiactionId: 'open_main_gridview@master',
                            showCaption: true,
                            showIcon: true,
                            id: 'ud2b4df4',
                          },
                        ],
                        appDataEntityId: 'web.master',
                        id: 'web成员为扩展界面行为组（动态）',
                      },
                      codeName: 'buttonlist6',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTONLIST',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'buttonlist6',
                    },
                  ],
                  caption: '首项+分组展开',
                  codeName: 'grouppanel12',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel12',
                },
              ],
              caption: '表单按钮组',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  actionGroupExtractMode: 'ITEM',
                  contentControl: {
                    aggMode: 'NONE',
                    columnEnableFilter: 2,
                    columnEnableLink: 2,
                    groupMode: 'NONE',
                    groupStyle: 'DEFAULT',
                    degridColumns: [
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'name',
                        excelCaption: '项名称',
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        enableRowEdit: true,
                        aggMode: 'NONE',
                        align: 'LEFT',
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DETAIL.NAME',
                        },
                        caption: '项名称',
                        codeName: 'name',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 150,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'name',
                      },
                      {
                        clconvertMode: 'NONE',
                        dataItemName: 'num',
                        excelCaption: '数量',
                        appDEFieldId: 'num',
                        valueType: 'SIMPLE',
                        enableRowEdit: true,
                        aggMode: 'NONE',
                        align: 'LEFT',
                        caption: '数量',
                        codeName: 'num',
                        columnType: 'DEFGRIDCOLUMN',
                        noPrivDisplayMode: 1,
                        width: 100,
                        widthUnit: 'PX',
                        enableSort: true,
                        id: 'num',
                      },
                    ],
                    degridDataItems: [
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'name',
                      },
                      {
                        appDEFieldId: 'num',
                        valueType: 'SIMPLE',
                        dataType: 29,
                        id: 'num',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfkey',
                      },
                      {
                        appDEFieldId: 'id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfdataaccaction',
                      },
                      {
                        appDEFieldId: 'master_id',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'master_id',
                      },
                      {
                        appDEFieldId: 'name',
                        valueType: 'SIMPLE',
                        dataType: 25,
                        id: 'srfmajortext',
                      },
                    ],
                    degridEditItems: [
                      {
                        caption: '项名称',
                        codeName: 'name',
                        enableCond: 3,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        id: 'name',
                      },
                      {
                        caption: '数量',
                        codeName: 'num',
                        enableCond: 3,
                        appDEFieldId: 'num',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'num',
                        },
                        allowEmpty: true,
                        id: 'num',
                      },
                      {
                        caption: '标识',
                        codeName: 'srfkey',
                        enableCond: 3,
                        appDEFieldId: 'id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfkey',
                        },
                        allowEmpty: true,
                        id: 'srfkey',
                      },
                    ],
                    pagingMode: 1,
                    pagingSize: 20,
                    sortMode: 'REMOTE',
                    hasWFDataItems: true,
                    enableCustomized: true,
                    enablePagingBar: true,
                    enableRowEdit: true,
                    enableRowNew: true,
                    navViewPos: 'NONE',
                    createControlAction: {
                      appDEMethodId: 'create',
                      appDataEntityId: 'web.detail',
                      id: 'create',
                    },
                    fetchControlAction: {
                      appDEMethodId: 'fetch_default',
                      appDataEntityId: 'web.detail',
                      id: 'fetch',
                    },
                    getDraftControlAction: {
                      appDEMethodId: 'get_draft',
                      appDataEntityId: 'web.detail',
                      id: 'loaddraft',
                    },
                    getControlAction: {
                      appDEMethodId: 'get',
                      appDataEntityId: 'web.detail',
                      id: 'load',
                    },
                    removeControlAction: {
                      appDEMethodId: 'remove',
                      appDataEntityId: 'web.detail',
                      id: 'remove',
                    },
                    updateControlAction: {
                      appDEMethodId: 'update',
                      appDataEntityId: 'web.detail',
                      id: 'update',
                    },
                    autoLoad: true,
                    showBusyIndicator: true,
                    codeName: 'main2',
                    controlType: 'GRID',
                    logicName: '表单多数据表格',
                    appDataEntityId: 'web.detail',
                    controlParam: {},
                    modelId: 'fec07763d9aca01df76bb83ae82ad802',
                    modelType: 'PSDEGRID',
                    name: 'mdctrl2_grid',
                    id: 'web.detail.main2',
                  },
                  contentType: 'GRID',
                  appDEFieldId: 'details',
                  uiactionGroup: {
                    uiactionGroupDetails: [
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        buttonStyle: 'DEFAULT',
                        caption: '打开弹窗',
                        detailType: 'DEUIACTION',
                        uiactionId: 'open_dialog@master',
                        showCaption: true,
                        showIcon: true,
                        id: 'u6d34e27',
                      },
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        buttonStyle: 'DEFAULT',
                        detailType: 'DEUIACTIONGROUP',
                        refUIActionGroup: {
                          dynamicMode: 1,
                          actionLevelAppDEFieldId: 'level',
                          buttonStyleAppDEFieldId: 'button_style',
                          clsAppDEFieldId: 'style',
                          detailAppDEDataSetId: 'fetch_web_data_set',
                          detailAppDataEntityId: 'web.ua_group_detail',
                          enableScriptAppDEFieldId: 'enable_logic',
                          iconClsAppDEFieldId: 'icon_cls',
                          appDataEntityId: 'web.master',
                          textAppDEFieldId: 'caption',
                          tipsAppDEFieldId: 'tooltip',
                          uiactionTagAppDEFieldId: 'action_tag',
                          uniqueTag: 'master__web_dynamic_ex_ua',
                          visibleScriptAppDEFieldId: 'visible_logic',
                          name: 'web扩展界面行为组（动态）',
                          id: 'web_dynamic_ex_ua',
                        },
                        showCaption: true,
                        showIcon: true,
                        id: 'u640401e',
                      },
                      {
                        actionLevel: 100,
                        afterItemType: 'NONE',
                        beforeItemType: 'NONE',
                        buttonStyle: 'DEFAULT',
                        caption: '打开主表格视图',
                        detailType: 'DEUIACTION',
                        uiactionId: 'open_main_gridview@master',
                        showCaption: true,
                        showIcon: true,
                        id: 'ud2b4df4',
                      },
                    ],
                    appDataEntityId: 'web.master',
                    id: 'web成员为扩展界面行为组（动态）',
                  },
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  caption: '成员为扩展界面行为组（动态）',
                  codeName: 'mdctrl2',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'mdctrl2',
                },
              ],
              caption: '多数据部件',
              codeName: 'grouppanel6',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel6',
            },
          ],
          caption: '成员为动态界面行为组',
          codeName: 'formpage2',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage2',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main258',
      controlType: 'FORM',
      logicName: '表单_动态界面行为组_表单',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'form',
      },
      modelId: '0ef90493a44d9351e039d197d90268e1',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.master.main258',
    },
    {
      codeName: 'form_dy_uiaction_group_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'form_dy_uiaction_group_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '表单_动态界面行为组',
      codeName: 'form_dy_uiaction_group_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'form_dy_uiaction_group_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表单_动态界面行为组',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '76d114c2a61c9729396df764a463c8dc',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERform_dy_uiaction_group',
  id: 'web.master_form_dy_uiaction_group',
};
