export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tree_quicksearch_exp_view',
  deviewId: '6c7e6fa4ead1c6c952ea0778b1271c1e',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树视图_快速搜索分页导航视图',
  codeName: 'master_tree_quicksearch_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '快速搜索',
          appViewId: 'web.master_tree_search',
          id: 'quicksearch',
        },
        {
          caption: '快速搜索提示分隔符',
          appViewId: 'web.master_tree_searchphseparator',
          id: 'quicksearch_separator',
        },
      ],
      dataRelationTag: 'DataRelation172',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_tree_quicksearch_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation172',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'bed6f048dadcc92a36e778a866e9b58c',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation172',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树视图_快速搜索分页导航视图',
      codeName: 'tree_quicksearch_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_quicksearch_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树视图_快速搜索分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4a867affb67a617aee02403af5f7aa4f',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtree_quicksearch_exp_view',
  id: 'web.master_tree_quicksearch_exp_view',
};
