export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'drbar_logic',
  deviewId: '631a992faa85b6ed309a230cadd25f2f',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '数据关系栏_逻辑',
  codeName: 'master_drbar_logic',
  height: 700,
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'MASTER',
      value: 'sample',
      name: 'MASTER',
      id: 'master',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '脚本',
          appViewId: 'web.master_drbar_logic_script',
          id: 'script',
        },
        {
          caption: '计数器',
          appViewId: 'web.master_drbar_logic_count',
          id: 'count',
        },
        {
          caption: '实体逻辑',
          appViewId: 'web.master_drbar_logic_delogic',
          id: 'delogic',
        },
      ],
      dataRelationTag: 'DataRelation109',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_drbar_logic__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation109',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'da5c72280f89fd03ed809e70971a45b5',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation109',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '数据关系栏_逻辑',
      codeName: 'drbar_logic_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'drbar_logic_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据关系栏_逻辑',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd79438c8061e26a0c569612628f3cadc',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdrbar_logic',
  id: 'web.master_drbar_logic',
};
