export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'screenCompTabExpView',
  deviewId: '9d1e57acccc5be42442d224972cfcc8c',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '大屏组件',
  codeName: 'master_screen_comp_tab_exp_view',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '装饰器',
          appViewId: 'web.master_decoration_dashboard_view',
          id: 'decoration',
        },
        {
          caption: '边框',
          appViewId: 'web.master_screen_border_dashboard_view',
          id: 'border',
        },
        {
          caption: '编辑器',
          appViewId: 'web.master_editor_dashboard_view',
          id: 'editor',
        },
        {
          caption: '按钮',
          appViewId: 'web.master_custom_btn_dashboard_view',
          id: 'button',
        },
      ],
      dataRelationTag: 'DataRelation153',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_screen_comp_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation153',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'eb6ad9b4a027bdcf51e334ab6fa366a4',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation153',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '大屏组件',
      codeName: 'screen_comp_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'screen_comp_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '大屏组件',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5351dc481d17c2d17514168f7915b9a8',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERscreenCompTabExpView',
  id: 'web.master_screen_comp_tab_exp_view',
};
