export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'treegridex',
  loadDefault: true,
  deviewCodeName: 'treegridex_column_dy_uiaction_group_embed',
  deviewId: 'aa65ac18034ebb725788c9e8ab4b61e5',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '树表格增强_成员为动态界面行为组',
  codeName: 'master_treegridex_column_dy_uiaction_group_embed',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeGridExView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup312',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '主数据编辑视图',
      refAppViewId: 'web.master_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detreeColumns: [
        {
          align: 'CENTER',
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          width: 300,
          widthUnit: 'px',
          id: 'name',
        },
        {
          align: 'CENTER',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          width: 200,
          widthUnit: 'px',
          id: 'code',
        },
        {
          align: 'CENTER',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          width: 100,
          widthUnit: 'STAR',
          id: 'status',
        },
        {
          align: 'CENTER',
          caption: '操作',
          codeName: 'treecol',
          columnType: 'UAGRIDCOLUMN',
          width: 350,
          widthUnit: 'px',
          id: 'treecol',
        },
      ],
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'node',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
        {
          childDETreeNodeId: 'node',
          parentAppDEFieldId: 'parent_id',
          parentDER1N: {
            pickupDEFName: 'PARENT_ID',
            codeName: 'parent',
            dertype: 'DER1N',
            logicName: '父项',
            orderValue: 100,
            serviceCodeName: 'parent',
            name: 'DER1N_CATEGORY_CATEGORY_PARENT_ID',
            id: 'mock.category.der1n_category_category_parent_id',
          },
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: 'null - null',
        },
      ],
      detreeNodes: [
        {
          nodeValue: '86',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'leaf',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'node',
          appDataEntityId: 'web.region',
          detreeNodeColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'code',
              appDEFieldId: 'code',
              valueType: 'SIMPLE',
              codeName: 'code',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'code',
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              appDEFieldId: 'name',
              deuiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开关于',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_about@region',
                    showCaption: true,
                    showIcon: true,
                    sysImage: {
                      cssClass: 'fa fa-info-circle',
                      glyph: 'xf05a@FontAwesome',
                    },
                    id: 'u28075ca',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      dynamicMode: 1,
                      actionLevelAppDEFieldId: 'level',
                      buttonStyleAppDEFieldId: 'button_style',
                      clsAppDEFieldId: 'style',
                      detailAppDEDataSetId: 'fetch_web_data_set',
                      detailAppDataEntityId: 'web.ua_group_detail',
                      enableScriptAppDEFieldId: 'enable_logic',
                      iconClsAppDEFieldId: 'icon_cls',
                      appDataEntityId: 'web.region',
                      textAppDEFieldId: 'caption',
                      tipsAppDEFieldId: 'tooltip',
                      uiactionTagAppDEFieldId: 'action_tag',
                      uniqueTag: 'region__dynamic_ex_ua',
                      visibleScriptAppDEFieldId: 'visible_logic',
                      name: 'web扩展界面行为组（动态）',
                      id: 'dynamic_ex_ua',
                    },
                    showCaption: true,
                    showIcon: true,
                    id: 'u946f3a0',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开文档',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_document@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'u9178bd4',
                  },
                ],
                appDataEntityId: 'web.region',
                id: '成员为扩展界面行为组（动态）',
              },
              valueType: 'SIMPLE',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'name',
              id: 'name',
            },
            {
              clconvertMode: 'FRONT',
              dataItemName: 'status',
              appCodeListId: 'web.mock__cl_status',
              appDEFieldId: 'status',
              valueType: 'SIMPLE',
              codeName: 'status',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'status',
              id: 'status',
            },
            {
              deuiactionGroup: {
                uiactionGroupDetails: [
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开关于',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_about@region',
                    showCaption: true,
                    showIcon: true,
                    sysImage: {
                      cssClass: 'fa fa-info-circle',
                      glyph: 'xf05a@FontAwesome',
                    },
                    id: 'u28075ca',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    detailType: 'DEUIACTIONGROUP',
                    refUIActionGroup: {
                      dynamicMode: 1,
                      actionLevelAppDEFieldId: 'level',
                      buttonStyleAppDEFieldId: 'button_style',
                      clsAppDEFieldId: 'style',
                      detailAppDEDataSetId: 'fetch_web_data_set',
                      detailAppDataEntityId: 'web.ua_group_detail',
                      enableScriptAppDEFieldId: 'enable_logic',
                      iconClsAppDEFieldId: 'icon_cls',
                      appDataEntityId: 'web.region',
                      textAppDEFieldId: 'caption',
                      tipsAppDEFieldId: 'tooltip',
                      uiactionTagAppDEFieldId: 'action_tag',
                      uniqueTag: 'region__dynamic_ex_ua',
                      visibleScriptAppDEFieldId: 'visible_logic',
                      name: 'web扩展界面行为组（动态）',
                      id: 'dynamic_ex_ua',
                    },
                    showCaption: true,
                    showIcon: true,
                    id: 'u946f3a0',
                  },
                  {
                    actionLevel: 100,
                    afterItemType: 'NONE',
                    beforeItemType: 'NONE',
                    buttonStyle: 'DEFAULT',
                    caption: '打开文档',
                    detailType: 'DEUIACTION',
                    uiactionId: 'open_document@master',
                    showCaption: true,
                    showIcon: true,
                    id: 'u9178bd4',
                  },
                ],
                appDataEntityId: 'web.region',
                id: '成员为扩展界面行为组（动态）',
              },
              codeName: 'treecol',
              columnType: 'UAGRIDCOLUMN',
              noPrivDisplayMode: 1,
              detreeColumnId: 'treecol',
              id: 'treecol',
            },
          ],
          detreeNodeDataItems: [
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'code',
              detreeColumnId: 'code',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'code',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'name',
              detreeColumnId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              appDEFieldId: 'status',
              detreeColumnId: 'status',
              valueType: 'SIMPLE',
              dataType: 9,
              id: 'status',
            },
            {
              clconvertMode: 'NONE',
              detreeColumnId: 'treecol',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'treecol',
            },
          ],
          detreeNodeRVs: [
            {
              refAppViewId: 'web.region_edit_view',
              id: 'newdata',
            },
            {
              refAppViewId: 'web.region_edit_view',
              id: 'editdata',
            },
            {
              refAppViewId: 'web.region_edit_view',
              id: 'opendata',
            },
          ],
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          enableEditData: true,
          enableNewData: true,
          enableRemoveData: true,
          enableViewData: true,
          name: '区域数据',
          id: 'node',
        },
      ],
      treeGridMode: 1,
      outputIconDefault: true,
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      appViewLogics: [
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            actionAfterWizard: 'DEFAULT',
            newDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.region_edit_view',
            },
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.region_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_NEWDATA',
            id: '新建数据',
          },
          builtinLogic: true,
          id: 'node_newdata',
        },
        {
          logicTrigger: 'CUSTOM',
          logicType: 'APPUILOGIC',
          builtinAppUILogic: {
            openDataAppView: {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.region_edit_view',
            },
            editMode: true,
            appUILogicRefViews: [
              {
                openMode: 'POPUPMODAL',
                refAppViewId: 'web.region_edit_view',
              },
            ],
            builtinLogic: true,
            logicType: 'PREDEFINED',
            viewLogicType: 'APP_OPENDATA',
            id: '打开数据',
          },
          builtinLogic: true,
          id: 'node_opendata',
        },
      ],
      codeName: 'treegridex_column_dy_uiaction_group_embed',
      controlType: 'TREEGRIDEX',
      logicName: '树表格增强_成员为动态界面行为组_树表格',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'treegridex',
      },
      modelId: 'e98475283faada35cddd4e0aa52b8f5a',
      modelType: 'PSDETREEGRIDEX',
      name: 'treegridex',
      id: 'web.master.treegridex_column_dy_uiaction_group_embed',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '树表格增强_成员为动态界面行为组',
      codeName: 'treegridex_column_dy_uiaction_group_embed_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'treegridex_column_dy_uiaction_group_embed_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEGRIDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格增强_成员为动态界面行为组',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDEXVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a208c8fe98604aed40c20214428fbb23',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERtreegridex_column_dy_uiaction_group_embed',
  id: 'web.master_treegridex_column_dy_uiaction_group_embed',
};
