export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'drtab_postion',
  deviewId: '0c889b9fc3719769c82ad0f997db74f9',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '数据关系分页_位置',
  codeName: 'master_drtab_postion',
  height: 800,
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '上方',
          appViewId: 'web.master_drtab_top',
          id: 'top',
        },
        {
          caption: '左侧',
          appViewId: 'web.master_drtab_left',
          id: 'left',
        },
        {
          caption: '右侧',
          appViewId: 'web.master_drtab_right',
          id: 'right',
        },
        {
          caption: '下方',
          appViewId: 'web.master_drtab_bottom',
          id: 'bottom',
        },
        {
          caption: '上方(下拉)',
          appViewId: 'web.master_drtab_dropdown',
          id: 'dropdown',
        },
      ],
      dataRelationTag: 'DataRelation34',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_drtab_postion__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation34',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '618a86edc2b6e838e548a9c5718a55e7',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation34',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '数据关系分页_位置',
      codeName: 'drtab_postion_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'drtab_postion_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '数据关系分页_位置',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '6f4be8ca59123fc7f97a1fb5901c93c2',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERdrtab_postion',
  id: 'web.master_drtab_postion',
};
