export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'calendar_layout_timeline',
  deviewId: '2448bc6b7ec12be570de864472bab9d3',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_项布局_时间轴',
  codeName: 'master_calendar_layout_timeline',
  appDataEntityId: 'web.master',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      calendarStyle: 'TIMELINE',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          endTimeAppDEFieldId: 'end_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          layoutPanel: {
            layoutMode: 'FLEX',
            layout: {
              layout: 'FLEX',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-tags',
                            glyph: 'xf02c@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          predefinedType: 'STATIC_IMAGE',
                          rawItemHeight: 16,
                          id: 'static_image',
                        },
                        caption: '图片',
                        contentHeight: 16,
                        height: 16,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          height: 16,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          spacingLeft: 'OUTERSMALL',
                        },
                        sysImage: {
                          cssClass: 'fa fa-tags',
                          glyph: 'xf02c@FontAwesome',
                        },
                        showCaption: true,
                        id: 'static_image',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container1',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layoutPanel: true,
            codeName: 'usr0515490940',
            controlType: 'PANEL',
            logicName: '日历_项布局面板',
            appDataEntityId: 'web.master',
            controlParam: {},
            modelId: '46da009e9d82a2836d629283c646fc43',
            modelType: 'PSSYSVIEWPANEL',
            name: 'masterlayoutpanel',
            id: 'web.master.usr0515490940',
          },
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.master',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'calendar_layout_timeline',
      controlType: 'CALENDAR',
      height: 650,
      logicName: '日历_项布局_时间轴',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'calendar',
      },
      modelId: '4b01643c1a808c2761c3e08055b1bdbe',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.master.calendar_layout_timeline',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_项布局_时间轴',
      codeName: 'calendar_layout_timeline_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_layout_timeline_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_项布局_时间轴',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'df913fbbaa6e9b4705b86fc328427d93',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_layout_timeline',
  id: 'web.master_calendar_layout_timeline',
};
