export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'calendar_nav_multiple_data_nav',
  deviewId: 'acc5d52d92d2695e9cd4a805f455f55e',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '日历_内置导航_多数据源_导航视图',
  codeName: 'master_calendar_nav_multiple_data_nav',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '右侧导航栏',
          appViewId: 'web.master_calendar_rightnav_multiple_data',
          id: 'rightnav',
        },
        {
          caption: '下方导航栏',
          appViewId: 'web.master_calendar_bottomnav_multiple_data',
          id: 'bottomnav',
        },
      ],
      dataRelationTag: 'DataRelation118',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_calendar_nav_multiple_data_nav__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation118',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        ctrlParams: {
          ENABLENAVBAR: 'false',
        },
        id: 'tabexppanel',
      },
      modelId: '41f7c01464e2290df95e78a660610754',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation118',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '日历_内置导航_多数据源_导航视图',
      codeName: 'calendar_nav_multiple_data_nav_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'calendar_nav_multiple_data_nav_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '日历_内置导航_多数据源_导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '875dfb388003be9ac30448e9c3f24f09',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcalendar_nav_multiple_data_nav',
  id: 'web.master_calendar_nav_multiple_data_nav',
};
