export default {
  deviewCodeName: 'panel_multi_data_container',
  deviewId: 'c61a3876e458512e8aa50917ab313a47',
  appWFId: 'workflow',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '面板_多项数据容器',
  codeName: 'master_panel_multi_data_container',
  appDataEntityId: 'web.master',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '名称',
                          halign: 'LEFT',
                          renderMode: 'PARAGRAPH',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_LABEL',
                          rawItemWidth: 120,
                          id: 'static_label24',
                        },
                        caption: '标签',
                        contentWidth: 120,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'RIGHT',
                          layout: 'FLEX',
                          spacingRight: 'INNERSMALL',
                          width: 120,
                          widthMode: 'PX',
                        },
                        width: 120,
                        showCaption: true,
                        id: 'static_label24',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_text_dynamic4',
                        },
                        viewFieldName: 'name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'field_text_dynamic4',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    cssStyle: 'line-height: 32px;',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'container39',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container36',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '状态',
                          halign: 'LEFT',
                          renderMode: 'PARAGRAPH',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_LABEL',
                          rawItemWidth: 120,
                          id: 'static_label25',
                        },
                        caption: '标签',
                        contentWidth: 120,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'RIGHT',
                          layout: 'FLEX',
                          spacingRight: 'INNERSMALL',
                          width: 120,
                          widthMode: 'PX',
                        },
                        width: 120,
                        showCaption: true,
                        id: 'static_label25',
                      },
                      {
                        editor: {
                          singleSelect: true,
                          appCodeListId: 'web.mock__cl_status',
                          editorType: 'DROPDOWNLIST',
                          predefinedType: 'FIELD_DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_dropdownlist1',
                        },
                        viewFieldName: 'status',
                        allowEmpty: true,
                        caption: '下拉列表框',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'field_dropdownlist1',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'container40',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container37',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '所属分类',
                          halign: 'LEFT',
                          renderMode: 'PARAGRAPH',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_LABEL',
                          rawItemWidth: 120,
                          id: 'static_label26',
                        },
                        caption: '标签',
                        contentWidth: 120,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'RIGHT',
                          layout: 'FLEX',
                          spacingRight: 'INNERSMALL',
                          width: 120,
                          widthMode: 'PX',
                        },
                        width: 120,
                        showCaption: true,
                        id: 'static_label26',
                      },
                      {
                        editor: {
                          singleSelect: true,
                          appCodeListId: 'web.mock__cl_sample',
                          editorType: 'DROPDOWNLIST',
                          predefinedType: 'FIELD_DROPDOWNLIST',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_dropdownlist2',
                        },
                        viewFieldName: 'categories',
                        allowEmpty: true,
                        caption: '下拉列表框',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'field_dropdownlist2',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'container41',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container38',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid5',
          },
          {
            rawItem: {
              contentType: 'DIVIDER',
              predefinedType: 'DIVIDER',
              id: 'divider',
            },
            caption: '分割线',
            itemStyle: 'DEFAULT',
            itemType: 'RAWITEM',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'divider',
          },
        ],
        predefinedType: 'CONTAINER_MULTIDATA',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'MULTIDATA',
        dataSourceType: 'DEDATASET',
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.master',
        navigateParams: [
          {
            key: 'size',
            value: '3',
            rawValue: true,
            id: 'size',
          },
        ],
        caption: '多项数据容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_multidata',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.MASTER',
        },
        caption: '面板_多项数据容器',
        codeName: 'panel_multi_data_container_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.master',
        controlParam: {},
        name: 'captionbar',
        id: 'panel_multi_data_container_captionbar',
      },
    ],
    codeName: 'a5a62818665f34688af',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'panel_multi_data_container',
    appDataEntityId: 'web.master',
    controlParam: {},
    modelId: 'ec24e61647fa41668183c21e86a73b24',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a5a62818665f34688af',
  },
  title: '面板_多项数据容器',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '93280dd4e66ef5b59858dd66d65a4c58',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERpanel_multi_data_container',
  id: 'web.master_panel_multi_data_container',
};
