export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'card_dyna_logic_exp',
  deviewId: '9F615AA3-2E8C-4859-A840-E0608236622D',
  appWFId: 'workflow',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.MASTER',
  },
  caption: '卡片_动态逻辑导航视图',
  codeName: 'master_card_dyna_logic_exp',
  appDataEntityId: 'web.master',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '动态启用',
          appViewId: 'web.master_card_dyna_enbale',
          id: 'card_dyna_enable',
        },
        {
          caption: '动态显示',
          appViewId: 'web.master_card_dyna_visible',
          id: 'card_dyna_visible',
        },
        {
          caption: '动态空输入',
          appViewId: 'web.master_card_dyna_blank',
          id: 'card_dyna_blank',
        },
      ],
      dataRelationTag: 'DataRelation39',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      editItemCaption: '主数据',
      uniqueTag: 'master_card_dyna_logic_exp__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation39',
      controlType: 'DRTAB',
      appDataEntityId: 'web.master',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '7AE45ABB-0682-4287-A68F-788248C33F4A',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation39',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.MASTER',
      },
      caption: '卡片_动态逻辑导航视图',
      codeName: 'card_dyna_logic_exp_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.master',
      controlParam: {},
      name: 'captionbar',
      id: 'card_dyna_logic_exp_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.master',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '卡片_动态逻辑导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'bffcffa5fc1ba00dcef29273b76d15e6',
  modelType: 'PSAPPDEVIEW',
  name: 'MASTERcard_dyna_logic_exp',
  id: 'web.master_card_dyna_logic_exp',
};
