export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'TreeGrid_basetabexpview',
  deviewId: '33067ead905ef77a271bca1882231405',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '树表格_基础分页导航视图',
  codeName: 'region_tree_grid_basetabexpview',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础树表格',
          appViewId: 'web.region_tree_grid_base',
          id: 'treegrid_base',
        },
        {
          caption: '无值显示内容',
          appViewId: 'web.region_tree_grid_emptydata',
          id: 'treegrid_emptydata',
        },
        {
          caption: '不显示头部',
          appViewId: 'web.region_tree_grid_noheader',
          id: 'treegrid_noheader',
        },
        {
          caption: '支持单选',
          appViewId: 'web.region_tree_grid_single',
          id: 'treegrid_single',
        },
        {
          caption: '适应屏宽',
          appViewId: 'web.region_tree_grid_autowidth',
          id: 'treegeid_autowidth',
        },
        {
          caption: '禁用列定制',
          appViewId: 'web.region_tree_grid_disablecolcustom',
          id: 'treegrid_disablecolcustom',
        },
      ],
      dataRelationTag: 'DataRelation8',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_tree_grid_basetabexpview__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation8',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '3985238d65d4f651d08b7ca58c228578',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation8',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '树表格_基础分页导航视图',
      codeName: 'tree_grid_basetabexpview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_grid_basetabexpview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格_基础分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '91d040c164b4aaa169dcfc329ad2745b',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONTreeGrid_basetabexpview',
  id: 'web.region_tree_grid_basetabexpview',
};
