export default {
  gridRowActiveMode: 2,
  loadDefault: true,
  deviewCodeName: 'TreeGrid_remoteagg',
  deviewId: '14baa3d4b8623a530ab0894d31dc8d05',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '树表格_远程聚合',
  codeName: 'region_tree_grid_remoteagg',
  appDataEntityId: 'web.region',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'treegrid_remoteagg',
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'ALL',
      aggAppDEDataSetId: 'fetch_agg_data',
      aggAppDataEntityId: 'web.region',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      gridStyle: 'TREEGRID',
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggField: 'name',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFTREEGRIDCOLUMN',
          hideMode: 3,
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'code',
          excelCaption: '编码',
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          aggField: 'code',
          aggMode: 'SUM',
          align: 'LEFT',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'code',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          aggField: 'status',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'id',
          excelCaption: '标识',
          appDEFieldId: 'id',
          treeColumnMode: 2,
          valueType: 'SIMPLE',
          aggField: 'id',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.ID',
          },
          caption: '标识',
          codeName: 'id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hiddenDataItem: true,
          id: 'id',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'parent_id',
          excelCaption: '上级区划标识',
          appDEFieldId: 'parent_id',
          treeColumnMode: 4,
          valueType: 'SIMPLE',
          aggField: 'parent_id',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '上级区划标识',
          codeName: 'parent_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hiddenDataItem: true,
          id: 'parent_id',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'code',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.region',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'treegrid_remoteagg',
      controlType: 'TREEGRID',
      logicName: '树表格_远程聚合',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'treegrid',
      },
      modelId: '61f70290d06000eaf0019b7a27c843c3',
      modelType: 'PSDEGRID',
      name: 'treegrid',
      id: 'web.region.treegrid_remoteagg',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main26',
      controlType: 'SEARCHFORM',
      logicName: '树表格_远程聚合_搜索表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'c35cd9c2e6374582c77694e9462c809f',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.region.main26',
    },
    {
      codeName: 'tree_grid_remoteagg_toolbar',
      controlType: 'TOOLBAR',
      logicName: '树表格_远程聚合_工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '2b82b200a9e077bb18fd7e499232c2eb',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'tree_grid_remoteagg_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '树表格_远程聚合',
      codeName: 'tree_grid_remoteagg_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_grid_remoteagg_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格_远程聚合',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9a863355cfc426f3d7d55034d4d00264',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONTreeGrid_remoteagg',
  id: 'web.region_tree_grid_remoteagg',
};
