export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'grid_message',
  deviewId: '3f71d49532669ebd578cb3944ee09043',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '基础表格_聊天窗口',
  codeName: 'region_grid_message',
  appDataEntityId: 'web.region',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        xdataControlName: 'form',
        codeName: 'grid_message_toolbar',
        controlType: 'TOOLBAR',
        logicName: '基础表格_聊天窗口_工具栏',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '4510cc1dabef6292cd97852021f48f78',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_message_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'code',
            excelCaption: '编码',
            appDEFieldId: 'code',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '编码',
            codeName: 'code',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'code',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.REGION.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'parent_id',
            excelCaption: '上级区划标识',
            appDEFieldId: 'parent_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '上级区划标识',
            codeName: 'parent_id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'parent_id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'level',
            excelCaption: '级别',
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '级别',
            codeName: 'level',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'level',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'web.mock__cl_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'path',
            excelCaption: '全路径',
            appDEFieldId: 'path',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '全路径',
            codeName: 'path',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'path',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'sort',
            excelCaption: '排序',
            appDEFieldId: 'sort',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '排序',
            codeName: 'sort',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'sort',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'longitude',
            excelCaption: '经度',
            appDEFieldId: 'longitude',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '经度',
            codeName: 'longitude',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'longitude',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'latitude',
            excelCaption: '纬度',
            appDEFieldId: 'latitude',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '纬度',
            codeName: 'latitude',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'latitude',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'update_time',
            excelCaption: '更新时间',
            appDEFieldId: 'update_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_TIME',
            },
            caption: '更新时间',
            codeName: 'update_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'update_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'create_time',
            excelCaption: '创建时间',
            appDEFieldId: 'create_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.REGION.CREATE_TIME',
            },
            caption: '创建时间',
            codeName: 'create_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_time',
          },
          {
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 100,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  caption: 'AI辅助',
                  detailType: 'DEUIACTION',
                  uiactionId: 'ai_view@region',
                  showCaption: true,
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-lightbulb-o',
                    glyph: 'xf0eb@FontAwesome',
                  },
                  id: 'u87d1e3f',
                },
              ],
              appDataEntityId: 'web.region',
              uniqueTag: 'region__Abb6c827226e13157d3',
              name: '表格操作列_AI辅助',
              id: 'abb6c827226e13157d3',
            },
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '操作',
            codeName: 'uagridcolumn1',
            columnType: 'UAGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'uagridcolumn1',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'code',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'code',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'parent_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'parent_id',
          },
          {
            appDEFieldId: 'level',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'level',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'status',
          },
          {
            appDEFieldId: 'path',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'path',
          },
          {
            appDEFieldId: 'sort',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'sort',
          },
          {
            appDEFieldId: 'longitude',
            valueType: 'SIMPLE',
            dataType: 29,
            id: 'longitude',
          },
          {
            appDEFieldId: 'latitude',
            valueType: 'SIMPLE',
            dataType: 29,
            id: 'latitude',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 10,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        enableRowEdit: true,
        enableRowNew: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.region',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'web.region',
          id: 'fetch',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.region',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.region',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.region',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.region',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'ai_grid',
        controlType: 'GRID',
        logicName: 'AI辅助表格',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'grid',
        },
        modelId: 'C942D101-B4AB-4CE2-A59C-B9047B805453',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.region.ai_grid',
      },
      {
        codeName: 'grid_message_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'web.region',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'grid_message_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.REGION',
        },
        caption: '基础表格_聊天窗口',
        codeName: 'grid_message_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.region',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_message_captionbar',
      },
    ],
    codeName: 'a990de267beaf54c89b',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'grid_message编辑视图布局面板',
    appDataEntityId: 'web.region',
    controlParam: {},
    modelId: '2eb2557fb38c7ec7bb457de68b7e6fe8',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'a990de267beaf54c89b',
  },
  title: '基础表格_聊天窗口',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'abac62c5839caef745b8e87b4bacd42b',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONgrid_message',
  id: 'web.region_grid_message',
};
