export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'gridTabCacheTabExpView',
  deviewId: '2826f079a207ad7633c90ef5f9cdfa55',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '表格导航栏_缓存分页',
  codeName: 'region_grid_tab_cache_tab_exp_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup31',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '启用缓存',
          appViewId: 'web.region_grid_cache_grid_exp_view',
          id: 'cache',
        },
        {
          caption: '不启用缓存',
          appViewId: 'web.region_grid_no_cacha_grid_exp_view',
          id: 'no_cache',
        },
      ],
      dataRelationTag: 'DataRelation4',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_grid_tab_cache_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation4',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'b061ee7c973f3b02eaa57ca2445c8e11',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation4',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '表格导航栏_缓存分页',
      codeName: 'grid_tab_cache_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_tab_cache_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格导航栏_缓存分页',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c8ba835fd2ff22fc4290da33410855ff',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONgridTabCacheTabExpView',
  id: 'web.region_grid_tab_cache_tab_exp_view',
};
