export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'listTabCacheTabExpView',
  deviewId: 'ea14b77b49f5cfb31d0ef55fceacd7ae',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '列表导航_缓存分页',
  codeName: 'region_list_tab_cache_tab_exp_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  appViewMsgGroupId: 'vmgroup35',
  controls: [
    {
      dedrtabPages: [
        {
          caption: '启用缓存',
          appViewId: 'web.region_list_cache_list_exp_view',
          id: 'cache',
        },
        {
          caption: '不启用缓存',
          appViewId: 'web.region_list_nocache_list_exp_view',
          id: 'no_cache',
        },
      ],
      dataRelationTag: 'DataRelation6',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_list_tab_cache_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation6',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '49814ff02d88bb769274e2f78292d12a',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation6',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '列表导航_缓存分页',
      codeName: 'list_tab_cache_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'list_tab_cache_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '列表导航_缓存分页',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '46b95a3ccb0ebc72eb4c19a0ad99e235',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONlistTabCacheTabExpView',
  id: 'web.region_list_tab_cache_tab_exp_view',
};
