export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'meditpanel_base',
  deviewId: '55345108c8b54e839d650e51e568c701',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '多编辑面板_基础',
  codeName: 'region_meditpanel_base',
  height: 700,
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '上分页',
          appViewId: 'web.region_meditpanel_top',
          id: 'top',
        },
        {
          caption: '行记录',
          appViewId: 'web.region_meditpanel_row',
          id: 'row',
        },
      ],
      dataRelationTag: 'DataRelation21',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_meditpanel_base__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation21',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '879456443053fc81ba48a074fecd09b3',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation21',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '多编辑面板_基础',
      codeName: 'meditpanel_base_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'meditpanel_base_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '多编辑面板_基础',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ebef8628baa44c4eaa02d20d01041707',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONmeditpanel_base',
  id: 'web.region_meditpanel_base',
};
