export default {
  gridRowActiveMode: 2,
  loadDefault: true,
  deviewCodeName: 'TreeGrid_quicktoolbar',
  deviewId: 'ef63b7fbd0e9c38d9d92882e079c33d2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '树表格_快速工具栏',
  codeName: 'region_tree_grid_quicktoolbar',
  appDataEntityId: 'web.region',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.region_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.region_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '区划编辑视图',
      refAppViewId: 'web.region_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      gridStyle: 'TREEGRID',
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFTREEGRIDCOLUMN',
          hideMode: 3,
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'code',
          excelCaption: '编码',
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '编码',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'code',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'web.mock__cl_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'id',
          excelCaption: '标识',
          appDEFieldId: 'id',
          treeColumnMode: 2,
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.REGION.ID',
          },
          caption: '标识',
          codeName: 'id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hiddenDataItem: true,
          id: 'id',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'parent_id',
          excelCaption: '上级区划标识',
          appDEFieldId: 'parent_id',
          treeColumnMode: 4,
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '上级区划标识',
          codeName: 'parent_id',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hiddenDataItem: true,
          id: 'parent_id',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'code',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'status',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_emptydata',
        appDataEntityId: 'web.region',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.region',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_newaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.*.NEW',
              },
              caption: '新建',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-file-text-o',
                glyph: 'xf0f6@FontAwesome',
              },
              tooltip: '新建',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.*.NEW',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'open_document@region',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '打开文档',
              itemType: 'DEUIACTION',
              tooltip: '打开文档',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'open_about@region',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '打开关于',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-info-circle',
                glyph: 'xf05a@FontAwesome',
              },
              tooltip: '打开关于',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction3',
            },
          ],
          codeName: 'tree_grid_quicktoolbar_treegrid_quicktoolbar',
          controlType: 'TOOLBAR',
          logicName: '树表格_快速工具栏_工具栏',
          appDataEntityId: 'web.region',
          controlParam: {
            id: 'treegrid_quicktoolbar',
          },
          modelId: 'f4a9fdc4d0af1d4bdeb3e0447cc8f120',
          modelType: 'PSDETOOLBAR',
          name: 'treegrid_quicktoolbar',
          id: 'tree_grid_quicktoolbar_treegrid_quicktoolbar',
        },
      ],
      codeName: 'treegrid_quicktoolbar',
      controlType: 'TREEGRID',
      logicName: '树表格_快速工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'treegrid',
      },
      modelId: 'a14bd7de76d5c56b971612709f36f8c5',
      modelType: 'PSDEGRID',
      name: 'treegrid',
      id: 'web.region.treegrid_quicktoolbar',
    },
    {
      codeName: 'tree_grid_quicktoolbar_toolbar',
      controlType: 'TOOLBAR',
      logicName: '树表格_内置工具栏',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'a0028852d4f4e8a9794c5a90ed3bb4d6',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'tree_grid_quicktoolbar_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main28',
      controlType: 'SEARCHFORM',
      logicName: '树表格_快速工具栏_搜索表单',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchform',
      },
      modelId: '7475c0d1e739a1fe5d4eedcebfbf0aec',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.region.main28',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '树表格_快速工具栏',
      codeName: 'tree_grid_quicktoolbar_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_grid_quicktoolbar_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格_快速工具栏',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e91c59e28751e1fcb0167914d62357fa',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONTreeGrid_quicktoolbar',
  id: 'web.region_tree_grid_quicktoolbar',
};
