export default {
  tabLayout: 'FLOW',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'gridexpbarTabExpView',
  deviewId: '9c915415993f0cca76e263caaac73a36',
  accUserMode: 3,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '表格导航栏分页导航视图',
  codeName: 'region_gridexpbar_tab_exp_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '基础',
          appViewId: 'web.region_grid_exp_view',
          id: 'base',
        },
        {
          caption: '导航参数',
          appViewId: 'web.region_grid_navparam_grid_exp_view',
          id: 'navparam',
        },
        {
          caption: '缓存',
          appViewId: 'web.region_grid_tab_cache_tab_exp_view',
          id: 'cache',
        },
        {
          caption: '快速搜索提示分隔符',
          appViewId: 'web.region_grid_separator_grid_exp_view',
          id: 'query',
        },
      ],
      dataRelationTag: 'DataRelation3',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_gridexpbar_tab_exp_view__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation3',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: '381b80f89530ade6df0db635a0ac2055',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation3',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '表格导航栏分页导航视图',
      codeName: 'gridexpbar_tab_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'gridexpbar_tab_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格导航栏分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '82ea566cb7aa6e7e0db7f11fd65b2ff3',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONgridexpbarTabExpView',
  id: 'web.region_gridexpbar_tab_exp_view',
};
