export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'gridSeparatorGridExpView',
  deviewId: '389e5f43145a6fcf35109aa48850a27b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '提示分隔符',
  codeName: 'region_grid_separator_grid_exp_view',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewMsgGroupId: 'vmgroup26',
  controls: [
    {
      title: '提示分隔符',
      xdataControlName: 'gridexpbar_grid',
      enableCounter: true,
      enableSearch: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realOpenMode: 'POPUPMODAL',
          realTitle: '区划信息',
          refAppViewId: 'web.region_info_view',
          name: 'EXPITEM:DEFAULT',
          id: 'expitem:default',
        },
      ],
      controls: [
        {
          aggMode: 'NONE',
          columnEnableFilter: 2,
          columnEnableLink: 2,
          groupMode: 'NONE',
          groupStyle: 'DEFAULT',
          degridColumns: [
            {
              clconvertMode: 'NONE',
              dataItemName: 'name',
              excelCaption: '名称',
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              aggMode: 'NONE',
              align: 'LEFT',
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.REGION.NAME',
              },
              caption: '名称',
              codeName: 'name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              width: 150,
              widthUnit: 'PX',
              enableSort: true,
              id: 'name',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'parent_name',
              excelCaption: '上级区划',
              linkAppViewId: 'web.region_redirect_view',
              linkValueItem: 'parent_id',
              appDEFieldId: 'parent_name',
              valueType: 'SIMPLE',
              enableLinkView: true,
              aggMode: 'NONE',
              align: 'LEFT',
              caption: '上级区划',
              codeName: 'parent_name',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              width: 100,
              widthUnit: 'PX',
              enableSort: true,
              id: 'parent_name',
            },
            {
              clconvertMode: 'NONE',
              dataItemName: 'path',
              excelCaption: '全路径',
              appDEFieldId: 'path',
              valueType: 'SIMPLE',
              aggMode: 'NONE',
              align: 'LEFT',
              caption: '全路径',
              codeName: 'path',
              columnType: 'DEFGRIDCOLUMN',
              noPrivDisplayMode: 1,
              width: 100,
              widthUnit: 'PX',
              enableSort: true,
              id: 'path',
            },
          ],
          degridDataItems: [
            {
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'name',
            },
            {
              appDEFieldId: 'parent_name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'parent_name',
            },
            {
              appDEFieldId: 'path',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'path',
            },
            {
              appDEFieldId: 'id',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'srfkey',
            },
            {
              appDEFieldId: 'id',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'srfdataaccaction',
            },
            {
              appDEFieldId: 'parent_id',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'parent_id',
            },
            {
              appDEFieldId: 'name',
              valueType: 'SIMPLE',
              dataType: 25,
              id: 'srfmajortext',
            },
          ],
          degridEditItems: [
            {
              caption: '标识',
              codeName: 'srfkey',
              enableCond: 3,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'srfkey',
              },
              allowEmpty: true,
              id: 'srfkey',
            },
          ],
          pagingMode: 1,
          pagingSize: 20,
          sortMode: 'REMOTE',
          enableCustomized: true,
          enablePagingBar: true,
          navAppViewId: 'web.region_info_view',
          navViewPos: 'NONE',
          fetchControlAction: {
            appDEMethodId: 'fetch_default',
            appDataEntityId: 'web.region',
            id: 'fetch',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.region',
            id: 'remove',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'main5',
          controlType: 'GRID',
          logicName: '表格导航_快速搜索提示分隔符_表格',
          appDataEntityId: 'web.region',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'gridexpbar_grid',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'gridexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'gridexpbar_grid',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'gridexpbar_load',
            },
          ],
          controlParam: {
            ctrlParams: {
              SEARCHPHSEPARATOR: '，',
            },
            id: 'gridexpbar_grid',
          },
          modelId: '0be56a6c1639ecf009e4792410c7032c',
          modelType: 'PSDEGRID',
          name: 'gridexpbar_grid',
          id: 'web.region.main5',
        },
      ],
      codeName: 'grid_separator_grid_exp_view_gridexpbar',
      controlType: 'GRIDEXPBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        ctrlParams: {
          SEARCHPHSEPARATOR: '，',
        },
        id: 'gridexpbar',
      },
      width: 750,
      modelId: 'b8038dd298f19437dd98c6ed939a53ff_gridexpbar',
      modelType: 'PSEXPBAR',
      name: 'gridexpbar',
      id: 'grid_separator_grid_exp_view_gridexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '提示分隔符',
      codeName: 'grid_separator_grid_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_separator_grid_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '表格导航_快速搜索提示分隔符',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'b8038dd298f19437dd98c6ed939a53ff',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONgridSeparatorGridExpView',
  id: 'web.region_grid_separator_grid_exp_view',
};
