export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'TreeGrid_logictabexpview',
  deviewId: 'adb5f182b485db91be2e72afcbde9e95',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REGION',
  },
  caption: '树表格_动态逻辑分页导航视图',
  codeName: 'region_tree_grid_logictabexpview',
  appDataEntityId: 'web.region',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TabExpView',
      id: 'engine',
    },
  ],
  controls: [
    {
      dedrtabPages: [
        {
          caption: '默认值',
          appViewId: 'web.region_tree_grid_defaultval',
          id: 'treegrid_defaultval',
        },
        {
          caption: '动态启用',
          appViewId: 'web.region_tree_grid_enable',
          id: 'treegrid_enable',
        },
        {
          caption: '动态空输入',
          appViewId: 'web.region_tree_grid_require',
          id: 'treegrid_require',
        },
      ],
      dataRelationTag: 'DataRelation12',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      editItemCaption: '区划',
      uniqueTag: 'region_tree_grid_logictabexpview__tabexppanel',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_relation12',
      controlType: 'DRTAB',
      appDataEntityId: 'web.region',
      controlParam: {
        id: 'tabexppanel',
      },
      modelId: 'c4823ed98c350ddbde04a35200b165a4',
      modelType: 'PSDEDRTAB',
      name: 'tabexppanel',
      id: 'data_relation12',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REGION',
      },
      caption: '树表格_动态逻辑分页导航视图',
      codeName: 'tree_grid_logictabexpview_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.region',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_grid_logictabexpview_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.region',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '树表格_动态逻辑分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '4b95a3c7c0eeb02b832a5783cee55a59',
  modelType: 'PSAPPDEVIEW',
  name: 'REGIONTreeGrid_logictabexpview',
  id: 'web.region_tree_grid_logictabexpview',
};
