export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'baseinfo_edit_view',
  deviewId: '9695c4b2f3c0c88aa5f01ad994eb7551',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REPORT',
  },
  caption: '基础信息变更',
  codeName: 'report_baseinfo_edit_view',
  height: 500,
  appDataEntityId: 'web.report',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'baseinfo_edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '基础信息变更_工具栏',
      appDataEntityId: 'web.report',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'c29328e785aba4427329a4ed2561c950',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'baseinfo_edit_view_toolbar',
    },
    {
      autoSaveMode: 1,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.report',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.report',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.report',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.report',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.report',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.report',
        id: 'update',
      },
      enableAutoSave: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                maxLength: 200,
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'name',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.REPORT.NAME',
              },
              caption: '名称',
              codeName: 'name',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'name',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'chart_type',
              editor: {
                singleSelect: true,
                appCodeListId: 'web.mock__bi_chart_type2',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'chart_type',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '图表类型',
              codeName: 'chart_type',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'chart_type',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'group',
              editor: {
                singleSelect: true,
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'group',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '数据集',
              codeName: 'group',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group',
            },
            {
              dataType: 21,
              enableCond: 3,
              itemHeight: 220,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'template_model',
              editor: {
                maxLength: 1048576,
                showMaxLength: true,
                editorHeight: 200,
                editorParams: {
                  HEIGHT: '200',
                },
                editorType: 'TEXTAREA_10',
                valueType: 'SIMPLE',
                editable: true,
                id: 'template_model',
              },
              allowEmpty: true,
              caption: '模板模型',
              codeName: 'template_model',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'template_model',
            },
            {
              dataType: 21,
              enableCond: 3,
              itemHeight: 220,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'desc',
              editor: {
                maxLength: 1048576,
                showMaxLength: true,
                editorHeight: 200,
                editorParams: {
                  HEIGHT: '200',
                },
                editorType: 'TEXTAREA_10',
                valueType: 'SIMPLE',
                editable: true,
                id: 'desc',
              },
              allowEmpty: true,
              caption: '描述',
              codeName: 'desc',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'desc',
            },
            {
              dataType: 9,
              enableCond: 3,
              itemWidth: 230,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'is_system',
              editor: {
                singleSelect: true,
                appCodeListId: 'web.yesno',
                editorType: 'DROPDOWNLIST_100',
                editorWidth: 100,
                valueType: 'SIMPLE',
                editable: true,
                id: 'is_system',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '是否系统类型',
              codeName: 'is_system',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'is_system',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.REPORT.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'baseinfo_edit_view_form',
      controlType: 'FORM',
      logicName: '基础信息变更_表单',
      appDataEntityId: 'web.report',
      controlParam: {
        id: 'form',
      },
      modelId: 'a9a5fb2386558897521c4883ea032a2e',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.report.baseinfo_edit_view_form',
    },
    {
      codeName: 'baseinfo_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.report',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'baseinfo_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REPORT',
      },
      caption: '基础信息变更',
      codeName: 'baseinfo_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.report',
      controlParam: {},
      name: 'captionbar',
      id: 'baseinfo_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.report',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '基础信息变更',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  width: 600,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'bece1d57faf7e09e1ec2b9d42df6e5bf',
  modelType: 'PSAPPDEVIEW',
  name: 'reportbaseinfo_edit_view',
  id: 'web.report_baseinfo_edit_view',
};
