export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'EditView',
  deviewId: '8cacaf3fc72d07ed70164cb84a2a766f',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.UA_GROUP_DETAIL',
  },
  caption: '界面行为组成员',
  codeName: 'ua_group_detail_edit_view',
  appDataEntityId: 'web.ua_group_detail',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.SAVE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.SAVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem10',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'sx-tb-saveandnew',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem12',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandexitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
          },
          caption: '保存并关闭',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'sx-tb-saveandclose',
          },
          tooltip: '保存并关闭',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem11',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem18',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_removeandexitaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
          },
          caption: '删除并关闭',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除并关闭',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem9',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem19',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem21',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem22',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_firstrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '第一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-fast-backward',
            glyph: 'xf049@FontAwesome',
          },
          tooltip: '第一个记录',
          showIcon: true,
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_prevrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '上一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-step-backward',
            glyph: 'xf048@FontAwesome',
          },
          tooltip: '上一个记录',
          showIcon: true,
          id: 'tbitem7',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_nextrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '下一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-step-forward',
            glyph: 'xf051@FontAwesome',
          },
          tooltip: '下一个记录',
          showIcon: true,
          id: 'tbitem6',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_lastrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '最后一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-fast-forward',
            glyph: 'xf050@FontAwesome',
          },
          tooltip: '最后一个记录',
          showIcon: true,
          id: 'tbitem4',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem25',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_helpaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.HELP',
          },
          caption: '帮助',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-question',
            glyph: 'xf128@FontAwesome',
          },
          tooltip: '帮助',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.HELP',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem3',
        },
      ],
      xdataControlName: 'form',
      codeName: 'edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认编辑界面）',
      appDataEntityId: 'web.ua_group_detail',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '48c8f789be8a5522d3003293c1cf2ffb',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.ua_group_detail',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.ua_group_detail',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.ua_group_detail',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.ua_group_detail',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.ua_group_detail',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.ua_group_detail',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'caption',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'caption',
                  },
                  caption: '标题',
                  codeName: 'caption',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'caption',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'platform_type',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.base__platformtype',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'platform_type',
                  },
                  needCodeListConfig: true,
                  caption: '平台类型',
                  codeName: 'platform_type',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'platform_type',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'action_tag',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'action_tag',
                  },
                  caption: '界面行为标记',
                  codeName: 'action_tag',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'action_tag',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'icon_cls',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'icon_cls',
                  },
                  allowEmpty: true,
                  caption: '图标样式',
                  codeName: 'icon_cls',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'icon_cls',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'style',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'style',
                  },
                  allowEmpty: true,
                  caption: '样式',
                  codeName: 'style',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'style',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'button_style',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.base__buttonstyle',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'button_style',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '按钮样式',
                  codeName: 'button_style',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'button_style',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'level',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'web.base__actionlevel',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'level',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  caption: '行为级别',
                  codeName: 'level',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'level',
                },
                {
                  dataType: 21,
                  enableCond: 3,
                  itemHeight: 200,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'enable_logic',
                  editor: {
                    maxLength: 1048576,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'enable_logic',
                  },
                  allowEmpty: true,
                  caption: '启用逻辑',
                  codeName: 'enable_logic',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'enable_logic',
                },
                {
                  dataType: 21,
                  enableCond: 3,
                  itemHeight: 200,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'visible_logic',
                  editor: {
                    maxLength: 1048576,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'visible_logic',
                  },
                  allowEmpty: true,
                  caption: '可见逻辑',
                  codeName: 'visible_logic',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'visible_logic',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  itemHeight: 200,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'tooltip',
                  editor: {
                    maxLength: 2000,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'tooltip',
                  },
                  allowEmpty: true,
                  caption: '提示信息',
                  codeName: 'tooltip',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 12,
                    colMD: 12,
                    colSM: 12,
                    colXS: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'tooltip',
                },
              ],
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.UA_GROUP_DETAIL.MAIN.GROUPPANEL.GROUP1',
              },
              caption: '界面行为组成员基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.UA_GROUP_DETAIL.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.UA_GROUP_DETAIL.MAIN.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'FORM',
      logicName: '主编辑表单',
      appDataEntityId: 'web.ua_group_detail',
      controlParam: {
        id: 'form',
      },
      modelId: '9f1ee9ff284b01d758d8745af978e39b',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.ua_group_detail.main',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.ua_group_detail',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.UA_GROUP_DETAIL',
      },
      caption: '界面行为组成员',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.ua_group_detail',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.ua_group_detail',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '界面行为组成员编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '31a93a4bc3beff2ca227dbce5e05b7c7',
  modelType: 'PSAPPDEVIEW',
  name: 'ua_group_detailEditView',
  id: 'web.ua_group_detail_edit_view',
};
