export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'web.category',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CATEGORY.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CATEGORY.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'enable',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ENABLE',
      },
      logicName: '逻辑有效标识',
      predefinedType: 'LOGICVALID',
      stdDataType: 9,
      name: 'ENABLE',
      id: 'enable',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CATEGORY.CREATE_MAN',
      },
      logicName: '创建人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CATEGORY.CREATE_TIME',
      },
      logicName: '创建时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'parent_id',
      logicName: '父项标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_ID',
      id: 'parent_id',
    },
    {
      codeName: 'sort',
      logicName: '排序',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SORT',
      id: 'sort',
    },
    {
      codeName: 'wf_id',
      logicName: '工作流标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WF_ID',
      id: 'wf_id',
    },
    {
      codeName: 'wf_version_id',
      logicName: '工作流版本',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WF_VERSION_ID',
      id: 'wf_version_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'category_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'create_man',
          logicName: '创建人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '创建时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
        {
          codeName: 'parent_id',
          logicName: '父项标识',
          appDEFieldId: 'parent_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_id',
        },
        {
          codeName: 'sort',
          logicName: '排序',
          appDEFieldId: 'sort',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sort',
        },
        {
          codeName: 'wf_id',
          logicName: '工作流标识',
          appDEFieldId: 'wf_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'wf_id',
        },
        {
          codeName: 'wf_version_id',
          logicName: '工作流版本',
          appDEFieldId: 'wf_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'wf_version_id',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'category_dto',
    },
    {
      codeName: 'category_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_parent_id_eq',
          logicName: '父项标识',
          appDEFieldId: 'parent_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'category_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'category_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'category_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'category_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '预览',
      codeName: 'form_design_preview',
      frontAppViewId: 'web.master_form_design_edit',
      frontProcessType: 'WIZARD',
      fullCodeName: 'category_form_design_preview',
      navigateContexts: [
        {
          key: 'CATEGORY',
          value: 'id',
          name: 'CATEGORY',
          id: 'category',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-eye',
        glyph: 'xf06e@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'form_design_preview',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '表单设计_预览',
      id: 'form_design_preview@category',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '表格设计',
      codeName: 'grid_design',
      frontAppViewId: 'web.psde_field_grid_design',
      frontProcessType: 'TOP',
      fullCodeName: 'category_grid_design',
      navigateContexts: [
        {
          key: 'PSDATAENTITY',
          value: 'FIELD__CATEGORY_TYPE__${id}@mock.master',
          name: 'PSDATAENTITY',
          id: 'psdataentity',
        },
        {
          key: 'PSDENAME',
          value: 'MASTER',
          rawValue: true,
          name: 'PSDENAME',
          id: 'psdename',
        },
      ],
      navigateParams: [
        {
          key: 'category_id',
          value: 'id',
          id: 'category_id',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'grid_design',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '表格_设计',
      id: 'grid_design@category',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '预览',
      codeName: 'grid_preview',
      frontAppViewId: 'web.master_grid_design_preview',
      frontProcessType: 'WIZARD',
      fullCodeName: 'category_grid_preview',
      navigateContexts: [
        {
          key: 'CATEGORY_ID',
          value: 'id',
          name: 'CATEGORY_ID',
          id: 'category_id',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-eye',
        glyph: 'xf06e@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'grid_preview',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '表格_预览',
      id: 'grid_preview@category',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '表单设计',
      codeName: 'open_edit_form_design_view',
      frontAppViewId: 'web.psdeformdesign_modal',
      frontProcessType: 'WIZARD',
      fullCodeName: 'category_open_edit_form_design_view',
      navigateContexts: [
        {
          key: 'PSDEFORM',
          value: 'FIELD__CATEGORY_ID__${id}@mock.master.form_design',
          name: 'PSDEFORM',
          id: 'psdeform',
        },
        {
          key: 'PSDATAENTITY',
          value: 'FIELD__CATEGORY_ID__${id}@mock.master',
          name: 'PSDATAENTITY',
          id: 'psdataentity',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit_form_design_view',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '表单设计',
      id: 'open_edit_form_design_view@category',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '查看审批单',
      codeName: 'workflow_approve',
      frontAppViewId: 'web.master_workflow_design_grid',
      frontProcessType: 'WIZARD',
      fullCodeName: 'category_workflow_approve',
      sysImage: {
        cssClass: 'fa fa-eye',
        glyph: 'xf06e@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'workflow_approve',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '流程_查看审批单',
      id: 'workflow_approve@category',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '流程设计',
      codeName: 'workflow_design',
      frontAppViewId: 'web.pswfversiondesign',
      frontProcessType: 'WIZARD',
      fullCodeName: 'category_workflow_design',
      navigateContexts: [
        {
          key: 'PSDATAENTITY',
          value: 'mock.master',
          rawValue: true,
          name: 'PSDATAENTITY',
          id: 'psdataentity',
        },
        {
          key: 'PSWFVERSION',
          value: 'wf_version_id',
          name: 'PSWFVERSION',
          id: 'pswfversion',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'workflow_design',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '流程_设计',
      id: 'workflow_design@category',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '新建审批单',
      codeName: 'workflow_new',
      frontAppViewId: 'web.master_workflow_design_edit',
      frontProcessType: 'WIZARD',
      fullCodeName: 'category_workflow_new',
      navigateParams: [
        {
          key: 'category_name',
          value: 'name',
          id: 'category_name',
        },
        {
          key: 'category_id',
          value: 'id',
          id: 'category_id',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-file-text-o',
        glyph: 'xf0f6@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'workflow_new',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.category',
      name: '流程_新建审批单',
      id: 'workflow_new@category',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'category',
  deapicodeName: 'category',
  deapicodeName2: 'categories',
  deapitag: 'CATEGORY',
  decodeName: 'CATEGORY',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.CATEGORY',
  },
  logicName: '分类',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'api',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'CATEGORY',
  id: 'web.category',
  codeName2: 'categories',
  requestPaths: [],
};
